### ISSUE TITLE
Image sizes

### ISSUE THREAD

**Issue by richgilbank** [Shopify/js-buy-sdk#10]
Images returned from the API are the raw image size uploaded to Shopify, i.e. 
`https://cdn.shopify.com/s/files/1/1015/1595/products/blackhelmet_store.png?v=1446233645`

We should be able to return these in the various sizes Shopify produces, which requires adding a suffix to the file name matching [these sizes](https://docs.shopify.com/themes/liquid/filters/url-filters#size-parameters). 

i.e. instead of `product.selectedVariantImage.src`, maybe `product.selectedVariantImage('thumb')`?

@minasmart @tessalt @harismahmood89

**Comment by minasmart** [comment]
Closing in favour of #51, but keeping it around for the links and details. :smile:
