### ISSUE TITLE
Question: Can rely on 'attrs'?

### ISSUE THREAD

**Issue by yoadsn** [Shopify/js-buy-sdk#100]
(Is this the right place for discussion and questions?)
I want to display the product description after fetching it.
I can see the description is only available under the `attrs` property of the product model.
Can I rely on this API or is it considered internal?

What is the best practice here? (I can see not reference to the attrs property in the docs.)

Thanks!

**Comment by minasmart** [comment]
It's considered internal. Also, I'm pretty sure the field you're looking for is called `body_html`. I'm going to create an issue to expose this field though. I think it was a miss during the initial push to get this out. Thanks for mentioning it!

**Comment by minasmart** [comment]
Closing in favour of #103
