### ISSUE TITLE
Expose product descriptions under `bodyHtml`

### ISSUE THREAD

**Issue by minasmart** [Shopify/js-buy-sdk#103]
We left this out from the product model. We should be proxying it so it's available as `product.bodyHtml` so developers don't have to rely on internal state (`product.attrs.body_html`).

Original issue: #100

**Comment by yoadsn** [comment]
Thanks @minasmart.
I'll try to PR this one when I get a moment.
In the meanwhile, I'm assuming it's safe to rely on it.
