### ISSUE TITLE
Collects

### ISSUE THREAD

**Issue by peteshilling** [Shopify/js-buy-sdk#113]
The ability to retrieve collection and product collect data using the SDK would be really helpful. For my project I had to display collections in a custom sort order, which is only possible if you can get the collect data  — GET /admin/collects.json?collection_id={id} in the Shopify API.

On the product detail page I needed to show related products, which meant I needed to know what collections the product was in — GET /admin/collects.json?product_id={id}.

**Comment by minasmart** [comment]
Our internal APIs don't actually support this, but it will be a feature in our next major release. It's underway right now.

**Comment by ar7casper** [comment]
Hi, any news about it?
