### ISSUE TITLE
Multiple Buy Buttons on a page?

### ISSUE THREAD

**Issue by cooliodoc** [Shopify/js-buy-sdk#115]
Hey guys,

Trying to set up  two different buy buttons on the same page with different products that add variants to the same cart. I was a bit surprised that the cart example didn't do this. Is there an example anywhere of how to do this?

**Comment by Cam** [comment]
Interesting question. I'd love to hear thoughts on this, but it seems to me like this may be more of an API implementation than a simple buy button one. No?

**Comment by richgilbank** [comment]
Hey folks, 
Is there a particular issue you've come up against preventing this? You should be able to simply call `cart.addVariants({variant: myVariant, quantity: 1})` with the second variant, just as with the first.

**Comment by cooliodoc** [comment]
Thanks Rich,
I thought that might be the case. I would suggest some updated example code that doesn't couple everything so tightly to having just a single buy button (I'd probably also suggest not using sass in the sole example). Just can't figure out the javascipt for it, but that's probably because I'm not a javascript pro.

**Comment by richgilbank** [comment]
Thanks for the suggestion, I'll take a look at adding an example with multiple buttons on it. We chose to go the direction of a single product for the sake of simplicity, but we'll be providing more examples and reference implementations in the near future 😄

**Comment by nzrubin** [comment]
hello @richgilbank ! im looking forward to view the example with multiple buttons please! :)

**Comment by mcmanimie** [comment]
Not sure if this is this what you were looking for but here's what I did: https://ecommerce.shopify.com/c/ecommerce-design/t/one-product-page-with-multiple-products-buy-buttons-323787#comment-434084
