### ISSUE TITLE
[DOCSITE][BUG] No active class for the sidebars.

### ISSUE THREAD

**Issue by dtKinger** [Shopify/js-buy-sdk#12]
It would be nice if the active section of both the left and right sidebars were styled differently.

**Comment by richgilbank** [comment]
I _think_ this is now completed. @harismahmood89 can you confirm?

**Comment by harismahmood89** [comment]
@richgilbank we have cleaner navigations now, but no auto-highlight on scrolling. Do we want to implement that?

**Comment by minasmart** [comment]
@richgilbank @harismahmood89 is this closable?

**Comment by richgilbank** [comment]
It would really only be for the examples anyway, I believe. So yeah, let's close it.
