### ISSUE TITLE
Redirect to cart instead of checkout

### ISSUE THREAD

**Issue by geoffchan23** [Shopify/js-buy-sdk#120]
Is there a way that I can generate a URL to the cart instead of the checkout? It looks like you can do this with the embedded buy button, but I don't see a way to do this with the Buy SDK.

The reason that I need to do this is that our store's cart page adds tracking as well as custom properties and attributes to our products before going to checkout. In the future we'll be looking at a better way of doing this so that we can send users straight to checkout. But for the time being it would be great to be able to generate a cart URL with products added from the Buy SDK.

**Comment by minasmart** [comment]
There isn't currently a way to do this. The checkout permalink does pre-load the cart, but it takes the user directly to the checkout. As far as I know, there's no way to force the user to return to the cart page. Additionally, checkout permalinks don't support line item properties at the moment. Depending on your solution, you might be able to extract the variant id and quantities from the cart, and build a hidden form and submit it like in this support thread solution: https://ecommerce.shopify.com/c/ecommerce-design/t/passing-product-line-item-properties-to-cart-via-permalink-196271.

Hopefully that helps! If you have any problems please let me know.

**Comment by geoffchan23** [comment]
Thank you for your response! We decided on a workaround solution where we send the user to a custom page to add our custom properties and attributes, and then send them to the checkout page.

**Comment by minasmart** [comment]
Sounds good! I'm going to close this issue, but I'll see if there's a way we can work in a feature around these sorts of problems.

**Comment by derekmorin** [comment]
Hi @minasmart  and @geoffchan23 I'm about to launch this feature to preload the cart via a link. Here's how I see it, but I would really like you guys to tell me some ideas, must have or nice to have features:
- When he clicks the link, the user falls on the Cart page
- The cart is pre-populated
- The user can edit the cart, remove or add items, remove or add quantities
- The store owner can build "product bundles" and multiple links
- The store owner can track link clicks and purchases, and then optimize the "product bundles"
- The store owner can send create links that send users directly to the checkout page, too.

What do you think?

**Comment by geoffchan23** [comment]
Hi Derek,

Your list of features looks good! I know that we would definitely find this
useful.

I was wondering if you would also be able to add the ability to add custom
attributes for products through the link?

Geoff

On Sun, Jul 10, 2016 at 12:04 PM, derekmorin <notifications@github.com>
wrote:

> Hi @minasmart <https://github.com/minasmart> and @geoffchan23
> <https://github.com/geoffchan23> I'm about to launch this feature to
> preload the cart via a link. Here's how I see it, but I would really like
> you guys to tell me some ideas, must have or nice to have features:
>
>    - When he clicks the link, the user falls on the Cart page
>    - The cart is pre-populated
>    - The user can edit the cart, remove or add items, remove or add
>    quantities
>    - The store owner can build "product bundles" and multiple links
>    - The store owner can track link clicks and purchases, and then
>    optimize the "product bundles"
>    - The store owner can send create links that send users directly to
>    the checkout page, too.
>
> What do you think?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Shopify/js-buy-sdk/issues/120#issuecomment-231596493>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAvxj27mSUx7cAvtYTnXmfrIHLjzL_mfks5qURghgaJpZM4Iilr2>
> .
>



-- 
Geoffrey Chan
Designer & Web Developer
416-827-2426 | www.geoffreychan.com

**Comment by timbroder** [comment]
@minasmart did this ever become possible? Thanks!
