### ISSUE TITLE
[docs] Download/CDN version outdated

### ISSUE THREAD

**Issue by richgilbank** [Shopify/js-buy-sdk#123]
The downloads at http://shopify.github.io/js-buy-sdk/downloads/ at all showing 0.1.0 😕

**Comment by minasmart** [comment]
I'll take a look at how those are generated.

**Comment by minasmart** [comment]
#yolo-fixed https://github.com/Shopify/js-buy-sdk/commit/85d3f1b5cd70c003ca7e83e5b7117b8ca125e993

**Comment by minasmart** [comment]
This should get automated though.
