### ISSUE TITLE
Error in IE when accessing selectedVariant.price

### ISSUE THREAD

**Issue by art0rz** [Shopify/js-buy-sdk#126]
When attempting to access a property on a `selectedVariant` before `selectedVariant` has ever ben accessed, shopify-buy throws error `Invalid option selection for storage`.

```
Unhandled rejection Error: Invalid option selection for storage.
   at selected.set (http://website/shopify/shopify-buy.globals.js:1590:11)
   at constructor (http://website/shopify/shopify-buy.globals.js:1544:7)
   at superWrapper (http://website/shopify/shopify-buy.globals.js:698:7)
   at Anonymous function (http://website/shopify/shopify-buy.globals.js:1454:11)
   at options.get (http://website/shopify/shopify-buy.globals.js:1439:9)
   at selections.get (http://website/shopify/shopify-buy.globals.js:1489:9
```

I can reproduce this by simply running:

```
console.log(product.selectedVariant.price);
```

I can work around this by accessing `selectedVariant` before any properties on the variant:

```
product.selectedVariant;
console.log(product.selectedVariant.price);
```

This is reproducable in IE11 and 10.

Edit: I can no longer work around it by accessing `selectedVariant` first.

**Comment by minasmart** [comment]
Is this in all instances of selected variant? There's the possibility that the variant you've built up with the selected options isn't actually a valid variant. If that's the case, there may be a bug in the `selectedVariant` getter.

Can you show a bit more of the code that leads up to this? specifically, how you're selecting options?

**Comment by lentfert** [comment]
Hi there, we experience the same issue (IE 10/11 only, works like a charm on Chrome,FF,Safari etc) for the collection fetch.. Whenever we call the attributes IE returns an error. This is the section of the code that causes the IE error: 

client.fetchQueryProducts({ collection_id: product_group }).then( function( products ){ 
        
            var productslength =    products.length;
        
            
            //loop
            if( productslength !== 0 ) {
                for (var i = 0; i < productslength; i++) {
                                        
                    product = products[i];  
                            
                    
                    if( i == 0 ){ $(tab_frame+' .shopify-products').html('<div class="product-group"></div>'); }
                                         
                    var selectedVariant         = product.selectedVariant;                   
                    var selectedVariantImage    = product.selectedVariantImage;
                    var currentOptions          = product.options;  
                     
                    var product_item_template   = $('#producItemTemplate').html();                                                  
                    
                    $(tab_frame+' .shopify-products .product-group').append(product_item_template)
                    $(tab_frame+' .shopify-products .product-group .shopify-product-item:last-child').find('.variant-image').attr('src',selectedVariantImage.src);                  
                    $(tab_frame+' .shopify-products .product-group .shopify-product-item:last-child').find('.product-title').text(products[i].title);
                    $(tab_frame+' .shopify-products .product-group .shopify-product-item:last-child').find('.variant-title').text(selectedVariant.title);
                    $(tab_frame+' .shopify-products .product-group .shopify-product-item:last-child').find('.variant-price').text('$ '+selectedVariant.price);
                    $(tab_frame+' .shopify-products .product-group .shopify-product-item:last-child').find('.variant-sku').text(selectedVariant.attrs.variant.sku);                  
                    $(tab_frame+' .shopify-products .product-group .shopify-product-item:last-child').find('.product-title').append(selectedVariant.attrs.product.attrs.body_html);

Thank you!

**Comment by mcrider** [comment]
Anyone get this to work?  IE11 is completely borked for me (and windows phone).

**Comment by minasmart** [comment]
Sorry, there are two issues in this thread (cross origin and ES5 getter support) would you mind opening a new issue referencing the code that's causing an error and relaying the error message? Thank you!
