### ISSUE TITLE
Setting "Continue Shopping" button via js-buy-sdk?

### ISSUE THREAD

**Issue by tom-james-watson** [Shopify/js-buy-sdk#128]
If you make an order via a shopify store, when you complete checkout there is a "Continue Shopping" button that takes you back to the storefront.

If you make an order that was created via the js-buy-sdk, this button is not shown. Is it possible to somehow set a value for this button and have it be shown? It would be good to be able to provide a link back to my shop.

Thanks!

**Comment by richgilbank** [comment]
Hey @tom-james-watson,
This should be doable by adding custom content to the order status page - more info here:
https://help.shopify.com/themes/customization/order-status#add-additional-content-and-scripts
Hope this helps!

**Comment by tom-james-watson** [comment]
Thanks - managed to get a reasonably styled button with

```
<a href="<website>" style="color: white">
<button class="btn" style="margin-top: 20px;margin-bottom:-20px;">
  <span class="btn__content">Continue Shopping</span>
</button>
</a>
```

It would be better at the bottom of the screen, but achieves what I wanted.
