### ISSUE TITLE
can't get createCart() to work

### ISSUE THREAD

**Issue by kevinzaki** [Shopify/js-buy-sdk#129]
Can't figure this out.  (Most of the below code is for test purposes)

Fetching all products works: (The reason I am showing the working code is so you can see everything else is right, the cart route immediately follows the products route.
`myRouter.route('/products')
  .get(function(req, res){
    shopClient.fetchQueryProducts({collection_id: 233148358})
      .then(function (product) {
         console.log(product);
      })
      .catch(function () {
        console.log('Request failed');
      })
});`

The following to createCart and log the cart ID does not work.
`myRouter.route('/cart').get(function(req, res){
  shopClient.createCart()
    .then(function (newCart) {
      console.log(newCart.id);
  })
  .catch(function () {
    console.log('Request failed');
  })
});`

**Comment by minasmart** [comment]
A couple things: Are you planning on managing cart associations to users yourself? If you're not, use `fetchRecentCart`. Also, if you `console.error(error)` the error that's sent to catch, can you post the trace?

**Comment by kevinzaki** [comment]
I do plan on managing cart associations.  Basically my plan is to use the buy SDK to generate and manage carts for products stored on Shopify.  Once I have a completed cart I am going to use the regular API to create an order and process payments separately.  The error I am getting is the following:

`[ReferenceError: localStorage is not defined]`

**Comment by minasmart** [comment]
What environment are you running this in? Node or browser?

**Comment by kevinzaki** [comment]
Node, running my server using Gulp locally at the moment.

**Comment by minasmart** [comment]
Ah... OK. Yeah. This is a thing we failed to implement.

For the time being, somewhere in your startup code, if you did something like 

```javascript
global.localStorage = {
  _storage: {},
  setItem: function(key, value) {
    this._storage[key] = value;
  },
  getItem: function(key) {
    return this._storage[key]
  },
  clear: function() {
    this._storage = {};
  }
};
```

I understand this is ugly, but it'll get you by for now. I'll post here when we make this functionality work properly in node.

**Comment by kevinzaki** [comment]
Thanks it worked, wouldn't of figured that out without some help.

**Comment by muzuitech** [comment]
How can I set up background colors and other stuffs using createCart() ? Anyone have idea. I am researching but not able to find anything which can solve. 

Thanks

**Comment by rebeccajfriedman** [comment]
@muzuitech Can you please create a new issue for this in the https://github.com/Shopify/buy-button-js repo?
