### ISSUE TITLE
Multi Variant Issue.

### ISSUE THREAD

**Issue by richyrb00** [Shopify/js-buy-sdk#130]
Hi,

I'm currently testing the Buy SDK on a local machine.

I've installed it and ran on localhost:4200 as advised. and then standard cart example works fine. 

When i have updated the api key and the shop domain and the product in the fetchProduct that loads the correct product details.

The Issue:

Our product has 3 variants (size name, product size, box size) which using the standard cart example loops through the variants and pulls in the 3 select drop downs. 

But now only the default loaded selection works. Even if i choose the specific valid options on the other options it causes an error in console.

[Error] TypeError: undefined is not an object (evaluating 'this.selectedVariant.image')
	get (shopify-buy.polyfilled.globals.js:3545)
	(anonymous function) (index.js:132)
	dispatch (jquery-2.2.1.min.js:3:7522)
	handle (jquery-2.2.1.min.js:3:5603)
[Error] Error: Invalid option selection for Matress dimensions.
	set (shopify-buy.polyfilled.globals.js:3612)
	(anonymous function) (index.js:129)
	dispatch (jquery-2.2.1.min.js:3:7522)
	handle (jquery-2.2.1.min.js:3:5603)
[Error] TypeError: undefined is not an object (evaluating 'product.selectedVariant.id')
	buyButtonClickHandler (index.js:168)
	dispatch (jquery-2.2.1.min.js:3:7522)
	handle (jquery-2.2.1.min.js:3:5603)
[Error] Error: Invalid option selection for Box dimensions.
	set (shopify-buy.polyfilled.globals.js:3612)
	(anonymous function) (index.js:129)
	dispatch (jquery-2.2.1.min.js:3:7522)
	handle (jquery-2.2.1.min.js:3:5603)
[Error] TypeError: undefined is not an object (evaluating 'product.selectedVariant.id')
	buyButtonClickHandler (index.js:168)
	dispatch (jquery-2.2.1.min.js:3:7522)
	handle (jquery-2.2.1.min.js:3:5603)

SO i tried to then only grab the first Variant row. (size name) as this would the preferred option for a user to select their option. 

so Line 60 on index.js in the cart example i changed

        return elements;

to

         return elements[0];

This then only returns the one select drop down as required, although it still doesn't update the product details as required with the same errors.

Does the code need updating to account for the 3 variants originally? is this a bug?

**Comment by harismahmood89** [comment]
Hi @richyrb00 - could you provide your store name (example.myshopify.com) and the code snippet you're working with and I'll take a look.

 Also note that the cart example was recently updated. Are you working with the previous version or the updated version?

**Comment by richyrb00** [comment]
Haris,

I've looked at your latest commit on the cart example and i can confirm that this is the version i have also.

I cannot publicly give you details, is there a way i can send you the store details in private?

**Comment by harismahmood89** [comment]
@RichardBlair sure thing! You can send your info to buybutton@shopify.com

**Comment by RichardBlair** [comment]
You probably mean @richyrb00

**Comment by harismahmood89** [comment]
whoops, sorry!

**Comment by richyrb00** [comment]
@harismahmood89 did you get my email?

**Comment by harismahmood89** [comment]
I did! Will get back to you soon @richyrb00 :)

**Comment by richyrb00** [comment]
Any luck @harismahmood89 ?

**Comment by harismahmood89** [comment]
Hey @richyrb00, wanted to check in and see if the email made sense and you got things working, or at least progressing!

**Comment by richyrb00** [comment]
@harismahmood89 i like your approach although what we did was get the super wrapper prams and then search by slug based on the product we want. then we use those details and variants to display the only available variants for the product. that way there is no mismatch of variants of all the available options and everything is tied together ready for sending to the cart.

**Comment by harismahmood89** [comment]
@richyrb00 oh awesome! glad you got it working 👍
