### ISSUE TITLE
Broken Serializer in CDN version?

### ISSUE THREAD

**Issue by ntdb** [Shopify/js-buy-sdk#134]
I've pulled down a few versions of the library to try to find something that works, whenever I request products or collections I get an array of `superWrapper` objects that do not contain the JSON payload I see coming back from the server.

Digging in a little bit I've found that that the serializer is the culprit. The `deserializeMultiple` function I get from the CDN looks like this:

```
    deserializeMultiple: function deserializeMultiple(type) {
      var _this = this;

      var collectionPayload = arguments.length <= 1 || arguments[1] === undefined ? {} : arguments[1];
      var metaAttrs = arguments.length <= 2 || arguments[2] === undefined ? {} : arguments[2];

      var models = collectionPayload[this.rootKeyForType(type) + 's'];

      return models.map(function (attrs) {
        var model = _this.modelFromAttrs(type, attrs, metaAttrs);

        return model;
      });
    }
```

and it's called like this:

```
serializer.deserializeMultiple(type, payload, meta)
```

Note that `deserializeMultiple` doesn't even receive the `payload` object. I can't find a `deserializeMultiple` signature that looks like this anywhere in the repo history. Any ideas? For now I'm going to pull down a zip file and use that but it would be great to not have a fundamentally broken version of the library on the CDN.

**Comment by thegreengrass** [comment]
+1 I'm coming up against this right now. This is very frustrating.

**Comment by ntdb** [comment]
@thegreengrass I closed this issue because I realized I was using the response improperly. I always log out API responses to see what I'm dealing with but the `superWrapper` objects were not clear at all. Here's what my product/collection code looks like, hopefully it's helpful (let me know if you need me to convert it from coffeescript)

```
all_products = {}
cart = null

$ ->
  shopClient = ShopifyBuy.buildClient(
    apiKey: 'KEY'
    myShopifyDomain: 'DOMAIN'
    appId: 'ID'
  )

  # Get the cart
  shopClient.createCart().then((newCart) -> cart = newCart)

  shopClient.fetchAllCollections()
  .then((collections) ->
    for collection in collections
      collection = collection.attrs
    return Promise.all(collections.map((collection) ->
      collection = collection.attrs
      return shopClient.fetchQueryProducts({ collection_id: collection.collection_id })
      .then((products) ->
        for product in products
          all_products[product.attrs.product_id] = product
      )
      .catch((e) -> console.log(e))
    ))
  )
  .catch((e) -> console.log(e))
```

Note the `product.attrs` and `collection.attrs` syntax, I think that was the key for me for getting at product and collection information.

**Comment by thegreengrass** [comment]
Thanks for the update, I ended up moving on to .fetchQueryProducts(), too. It's odd there's no documentation for the Collection model in the API, that didn't help when trying to figure out what to do with the result of .fetchAllCollections().
