### ISSUE TITLE
Mobile Safari Issue

### ISSUE THREAD

**Issue by haozeng** [Shopify/js-buy-sdk#136]
I ran into one issue with mobile safari running in IOS 9.2. It works in safari desktop. The following func never works in mobile safari. newCart never returns from the createCart() and its promise. I first thought b/c mobile safari doesn't support promise, but it actually does since version 8.0. Is there anything I missed ?

Thanks for looking into it.

```js
window.client.createCart().then(function (newCart) {
    window.cart = newCart;
    localStorage.setItem('lastCartId', window.cart.id);
    cartLineItemCount = 0;

    fetchAndInitProduct()
});
```

**Comment by tessalt** [comment]
are you running in private browsing mode?

**Comment by haozeng** [comment]
Its not private browsing mode. I am running it in my mobile safari. You can reproduce the bug by using USB cable to connect your mobile safari to your desktop and by clicking the Develop tab in the top, and then you open you developer console and try to fire a call to createCart there.

**Comment by tessalt** [comment]
I'm unable to reproduce this in regular browsing mode, however this is a known issue in private browsing mode we are looking into (https://github.com/Shopify/js-buy-sdk/issues/133). 

![image](https://cloud.githubusercontent.com/assets/1789029/16116525/7098ec4e-339b-11e6-86f1-a58f91bd37de.png)
(remote debugging from my iPhone running 9.3.2)

**Comment by haozeng** [comment]
I think I was using private browsing mode. Sorry for the confusion. It works fine in non-private browsing mode.
