### ISSUE TITLE
Cart method addVariants is not defined. 

### ISSUE THREAD

**Issue by lopugit** [Shopify/js-buy-sdk#169]
In the docs http://shopify.github.io/js-buy-sdk/api/classes/CartModel.html#method-addVariants

It says to use addVariants to add products to the shopping cart but addVariants is a function which is defined no where, not in the sdk, nor in the javascript file in the cart example. It is used inside addVariantToCart but well yeah. 

It seems to be defined in https://github.com/Shopify/js-buy-sdk/blob/master/src/models/cart-model.js#L82 but is this included in the sdk or what?

I just get an error cart.addVariants is not a function.

Can I also just ask, if I've got a bunch of products in a collection, is it possible to return all of those product ID's in an array?

And what is the easiest way to add a product to the cart, eg. how do you define the selected Variant of the product because it says to use product.selectedVariant for the variant in addVariant. if var product; is just client.fetchProduct(numbers) then can I just use product.selectedVariant or is there something else I need to do?

**Comment by richgilbank** [comment]
Hi @lopugit,

`addVariants` is defined in the SDK. If you're getting that error, I'd double check that your cart exists at that point (remember, cart creation is asynchronous). 

If you have your products in a collection, you can retrieve them all with the `fetchQueryProducts` method: http://shopify.github.io/js-buy-sdk/api/classes/ShopClient.html#method-fetchQueryProducts
ie.
```javascript
shopClient.fetchQueryProducts({collection_id: 12345}).then(function(productsArray) {
  // productsArray holds the products
});
```

As for the variant selection, [this section](http://shopify.github.io/js-buy-sdk/guide/#selecting-variants) of the docs should help get you started 😄 

Hope this helps!

**Comment by lopugit** [comment]
thank you @richgilbank 

I'll learn what asynchronous is, if I could sit with you in a room and a laptop for an hour I'd chew your ear off about the documentation for this, you guys are gonna be the bosses of ecommerce and you're the fuckin dev at the helm of this SDK, it's so awesome. The implementation needs to be made a little easier though. The docs get a little confusing and they contradict themselves when talking about selectedVariants, adding variants, rendering cartlineitems or rendercartlineitem(cartItem). Have you read through the documentation? I've followed instructions to the point where I have to go to a different page and then that page will give me a different method to get to where I was but yeah..

Maybe I'll offer a fork with what I think should change :') Thank you so much for the work though.

Have a good one :) :)
