### ISSUE TITLE
Product Sort Order Within a Collection?

### ISSUE THREAD

**Issue by rgdelato** [Shopify/js-buy-sdk#175]
Is there currently anyway to get the custom sort order of products within a collection (and thus be able to display products in the correct order)?

**Comment by homerjam** [comment]
+1

**Comment by yomexzo** [comment]
that's correct @homerjam 

however, the api exposes a `sort_by` option that currently accepts the following: `updated_at`, `best-selling`, `title-ascending`, `title-descending`, `price-descending`, `price-ascending`, `created-descending`, `created-ascending`, and `collection-default`.

This can be used like this `client.fetchQueryProducts({ sort_by: 'title-descending' })`

`collection-default` is the only one that might not be clear there and it means using the sorting order you specified in the Shopify admin collection page. If you attempt to edit your collection, you would see a section that looks like the below: 

![screen shot 2016-07-22 at 11 37 52 am](https://cloud.githubusercontent.com/assets/3056958/17062398/cd2f1ec0-5000-11e6-9b97-354847d2500e.png)

**Comment by homerjam** [comment]
@yomexzo Great! Thanks for letting me know

**Comment by yomexzo** [comment]
@homerjam, @rgdelato .. i missed something out. It also accepts `manual`.

Manual is the custom ordering you provide in the Shopify Admin when editing/creating your collection as shown below.

![screen shot 2016-07-22 at 12 03 41 pm](https://cloud.githubusercontent.com/assets/3056958/17063288/7c2da20e-5004-11e6-9f10-01192e09cdb7.png)

You can sort by dragging each product back and forth.
