### ISSUE TITLE
Fetching products by handles

### ISSUE THREAD

**Issue by ar7casper** [Shopify/js-buy-sdk#177]
Hi, 
I've noticed that I can only fetch products by an Id. 
Here's an example of a path on my actual store -

>  /collections/new/products/product-287

But, 'product-287' is not a valid product Id and I can only get the actual productId from shopify's dashboard. It could have been great If I could fetch 'product-287' instead.

**Comment by yomexzo** [comment]
hey @ar7casper, your situation is not exactly clear.

however, if it is that you are trying to fetch a product using an identification other than the ID, you may want to consider maintaining a local mapping of this identification to the ID locally on your end.

You also have the option of fetching a product using it's `handle`. The handle is "a human-friendly unique string for the Product automatically generated from its title." e.g A product with title `6 Panel - Lumberjack` can be retrieved using `client.fetchQueryProducts({ handle: '6-panel-lumberjack' })`

**Comment by swalkinshaw** [comment]
Closing as http://shopify.github.io/js-buy-sdk/api/classes/ShopClient.html#method-fetchQueryProducts exists.
