### ISSUE TITLE
javascript fetchCart() function is not returning cart

### ISSUE THREAD

**Issue by akashrajguru** [Shopify/js-buy-sdk#178]
javascript
   client.fetchCart('shopify-buy.1459804699118.2').then(cart => {
    console.log(cart); // The retrieved cart
   });

what am i doing wrong ?

**Comment by yomexzo** [comment]
@akashrajguru, it appears what's missing there is the prefix `carts`. Try `carts.shopify-buy.1459804699118.2`.

you might also want to checkout the `client.fetchRecentCart()` api so you don't have to deal with the key.

**Comment by akashrajguru** [comment]
Hi yomexzo, I am still not getting cart after prefixing carts.shopify-buy.1459804699118.2 . I using js-buy-sdk in back end server where, I am grammatically creating a cart and adding product into cart trying to get cart details using client.featchCart.

 shopClient.fetchCart('carts.shopify-buy.1471349153978.1').then(function (cart) {
      console.log(cart); // The retrieved cart
   		}).catch(function(reason){
   		console.log(reason);
 });   

[Error: carts#cart.shopify-buy.1471349153978.1 not found]

**Comment by yomexzo** [comment]
okay @akashrajguru.

i assumed you were using this in your browser where data is stored in `localStorage`. You would have been able to get the information you need by inspecting `localStorage`.

my recommendation would be to save/manage your `cartId` once you have the `cart` object. You can get this from `cart.id` as seen below.

```
client.createCart().then(function (newCart) {
  console.log(newCart.id); //this would give you the id you need
});
```

**Comment by akashrajguru** [comment]
Hi Yomexzo, Thanks for recommendation. The only problem is if, I can't fetch the card, it will be difficult to modify the items in the cart.

**Comment by yomexzo** [comment]
Not sure i understood what you meant.

But you can save your `cart` object and use it as you wish. Just as we did in [this example](https://github.com/Shopify/js-buy-sdk/blob/master/examples/cart/index.js#L16)

**Comment by akashrajguru** [comment]
Okey Yes, sorry I miss understood, thanks again
