### ISSUE TITLE
[docs] Docs should not point to `latest` CDN link

### ISSUE THREAD

**Issue by richgilbank** [Shopify/js-buy-sdk#182]
Currently on the [home page](http://shopify.github.io/js-buy-sdk/) and the [downloads page](http://shopify.github.io/js-buy-sdk/downloads/), we link to the `latest` CDN version of the lib, so it's being used by default. As a result, people who copy/pasted from the docs will have broken sites if we release a breaking version. 
- [ ] Update CDN links in the docs to point to the last version released
- [ ] Decide on an approach for people using the `latest` path for when breaking changes are introduced.

**Comment by LoganD** [comment]
@richgilbank any update on this, I'm trying to find a cdn version of the lib that is versioned. Is there another location this information lives?

**Comment by richgilbank** [comment]
@LoganD The [Downloads](http://shopify.github.io/js-buy-sdk/downloads/) page has [a link to v0.1.7](http://sdks.shopifycdn.com/js-buy-sdk/v0.1.7/shopify-buy.polyfilled.globals.min.js), the URL structure for which should apply to all builds. However, there seems to be a problem with the latest builds not being pushed (since 0.1.7), which I believe @mikkoh and @yomexzo are currently looking into. 
cc @minasmart

**Comment by LoganD** [comment]
The url struct seems to have changed, I'm using `https://sdks.shopifycdn.com/js-buy-sdk/0.2.3/shopify-buy.polyfilled.globals.min.js`, the v was removed. I built on top of the latests version and v1.7 didn't work with my code. That solved the issue for me.

**Comment by minasmart** [comment]
Thanks for the find @LoganD! We have a couple docs PRs just rarin' to go out. They should be out soon.

**Comment by mikkoh** [comment]
Here are the two prs we'll need to get in:
https://github.com/Shopify/js-buy-sdk/pull/205
https://github.com/Shopify/js-buy-sdk/pull/230

**Comment by mikkoh** [comment]
@richgilbank @LoganD links have been updated in docs:
http://shopify.github.io/js-buy-sdk/downloads/
