### ISSUE TITLE
Document build system

### ISSUE THREAD

**Issue by mikkoh** [Shopify/js-buy-sdk#190]
We should add documentation on how the build system works in [`CONTRIBUTING.md`](https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md).

This would allow for new developers to get onboard faster. In the process it might be good to describe the folder structure of the repo.

The following items should be documented:
- [ ] the process of building js src/ -> dist/ and src/ lib/
- [x] how are tests run
- [ ] what modules run tests
- [x] a break down of major "entry" npm scripts and what they do (`start`, `test`, `prepublish`)

Please feel free to add to the list ^^^

**Comment by darol100** [comment]
Hey @mikkoh , Any update on this?

**Comment by rebeccajfriedman** [comment]
Closing this. Updated with some yarn commands. If there are specific questions, feel free to open a new ticket.
