### ISSUE TITLE
iOS 7-8 array return issues 

### ISSUE THREAD

**Issue by tdetweiler** [Shopify/js-buy-sdk#198]
I broke up my array map to try and figure out why IOS 8 and lower fail when loading products on our page. Finally found the issue to be product.options and the array returned which caused the catch function to trigger. Not able to get any more error messages then what I see. Documentation lists as supporting iOS 6.1+ but doesn't seem to be the case as it fails with getting the product options.

![screen shot 2016-08-17 at 3 55 10 pm](https://cloud.githubusercontent.com/assets/3488449/17756189/4eb3e4fc-6493-11e6-9d62-49094f8cc501.png)

![screen shot 2016-08-17 at 3 59 03 pm](https://cloud.githubusercontent.com/assets/3488449/17756317/f19f8c20-6493-11e6-9e9b-ba95e2aab3de.png)

**Comment by tessalt** [comment]
can you paste in the rest of your code? I'm unable to reproduce in iOS 8.1 simulator.

**Comment by tdetweiler** [comment]
Rest of my code should be irrelevant but I have attached it. Did you try to test on 8.0? I have specifically found the issue on 8.0 and 7.0, not sure if it is an issue on 8.1

(code before I split it up for debugging purposes):


shopClient.fetchProduct(6566423111)
        .then(function (product) {

            //build the select boxes for variants
            var selects = product.options.map(function (option) { //code breaks here on ios <=8.0
            return '<div class="variant-option"><div class="variant-option-title">' + option.name + '</div><select class="variant-select-wrapper" name="' + option.name + '">' + option.values.map(function(value) {
                return '<option value="' + value + '">' + value + '</option>';
            }) + '</div>';
            });
            
            //append the select boxes and buy button
            $('#select-zone-product').append(selects);
            $('#product-buy-layer').append('<div class="add-to-cart-wrapper"><a href="#" class="buy-now-button" id="buy-now">Add To Cart</a></div>');
            
            //select the color of the page we are on and hide it *NOTE THIS MUST BE CHANGED ON EVERY PRODUCT PAGE*
            $('#select-zone-product').find("select[name*='Color']").val('Brown');
            changeColorUpdate();
            $('#select-zone-product').find("select[name*='Color']").attr('disabled', true);
            $('#select-zone-product').find("select[name*='Color']").parent().hide();
            
            //actions when a select option is changed. Should update the product variant and image selected
            $('.variant-select-wrapper').change( function(event){
                var $element = $(this);
                var name = $element.attr('name');
                var value = $element.val();
                
                //color switches for adapter MAY NEED TO BE UPDATED FOR DIFFERENT PRODUCTS
                var optionColor;
                switch(value){
                    case "Stainless Steel":
                        optionColor = "chrome";
                        break;
                    case "Silver":
                        optionColor = "silver";
                        break;
                    case "Space Gray":
                        optionColor = "black";
                        break;
                    case "Rose Gold":
                        optionColor = "rose";
                        break;
                    case "Gold":
                        optionColor = "gold";
                        break;
                }
                
                //update selected picture
                if(name=="Adaptor Finish"){
                    $('#productThumbnails').find('div[name*="brown_l_' + optionColor + '"]').click();
                }
                
                // option Name and selected value obtained from DOM/user interaction
                product.options.filter(function(option) {
                    return option.name === name;
                })[0].selected = value;
            });
            
            function changeColorUpdate(){
                var name = 'Color';
                var value = $('#select-zone-product').find("select[name*='Color']").val();
                // option Name and selected value obtained from DOM/user interaction
                product.options.filter(function(option) {
                    return option.name === name;
                })[0].selected = value;
            }
            
            //add product to cart with options and selected quantity
            var clicked = false;
            $('#buy-now')
            .on('click touchstart', function (e) {
                var isScrolling; // scroll issue fix
                if(e.type=='click' && !clicked) {
                    e.preventDefault();
                    addItem(product); 
                }else if(e.type!='click' && !clicked) {
                    clicked = true;
                    $('#buy-now')
                    .on('touchstart', function(){
                        isScrolling = false;
                    })
                    .on('touchmove', function(e){
                        isScrolling = true;
                    })
                    .on('touchend', function(e){
                        if( !isScrolling )
                        {
                            e.preventDefault();
                            addItem(product); 
                        }
                    });
                }   
            });
    })         
    .catch(function () {
        console.log('Request failed');
    });

**Comment by tessalt** [comment]
Ah ok, the earliest version I can download for the simulator is 8.1. How are you testing iOS 8.0?

**Comment by tdetweiler** [comment]
We use device testing on browserstack.com

**Comment by tdetweiler** [comment]
Through analysis we found no customers using iOS <8.1. Issue is irrelevant now.
