### ISSUE TITLE
Return Order Number after Checkout

### ISSUE THREAD

**Issue by elwin-jacellc** [Shopify/js-buy-sdk#208]
Need to bind order number to unique product customization data. Is there a way to access order number after checkout currently?

**Comment by mikkoh** [comment]
@elwin-jacellc sorry it's not possible to do this at this time. We are actively thinking about the best way to implement this. Sorry I can't give you more.

I'm unsure if you have an Online Store associated with this project? Is there anyway you could associate the order via Cart Attributes?
https://help.shopify.com/themes/customization/cart/get-more-information-with-cart-attributes
