### ISSUE TITLE
fetchProduct bug with product variant images

### ISSUE THREAD

**Issue by guillelopez** [Shopify/js-buy-sdk#210]
Hi, 

When doing `fetchProduct` on **a just created product** I am getting empty variant images. All the other information is correct, but there is no variant images. 

For example:
-`product.selectedVariant.image` is `undefined`.
-`product.variants[0].image` is `undefined`.

But:
-`product.selectedVariant.price` shows correctly.

If you want to take a look on my specific store, it's electric-objects-2 and one of the products ids that is failing is 8383881670.

Thanks!

**Comment by minasmart** [comment]
Hey there! I just built a test with your shop and this product, and `product.selectedVariant.image` definitely returns an image with an `src` that points to a valid image. Could you tell me a little more about your environment? Browser, version, OS, etc? As well as a snippet of your code to get there with the `apiKey` redacted?

**Comment by guillelopez** [comment]
Hi @minasmart. My bad, now that I was copying you the code, I found an error on it that was modifing the `product` object. Thanks again for your help.

**Comment by minasmart** [comment]
NP 😄 !

I'm glad you got it figured out!!
