### ISSUE TITLE
how to get product/variant IDs?

### ISSUE THREAD

**Issue by rkoberg** [Shopify/js-buy-sdk#216]
I need to provide the product/variant ID to add a product variant to a cart. I imported products into shopify with the handle set to the ID of the product in my DB. I see how I can request a product with the js-buy-sdk using the handle and _then_ get the ID. But how do I get all of the IDs to re-associate back in my DB? I want to use a highly customized UI to filter/sort products (mostly a hierarchical "regions of the world" filter). Anyway, after importing into shopify, I tried to export from the shopify admin. I get the export emailed to me and there are no IDs. I have to be missing something on how to integrate a shopify shopping cart into a pre-existing site. This is an extremely frustrating experience. (I can't even tell if I am using the appropriate SDK/integration point with shopify)

**Comment by swalkinshaw** [comment]
Sorry for the delay, but this isn't really a JS Buy SDK concern. If you want to get IDs for mapping to your DB, I'd suggest using our REST API to get all the products: https://help.shopify.com/api/reference/product#index

Once that's done, you can use this library to integrate a Shopify cart.
