### ISSUE TITLE
undocumented(?) anonymous user REST api: documented somewhere?

### ISSUE THREAD

**Issue by rkoberg** [Shopify/js-buy-sdk#217]
You guys work closely with this, so I am hoping you might have _some_ information. Posted to the API forum: https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/undocumented-anonymous-user-rest-api-documented-somewhere-369824

I am building Shopify into an existing website (and probably using the http://shopify.github.io/js-buy-sdk ). This site is a Single Page App rendered once on the server and then handled on the client (browser) with fetches to the servers/APIs. I see that client code can make unauthenticated requests to Shopify endpoints for JSON. For example:
```
GET myshop.myshopify.com/products.json
GET myshop.myshopify.com/collections.json
GET myshop.myshopify.com/collections/france.json
GET myshop.myshopify.com/collections/france/products.json
```
Are these endpoints findable somehow and/or documented somewhere? Among other things, I want to get "tags" and then be able to filter products by those tags (think hierarchical regions of the world, for example: USA > California > North Coast > Napa County > Napa Valley). I tried (following the URL patterns from a regular template driven site):
```
GET myshop.myshopify.com/tags.json
GET myshop.myshopify.com/collections/all.json
GET myshop.myshopify.com/collections/all/bordeaux.json
GET myshop.myshopify.com/collections/bordeaux.json
```
but no luck. How can I get this information? 
In addition, is there some way to combine requests on this api? To get a "frontpage" collection I need first call the endpoint for the front page collection to get the title, description, image:
```
GET myshop.myshopify.com/collections/frontpage.json
```
And then another request to get the products associated:
```
GET myshop.myshopify.com/collections/frontpage/products.json
```
It would be great if it was possible to get this data in one request. Possible?
How about a way to sort? I tried:
```
GET myshop.myshopify.com/collections/france/products.json?sort_by=price-descending
```
but no luck

**Comment by mikkoh** [comment]
@rkoberg hey sorry these API endpoints are apart of a another Shopify API that has been deprecated. It is unwise to use these API endpoints.

The good news is that there will be a new public API coming some time early next year with more features.

**Comment by zk** [comment]
@mikkoh Any update on this? You all taking beta devs?

**Comment by minasmart** [comment]
Hey! We're working hard internally to get this API launched and public. As soon as it becomes available, there'll be a `v1.0.0-beta1` available for anyone to test out. Just keep an eye on this repo. Thanks for your interest 😄

**Comment by doprdele** [comment]
Any news on the new Shopify public api endpoints?

**Comment by mikkoh** [comment]
@doprdele keep your eyes peeled.
