### ISSUE TITLE
feature request: fetch/get raw json

### ISSUE THREAD

**Issue by rkoberg** [Shopify/js-buy-sdk#218]
Perhaps there is already some way to do this? Apparently, I am not supposed to use the publicly available endpoints that are present for a non-password-protected site. I just want the JSON arrays/objects as returned from the server. As it is now I need to deserialize the objects created by this library. The use case is that I am using a redux reducer to create/modify/delete ImmutableJS Records, Lists, Maps for use in purely rendered React components. There really is no point to the Model objects.

**Comment by coreytrampe** [comment]
Same here, basically. I'm using Elm, and keep thinking maybe I don't want to use this SDK, but the APIs backing it, instead. It'd be nice if they were documented, and deemed generally available.

**Comment by mikkoh** [comment]
Sorry @rkoberg could you explain your issue some more? Is the issue that you don't feel comfortable passing an access token when querying via the `js-buy-sdk` and that you'd like to be able to simply query your Store via the `js-buy-sdk` without an access token?

**Comment by minasmart** [comment]
The raw JSON is available under the attrs property of the model you request. However, I'd caution that the underlying API & JSON is not publicly documented and may change. That's why the model layer exists.

**Comment by swalkinshaw** [comment]
https://github.com/Shopify/js-buy-sdk/issues/293 will be the tracking issue for this since it has more details.
