### ISSUE TITLE
Make APP ID Optional

### ISSUE THREAD

**Issue by mikkoh** [Shopify/js-buy-sdk#219]
TL;DR make `appId` be optional when building a client. If no value is passed just default to 6.

I'm opening this issue just for discussion. I think the ability to pass in an App ID is neat but it's definitely an Advanced Use case. I'm unsure if we have data to get details but I imagine that 99% of the time the value of App ID is 6 when working with the `js-buy-sdk`.

Using 8 might feel like a Hack to developers and you'd definitely need to have advanced knowledge to use another App Id outside of 6 and 8.

@minasmart @richgilbank thoughts?

**Comment by minasmart** [comment]
Defaulting it to six works for the short term, however this functionality may be opening up and/or changing in the near future. For the moment I'd hold off, but keep this issue open as a placeholder until we have a more solid direction on timing.

**Comment by mikkoh** [comment]
Sounds great.
