### ISSUE TITLE
Total product count in collection for paging

### ISSUE THREAD

**Issue by snapcoyote** [Shopify/js-buy-sdk#221]
Can the total product count be added to the collection model or product array so paging can be implemented?  When I query the products in a collection with optional parameters for page / limit, I get back the limit number of products without knowing the max total available.  I don't know how many pages are available in the collection for me to display it in the front end.  Thoughts?

**Comment by minasmart** [comment]
Hey there! This is a limitation of our API. Pagination in our system is a non-trivial problem. We're working on adding better meta data around paginated sets, but it'll be some time before we're able to expose it through the SDK.

I'm sorry I don't have a better answer at the moment. We know it's a sought after feature, and it is being worked on. 

Thanks for your interest, and sorry I couldn't help more!

**Comment by snapcoyote** [comment]
Thanks for your response!  Looking forward to the feature once it is available.

**Comment by Januszpl** [comment]
@minasmart any updates on having product total count when requesting products by collection ?
https://graphql.org/learn/pagination/

Could you also give more details what kind of problem you have with it?
