### ISSUE TITLE
fetching collections return ONLY custom collections

### ISSUE THREAD

**Issue by ar7casper** [Shopify/js-buy-sdk#227]
Hi, 

Used all of the different ways to fetch collections, i.e.:
`shopClient.fetchAllCollections()
.then((cols) => {
console.log(cols);
})`
The result is an array of 3 custom collections.
expected: to get a list with the collections and hopefully the products underneath each collection.

Am I missing anything?
Thanks.

**Comment by minasmart** [comment]
Can you confirm that you've published all of the collections you want to see to the buy button (or whichever sales channel you're using) sales channel? 

Check the visibility channel to the right of your collection and make sure the box is checked:

![image](https://cloud.githubusercontent.com/assets/568174/18878036/2dfa947a-849d-11e6-999e-64e6c8047257.png)

**Comment by ar7casper** [comment]
Hmmm.... might be it 👍 
I'll double check later this week.
Thank you for the pointer!

**Comment by ar7casper** [comment]
@minasmart 
Thank you very much for your help!
Any chance it could be added to the docs? (btw, last time i've checked, the docs don't mention the fetchAllCollecitons method)
