### ISSUE TITLE
Changing cart item quantities on any page

### ISSUE THREAD

**Issue by vzkiss** [Shopify/js-buy-sdk#232]
I would like to modify the cart demo example so that customers can update the quantity of any product in the cart no matter which page they currently view on the website.

What I did so far is list a collection of products on a catalog page. Each product has a link to a separate page which lists a single product and the option to add it to the cart.
However with the demo script you can only change the quantity of the items in the cart if you are on the same page as the product you want to change the quantity of.

To be able to increase or decrease the quantity of products in the cart I changed the updateQuantity() function in the following way.
1. First I find the product (var pr) in a collection with the same variantId.
2. Use single product (pr) to update quantity. 

Problems:
iIt only works with products that has one varaint. I need this to work with multiple variants for the same product.
It increase or decrease the quantity of a product in the cart by 3 each time the minus or plus buttons are used. (There are 3 products in the collection).

I am new to JavaScript.

Here is the code

```
function updateQuantity(fn, variantId) {
    var pr;
    for (var key in collection){
      if (collection.hasOwnProperty(key)) {
         if (variantId === collection[key].variants[0].id){
          pr = collection[key];
         }  
      }
    }

    var variant = pr.variants.filter(function (variant) {

    /* no changes below this point in the function */
      return (variant.id === variantId);
    })[0]; 
    var quantity;
    var cartLineItem = findCartItemByVariantId(variant.id);
    if (cartLineItem) {
      quantity = fn(cartLineItem.quantity);
      updateVariantInCart(cartLineItem, quantity);
    }
```

**Comment by cskiva** [comment]
Hi vzkiss,

I had the same issue a few months ago and I solved it with a friend.

I did not solve it myself, so I will do my best to explain it to you.

Basically, the code is using the variantId to check the variantId and it causes issues when you go between pages where you have called a new product up.

Here is what we changed:
At Line 186 of 
js-buy-sdk/examples/cart/index.js

`/* Update product variant quantity in cart
  ============================================================ */
  function updateQuantity(fn, variantId) {
    var variant = product.variants.filter(function (variant) {
      return (variant.id === variantId);
    })[0];
    var quantity;
    var cartLineItem = findCartItemByVariantId(variant.id);
    if (cartLineItem) {
      quantity = fn(cartLineItem.quantity);
      updateVariantInCart(cartLineItem, quantity);
    }
  }`

we took out:

` var variant = product.variants.filter(function (variant) {
      return (variant.id === variantId);
    })[0];`

Leaving us with (the working code)

`/* Update product variant quantity in cart
  ============================================================ */
  function updateQuantity(fn, variantId) {
    var quantity;
    var cartLineItem = findCartItemByVariantId(variantId);
    if (cartLineItem) {
      quantity = fn(cartLineItem.quantity);
      updateVariantInCart(cartLineItem, quantity);
    }
  }`

Hope that helps. As you say you are using the cart example, I assume you mean this full version, I don't have experience with the simple cart example.
