### ISSUE TITLE
Documentation for JS Buy SDK and Google Analytics integration?

### ISSUE THREAD

**Issue by nocean** [Shopify/js-buy-sdk#250]
Is there any documentation on best practices for integrating Google Analytics with the JS Buy SDK? A list of GA events that Shopify uses that could be mirrored in an JS Buy SDK implementation?

**Comment by alfsaav** [comment]
@nocean Hi there, just wanted to check with you. Are you able to track medium/source parameters for ad campaigns (adwords/facebook)? We lose those paremeters at the of the checkout flow (chekcout.shopify.com), any help on this would be greatly appreciated.

**Comment by nocean** [comment]
We're not using them, but off the top of my head, I would guess that Shopify's GA integration (for checkout.shopify.com) would track them, and so you'd just have to build the checkout URL for the SDK's cart's "checkout" button to include them dynamically.

**Comment by alfsaav** [comment]
Actually they don't get carried automatically, I got a response from a different thread here. @minasmart provides a great response on how to deal with this, I will test it and report back. here is the link to the other article #281 https://github.com/Shopify/js-buy-sdk/issues/281#issuecomment-268017441 

Thanks for following up. I will update the other thread with my results.

**Comment by Andriy-Kulak** [comment]
@alfsaav Did it work? I am just beginning to build my application and will need to implement this exact feature in the next couple of weeks as well.

**Comment by alfsaav** [comment]
@Andriy-Kulak Yes it worked, just follow the instructions in the other linked threads.
