### ISSUE TITLE
Problem with api in IE Edge, Windows 8.1

### ISSUE THREAD

**Issue by lucasmoeskops** [Shopify/js-buy-sdk#258]
I'm trying to setup a buy button to a store. Everything goes fine except when I test it in IE (Edge, on window 8.1). I would like to fetch a product using `shopClient.fetchProduct` and then access its selectedVariant. However, on starting the request, immediately two info messages show up:

> SEC7118: XMLHttpRequest for https://my-store.myshopify.com/api/apps/6/product_listings/123456789 required Cross Origin Resource Sharing (CORS).
> SEC7119: XMLHttpRequest for https://my-store.myshopify.com/api/apps/6/product_listings/123456789 required CORS preflight.

The resulting object does have the basic property values, however, some give a `<Permission denied>` error, when I inspect the object in the console. An example of these is `product.selectedVariant`. When I try to access these properties, for instance `product.selectedVariant` I get an error:

>SCRIPT5022: Invalid option selection for Size.
File: shopify-buy.polyfilled.globals.min.js, Line: 30, Column: 3450

Does anyone have an idea what is going on here? Thanks in advance!

**Comment by mikkoh** [comment]
@lucasmoeskops thanks for the issue. We're looking into this.

**Comment by mikkoh** [comment]
@lucasmoeskops can you paste the url from where you're loading `shopify-buy.polyfilled.globals.min.js`?

**Comment by mikkoh** [comment]
@lucasmoeskops Where is `shopify-buy.polyfilled.globals.min.js` being loaded/consumed from? Is it from a local build or from: 
http://sdks.shopifycdn.com/js-buy-sdk/latest/shopify-buy.polyfilled.globals.min.js

We've recently made updates to the JS Buy SDK and how it's served via the CDN. If you are loading via CDN Could you try this version of the JS Buy SDK:
http://sdks.shopifycdn.com/js-buy-sdk/v0/latest/shopify-buy.umd.polyfilled.min.js

**Comment by lucasmoeskops** [comment]
@mikkoh 

Thanks for the quick response! I used the one from the shopifycdn (your first link). 

I just tested with your different version and that worked! I still get the IE security messages, but the variables are now accessible and work correctly. 

So, I will now use the v0 version instead. Will it remain available, or is it only a temporal url?

**Comment by minasmart** [comment]
We started to vendor our latest release by major version. That link is the new format and will stick around. It should also be reflected in our documentation as of a couple days ago, and in the future. 

Thanks for using the SDK :smile:!
