### ISSUE TITLE
x-sdk-version header undefined

### ISSUE THREAD

**Issue by tessalt** [Shopify/js-buy-sdk#260]
![image](https://cloud.githubusercontent.com/assets/1789029/19899320/0ecfea46-a036-11e6-9a48-5e6d79860ed5.png)

not sure when this happened. ShopifyBuy.version is also undefined. 

@minasmart @mikkoh

**Comment by minasmart** [comment]
@tessalt are you building using our babelrc, or your own?

You may need to do what we've done [here](https://github.com/Shopify/js-buy-sdk/blob/master/.babelrc#L25) and [here](https://github.com/Shopify/js-buy-sdk/blob/8f3156f9506eb56aa989e202995ebfebb6f4b2ff/docs/_data/package.json#L34) using env vars if you're building yourself. If you use the version that we bundle, or compile into `lib`, version should already be injected.

**Comment by minasmart** [comment]
If you're using our ES6 code, I'm not entirely sure of the best way to inject this data. @mikkoh thoughts?

**Comment by mikkoh** [comment]
Sorry I had missed this conversation. There's really no nice way to inject the code if using the es6 code in this module.

I wonder if instead of injecting `process.env.VERSION` we generate es6 source of `version.js` when `start`, `test,` or `prepublish` is called.

**Comment by minasmart** [comment]
Turns out the value is also missing in the UMD build. The fix we came to was to just hard code the value, and have a test that ensures `package.json` and `version.js` are in sync.
