### ISSUE TITLE
whatwg-fetch in dev and main deps

### ISSUE THREAD

**Issue by minasmart** [Shopify/js-buy-sdk#263]
Looks like fe7c7286b0b53dd3efb066b0230ea7f6aaef30a3 duplicated `whatwg-fetch` between dev and main dependencies.

Tagging @yomexzo to take a look and see if it can just live in main deps.

**Comment by swalkinshaw** [comment]
Closed by https://github.com/Shopify/js-buy-sdk/pull/265/commits/805f068dcbabdb3ef9ccc520bb6452f91701271c
