### ISSUE TITLE
Provide rolled-up commonjs module for browserify / webpack / node

### ISSUE THREAD

**Issue by minasmart** [Shopify/js-buy-sdk#264]
Based on [this issue](https://github.com/Shopify/buy-button-js/pull/284) on `buy-button-js` it looks like our UMD wrapper will get weird depending what gets defined on `window` and then have some weird behaviour that a `browserify` generated bundle doesn't expect (just calling define instead of exporting, or whatever). We should provide a commonjs build with no wrapper cruft for easy consumption with common bundling tools. It should probably be the `main` as specified by our `package.json`.

@tessalt thoughts?

**Comment by tessalt** [comment]
sounds good... not also that the issue is not browserify specific. Rollup build has the same behaviour.

**Comment by minasmart** [comment]
Yeah, UMD looks great in a standalone static asset sort of environment, but kinda poopy for any build system that resolves modules and dependencies.
