### ISSUE TITLE
Write tests or refactor tests to run on distributed code

### ISSUE THREAD

**Issue by mikkoh** [Shopify/js-buy-sdk#267]
An issue we have right now is that our tests are run on a different build than our distributed code. This makes distributing/publishing a bit hairy.

It would be a large refactor to refactor our tests to run on the distributed bundles so I wonder if it'd be best to write new tests instead.

**Comment by minasmart** [comment]
wdio/example tests were running on our distributed code. That may need to be updated, but end-to-end integration tests do exist. :smile:

**Comment by mikkoh** [comment]
This is true. I'll need to check what it tests against but having checks on version would be good.

Also we'd need to ensure that the regular cjs, cjs polyfilled, es, es polyfilled, and umd builds are all tested against. Off the top of my head I cannot remember which build `test-examples` runs.

**Comment by minasmart** [comment]
It validates the UMD build: https://github.com/Shopify/js-buy-sdk/blob/master/examples/cart/index.html#L9

We should probably add a webpack and browserify example that test against CJS. We should also probably add some assertions for build metadata, like exposing `version` off the top-level export, and just test that the JS reflects that.
