### ISSUE TITLE
Issues Local Storage not being retrieved ( checking for it on globalVars is always false ) 

### ISSUE THREAD

**Issue by moxiemonkshood** [Shopify/js-buy-sdk#271]
**In checking for localStorageAvailable , it seems that we are checking for something that hasn't ever been set.** 

```
    var Store = CoreObject.extend({
        constructor: function constructor() {
            this.localStorageAvailable = this.storageAvailable('localStorage');
            this.cache = {};
        },
       ...
```

```
    globalVars.set('btoa', base64.btoa);
    globalVars.set('atob', base64.atob); // drop in polyfills from Promise
    globalVars.set('Promise', promise); /* eslint no-undefined: 0 */
    globalVars.set( 'localStorage' , localStorage);
```

**To get local storage to work, I set localStorage on the globalVars object then it was able to succesfully check for it.** 

**Found the source in polyfills.js**

Thanks!

**Comment by minasmart** [comment]
Is this in the context of a node app? Or the web?

**Comment by moxiemonkshood** [comment]
This is on the web. 

 
 
 


SEAN BRADLEY   [ Senior Technical Lead ]
—
EMAIL:  sean.bradley@moxiesozo.com <mailto:sean.bradley@moxiesozo.com>
—

MOXIE SOZO
—
ADDRESS: 1140 Pearl Street | 2nd Floor | Boulder | CO | 80302
MAIN:  720.304.7210
WEB:  www.moxiesozo.com <http://www.moxiesozo.com/>
—

**Comment by mikkoh** [comment]
@moxiemonkshood do you know what browser + version `localStorage` did not exist on?

**Comment by moxiemonkshood** [comment]
Mac Google Chrome
Version 54.0.2840.98 (64-bit)
Windows IE 11.103.10586.0
It isn’t that the localStorage didn’t exist. I was actually using it in my script. It was that the sdk wasn’t creating a cart in localStorage. I looked into it, and it was checking for localStorage on globalVars and always returning false. After adding globalVars.set( ‘localStorage’ , localStorage ) , it started saving the cart successfully again. 
Thanks 


\


SEAN BRADLEY   [ Senior Technical Lead ]
—
EMAIL:  sean.bradley@moxiesozo.com <mailto:sean.bradley@moxiesozo.com>
—

MOXIE SOZO
—
ADDRESS: 1140 Pearl Street | 2nd Floor | Boulder | CO | 80302
MAIN:  720.304.7210
WEB:  www.moxiesozo.com <http://www.moxiesozo.com/>
—

**Comment by mikkoh** [comment]
@moxiemonkshood how are you consuming `js-buy-sdk` is it from `npm` or from this url http://sdks.shopifycdn.com/js-buy-sdk/v0/latest/shopify-buy.umd.polyfilled.min.js ?

Thanks for being so helpful I'm looking into this issue.

**Comment by moxiemonkshood** [comment]
Glad to contribute 

That is what I originally linked to.Though now the line where localStorage is being checked is a bit different than on the version that I have, and I don’t see the globalVars object in there. 

I saved the source to debug last night and ended up with the script below. 

 
   


Thanks. 







SEAN BRADLEY   [ Senior Technical Lead ]
—
EMAIL:  sean.bradley@moxiesozo.com <mailto:sean.bradley@moxiesozo.com>
—

MOXIE SOZO
—
ADDRESS: 1140 Pearl Street | 2nd Floor | Boulder | CO | 80302
MAIN:  720.304.7210
WEB:  www.moxiesozo.com <http://www.moxiesozo.com/>
—
