### ISSUE TITLE
Analytics / Ad campaigns

### ISSUE THREAD

**Issue by alfsaav** [Shopify/js-buy-sdk#281]
First of all, great job on the SDK, it's very useful. We have some issues with Analytics. We want to be able to track attribution (medium/source) at the end of our checkout flow. I believe this is due to the fact that this parameters don't get pass once you transition into Shopify checkout (checkout.shopify.com). 

This is important, because we have paid ad campaigns through Facebook and Google Ads, and would like to be able to track the medium and source parameters in GA. We have a workaround for this, but it means having to open a different tab for checkout and have the order-status page send a post to the tab that originated the flow. Any help on this will be very much appreciated, thank you.

**Comment by minasmart** [comment]
Hey there!

At one point we managed this through the SDK, but found that implementations of google analytics varied between shops enough that there was no way we could do it effectively.

The right solution for you will be three parts:

1. Make sure you've added your google analytics token to your shopify account
2. The google analytics feature you're looking for is cross-domain tracking, which is most commonly implemented using [google's linker plugin](https://developers.google.com/analytics/devguides/collection/analyticsjs/linker). Make sure your google analytics account is set up properly to use this plugin.
3. Once you have the linker param out of google analytics, on the page that you're using the js buy SDK, add it to the checkout URL you send your customer to. Google analytics on the shopify checkout side should pick this up (provided your google analytics account is properly set up), and you should be able to see campaign tracking all the way through!

__NOTE:__ Google makes a lot of mention of their linker plugin's auto decoration feature. This works just fine provided you're sticking your checkout link on an anchor tag and not dynamically updating it through JS. The snippet shown here:

```javascript
ga(function(tracker) {
  var linkerParam = tracker.get('linkerParam');
});
```

is the most common case to pull the linker param out and and stick it to your checkout URL. 

__NOTE 2__: linker params expire. They're only good for a couple minutes, so it's best to capture the checkout link click, add the param, and immediately send the customer over to the checkout.

Hope this helps!!

**Comment by alfsaav** [comment]
@minasmart Thank you very much, I will try it out!
