### ISSUE TITLE
Add currency attribute

### ISSUE THREAD

**Issue by defrank** [Shopify/js-buy-sdk#282]
Currently the only way to guess the currency is with #231's formatted price attribute.  However, this only gets us the symbol, not the currency.

Ideally there should be attributes for the `currency` and `currencySymbol`.

**Comment by andydust** [comment]
+1

**Comment by minasmart** [comment]
This  attribute is available in the [v1.0 alpha](https://github.com/Shopify/js-buy-sdk/blob/v1.0alpha/README.md), and will soon be released in the `v1` major release.
