### ISSUE TITLE
add/modify headers of ajax requests

### ISSUE THREAD

**Issue by tessalt** [Shopify/js-buy-sdk#286]
Currently, there's no way for consumers to add or modify headers sent to product listings. Could we add some sort of ajax config object or something? Thoughts? @minasmart @mikkoh @richgilbank

**Comment by mikkoh** [comment]
What headers would be modified?

**Comment by richgilbank** [comment]
My bad for not following up on this earlier. Currently we can't distinguish between Buy Button and JS Buy requests, so we can't measure the performance of either. We should be able to override the headers to identify buybutton.js requests. Although it unfortunately wasn't documented previously, this is a pretty high priority for us.

**Comment by tessalt** [comment]
specifically the `X-SDK-VARIANT` and version. We want to be able to differentiate between requests from js buy sdk directly and those through buy butt

**Comment by minasmart** [comment]
If it's urgent, feel free to make a PR and add options to the client initialization, otherwise, this will be a part of v1

**Comment by swalkinshaw** [comment]
Closed by https://github.com/Shopify/js-buy-sdk/pull/287
