### ISSUE TITLE
Get Raw Product Values

### ISSUE THREAD

**Issue by rizedr** [Shopify/js-buy-sdk#293]
Hello,

I am looking to build an e-commerce web app using ES6, react, react-redux and yours js-buy-sdk api. My problem is that after fetching all products from shopify and placing them in the store, I seem to no have all data about a product as I would expect, rather only:  `{ attrs, shopClient, serializer, type, config, _memoized }`.

Here is how I am making the call to get products, under a file I named `shopify.js`:
```
import ShopifyBuy from 'shopify-buy';

const shopClient = ShopifyBuy.buildClient({
  apiKey: 'xxxxxxxxxxxxxxxxxxxx1403c107adc7e',
  domain: 'xxxxxxxxxxxxxxxx.myshopify.com',
  appId: '6',
});

export function fetchAllProducts() {
  return new Promise((resolve, reject) => {
    shopClient.fetchAllProducts()
      .then((data) => {
        console.log('shopClient.fetchAllProducts', data);
        resolve(data);
      }).catch((error) => {
        console.error(new Error('Fetching products error!'));
        reject(error);
      });
  });
}
```

Looking at the console.log `shopClient.fetchAllProducts` this is what I get:
<img width="434" alt="screen shot 2017-01-21 at 2 33 06 pm" src="https://cloud.githubusercontent.com/assets/3323353/22174428/e71f7b60-dfe6-11e6-85b0-49e79e6b0ff7.png">

I take `data` and place it in the redux store and when I am looking at it, it looks like this:
<img width="433" alt="screen shot 2017-01-21 at 2 49 07 pm" src="https://cloud.githubusercontent.com/assets/3323353/22174499/dec0ee98-dfe8-11e6-8d67-edc072a865f8.png">

If it is relevant, check [this gist](https://gist.github.com/rizedr/bcfeaefb2a6082355b9b75a3b5e5fac1) to see the actions I am dispatching and [this gist](https://gist.github.com/rizedr/b698649a9bef5842ff420a38553f4fda) where my actions get reduced and placed in the store.

From my understanding, when you do `fetchAllProducts()` method, you get an array of `ProductModel`s, therefore, I suppose in my store gets set the following `{ attrs, shopClient, serializer, type, config, _memoized }` because that is what `ProductModel` stores internally.

**My question is**, is there a way to get a raw object of data from `ProductModel` (with all the relevant product values as presented in the first screenshot and with the data from the Models, such as `ProductOptionModel`, that `ProductModel` relies on) so I can place that my store for stability and sanity reasons?

**Comment by swalkinshaw** [comment]
Thanks for the detailed issue.

This was previously answered at https://github.com/Shopify/js-buy-sdk/issues/218#issuecomment-253681923.

This will likely be possible in an upcoming version.
