### ISSUE TITLE
Getting started guide needs improvement

### ISSUE THREAD

**Issue by abdulhannanali** [Shopify/js-buy-sdk#299]
I noticed a few things, which needs attention while going through the [JS Buy SDK Getting Started Guide](https://shopify.github.io/js-buy-sdk/). The Getting started guide doesn't represent what's there in Reference  and the latest version of the library's code. 

In **Making a Request** section, there's this para

> All fetch methods return a promise which will return a Cart or Collection model for fetchProduct or fetchCollection, or an array of Cart or Collection models for fetchAllProducts or fetchAllCollection.

The Reference doesn't discuss about any `CollectionModel` explicitly, if there was one that should be documented, however on a glance over the code and as reference says it returns an instance of `BaseModel`. Also, the `fetchProduct` or  `fetchAllProducts` doesn't seem to return Cart model. They instead seem to return the ProductModel, library has available in it's code. 

I would like to have any feedback on this explanation and if it holds true.

Another major thing that needs to be changed ASAP is description of the **Adding Items to Cart** which is given below

>  Adding items to a cart
Cart items can be retrieved as an array with the cart.lineItems getter. To add items to a cart, you can call the cart’s addVariants method and pass in the product(s) to be added. The update call will return a promise which returns the updated model.
``` js
cart.addVariants({variant: product.selectedVariant, quantity: 1}).then(function (cart) {
  // do something with updated cart
});
```

This is very inconsistent, as the Reference doesn't even talk about this method, also, `addVariants` is now deprecated, so this should be replaced with `createLineItemsFromVariants`. I moved to  createLineItemsFromVariants after getting warning in the console about this method.

**Comment by abdulhannanali** [comment]
I am happy to make a PR to `gh-pages` branch after the approval, and some feedback on this. So, I can work on the content accordingly.

**Comment by abdulhannanali** [comment]
Also, I made this little store with Shopify's JavaScript SDK, http://hannanali.tech/shopify-js-store/

**Comment by swalkinshaw** [comment]
@abdulhannanali feel free to open a PR for the docs. But it's no longer on the `gh-pages` branch, just `master`.

You can use `npm run doc:build` and `npm run doc:serve` to run them.

Warning that the docs are likely changing soon though with a lot of changes coming in the next major version.

**Comment by teodors** [comment]
I can relate to this. This got really frustrating for me when I was trying to add variants to cart, but it just kept giving back null/undefined cart line items. It turns out ID is not enough although guide says something else.

> Adding items to a cart
> Items are added to the cart by calling the cart’s createLineItemsFromVariants method, which accepts one or more **objects containing a variant ID and quantity**. createLineItemsFromVariants will update the cart and synchronizing it with Shopify. If you add a variant ID that already exists in the cart, that line item’s quantity will be incremented.

Here in reference, it states that `createLineItemsFromVariants` takes variant objects.
http://shopify.github.io/js-buy-sdk/api/classes/CartModel.html#method-createLineItemsFromVariants

Why do you need the whole variant object in the first place? Why isn't ID enough?

**Comment by AlcuinGuest** [comment]
@teodors Hey, I'm having a similar problem currently. Not sure how to add a specific variant to the cart (the 'selectedVariant' property of the product object is always the first variant). Did you ever come up with a solution to this problem?

Would love some help, it's driving me crazy!

**Comment by rebeccajfriedman** [comment]
Closing as stale.
