### ISSUE TITLE
Server-side usage (without localStorage)

### ISSUE THREAD

**Issue by sashafklein** [Shopify/js-buy-sdk#301]
I'm trying to use this library in a React/Redux application. As a consequence, any client-side code is insecure, so I proxy my requests through a series of express endpoints which have access to secure/hidden environment variables (ie SHOPIFY_API_KEY, SHOPIFY_APP_ID, and SHOPIFY_DOMAIN), and can reach out to the Shopify API using those credentials and return the response to the client without exposing the secure creds of my Shopify store.

Unfortunately, that seems not to be working. 

After successfully creating a cart (server-side), returning the cart ID to my client code, and then initializing a request to fetch that cart and add (an) item(s) to it, I get an empty error when running `client.fetchCart(someCartID)`

Here's the code for the internal express endpoint I made for fetching a cart and adding an item to it:

```
return (req, res, next) => {
  try {
    client.fetchCart(req.body.cartID).then(cart => {
      const { variant, quantity } = req.body;
      cart.createLineItemsFromVariants({ variant, quantity }).then(
        response => { res.status(200).send(response); },
        error => { next({ err: error, spot: 'ADD ITEM' }); }
      );
    }, error => { next({
      err: error, // This is the error which is called, and the error object is empty
      spot: 'FETCH CART'
    }); });
  } catch (error) { next(error); }
};
```

`req.body.id` is in the format `shopify-buy.123456789.1`. I've also tried prepending `carts.` to the beginning of that, per #178. But no dice. 

Here's the endpoint I hit first, which creates a cart and returns its ID for later fetching:

```
return (req, res, next) => {
  try {
    client.createCart().then(
      cart => { res.status(200).send({ id: cart.attrs['shopify-buy-uuid'] }); },
      error => { next(error); }
    );
  } catch (error) { next(error); }
};
```

It seems that this SDK only functions client-side, because of its dependency on `localStorage`. 

Am I doing something wrong? Do you have a suggestion about how to use this library server-side? How else can/should I keep my credentials secure?

Thanks!

**Comment by jamiemtdwyer** [comment]
Hey Sasha,

None of the credentials used for the JS Buy SDK are sensitive - these credentials are specifically meant for "untrusted" applications as the JS Buy SDK doesn't expose any sensitive shop actions, only the ability to view products, create checkouts, etc.

Perhaps someone else might be able to comment on the feasibility of a server-side integration as I haven't attempted this before.

**Comment by minasmart** [comment]
Server side the SDK is a fetching tool. Our cart implementation can't determine your persistence layer, so more work is required to do things that way. It's highly recommended that if you're trying to store user sessions that you build out your own solution because it's pretty specific for every case. If I could think of a general way to do this server side, I would build it into the SDK. In the next major version of this tool, carts will be server persisted, and everything will work exactly the same, client or server side.

**Comment by isaachinman** [comment]
@minasmart Was there any update on this? As far as I can tell, if I create a checkout server-side, add some line items to it, and then open the `webUrl` in a fresh browser session (eg redirecting the user from my application to Shopify), I see a "Your cart is empty" page.

I assume the cart data is being stored in localStorage, and a url like:

    https://myapp.myshopify.com/3004999964/checkouts/cc1a4fde8788ddc296f08522b928cf00?key=0fd50cb4913a4ceda9e4d023d4ca5bd2

...is not actually session-independent. Is that correct?

**Comment by minasmart** [comment]
I'm really unsure of what you're asking. the webUrl field from the checkout should direct them to the in progress checkout.
