### ISSUE TITLE
Customizing / adding data to checkout URL

### ISSUE THREAD

**Issue by sashafklein** [Shopify/js-buy-sdk#302]
Apologies if someone else has asked this, but I couldn't find it.

Is there any way to attach information to the `checkoutURL` (ie, user email, name, etc), so that **a)** the fields are pre-filled, and **b)** any post-checkout webhooks I create for my app are given that information? It looks the like checkout URL is a static property of the cart.

**Comment by minasmart** [comment]
The checkout URL is static. It doesn't have any more extensibility over what's been done in this SDK. We will be releasing a different version soon that has server-persisted carts, so this will be possible in the near future.

Regarding checkout webhooks, you can subscribe to `create`, `delete`, and `update`. Each of these will yield the entirety of the checkout object (including customer email, name, etc). This is [documented in our webhook reference here](https://help.shopify.com/api/reference/webhook)

**Comment by doublerebel** [comment]
@sashafklein The checkout URL actually is somewhat customizable, it's possible to fill many of the fields on the page. For example, fill user email with `&checkout[email]=url-encoded-users-email-here`.  There's a mention of that in https://github.com/Shopify/js-buy-sdk/issues/105#issuecomment-217081126 .

It's also possible in `v1.0alpha` to add custom attributes to a checkout during checkout creation, [as documented here](https://github.com/Shopify/js-buy-sdk/blob/v1.0alpha/docs/API_REFERENCE.md#clientcreatecheckoutinput-query--promise--graphmodel).

**Comment by harry1064** [comment]
@minasmart The id we get for checkout in js buy sdk is base64 encoded value but on checkout webhooks we get `token`. This way i am not able to know for which checkout this webhook is as i am only having the checkout Id i got i from js buy sdk.
