### ISSUE TITLE
Can I pass custom product data via shopify buy button?

### ISSUE THREAD

**Issue by Andriy-Kulak** [Shopify/js-buy-sdk#306]
Can I pass custom product data via shopify buy button? I am unable to find documentation on this.

In my app, the customers will upload their images and customize the product so each product will be unique. I need to make sure I can pass this data to checkout so that I know what specifications were selected once they make the purchase.

Thanks!
Andriy

**Comment by ajhool** [comment]
http://shopify.github.io/js-buy-sdk/api/classes/ProductOptionModel.html

I have not implemented this yet, but I believe the correct way to do this is to set a key/value option setting. In your case, you will probably need to store/host the uploaded image online, and then pass the URL in the value. I find it unlikely that you could pass the data in key/value string, but.. maybe?

**Comment by sethbibler** [comment]
I don't think ProductOptionModel work. We don't need a way to select a product variant, that's available now so long as you have the variant ID.

What we need is an ability to store custom strings per line item and per order.

**Comment by Andriy-Kulak** [comment]
Yes @sethbibler it doesn't appear you can attach custom attributes to each item at the moment via the buy button. They are working on this apparently... What you can do is add custom attributes to the entire order. In this custom attribute you will have to define which product you are referencing because otherwise, if the person has more than 1 item in their order, you won't know which custom attribute is relevant to which product. This is the best workaround I came up with for now.

This is discussed here #105

**Comment by macgibbo83** [comment]
Hi there totally new to GitHub and to the js-buy-sdk. I've recently been handed an existing project using shopify buy buttons. Client wants to be able to sell products with handwritten gift notes from customers written by customers. Is there any way to pass this as a custom attribute in buybutton.js

**Comment by rebeccajfriedman** [comment]
When you are [adding line items to the checkout](https://github.com/Shopify/js-buy-sdk/blob/master/src/checkout-resource.js#L126-L145), you can add custom attributes to them. See https://help.shopify.com/en/api/storefront-api/reference/mutation/input-object/checkoutlineiteminput for the specifics of line item input.

@macgibbo83 For questions about BuyButton.js, please post in that repo.
