### ISSUE TITLE
Switching Carts but preserving products

### ISSUE THREAD

**Issue by Brendan-Smith** [Shopify/js-buy-sdk#308]
Hi,

I have a scenario were I want to allow a user to switch currencies for my site. I understand that currently Shopify doesn't support multiple currency, to work around this I'm looking to use multiple Shopify stores and allow on my site the user to choose which cart they are using so it checkouts at the correct store. The one thing I'm not able to find a answer for is, we will be creating a new cart when the currency is changed but what I would like to do is preserve the products already in the cart. Have others done something similar to this and do you have any suggestions on how I can accomplish this using the SDK?

**Comment by minasmart** [comment]
Variants in the cart are all keyed by ID, so if you have multiple clients set up, pointed at multiple shops, even though the variants may have the same names, they will have different IDs, and they'll look like different variants. Similarly, a cart points to a check out URL, so carts are naturally separated by shop domain. It may not be ideal, but I'd recommend using a single shop, with a set currency, and a library like [money.js](http://openexchangerates.github.io/money.js/) that can convert the currency on the fly for you.
