### ISSUE TITLE
client.fetchCart

### ISSUE THREAD

**Issue by TUncleSan** [Shopify/js-buy-sdk#312]
In localhost:8080 show normal,but Upload to server，It will show " Error: carts#shopify-buy.1488428339424.1 not found ".I'm sure my cookie(cart.id) is right.
 code:
function getCookie(cname) {
        var name = cname + "=";
        var ca = document.cookie.split(';');
        for (var i = 0; i < ca.length; i++) {
            var c = ca[i].trim();
            if (c.indexOf(name) == 0) return c.substring(name.length, c.length);
        }
        return "";
    }
    function checkCookie() {
        var user = getCookie("cartid");
        if (user != "") {
            client.fetchCart(user).then(function (oldCart) {
                cart = oldCart;// The retrieved cart
           }

**Comment by minasmart** [comment]
Carts aren't stored in cookies. They're in local storage. However, you should always use the fetchCart methods and not access it directly. There are some mechanics that happen behind the scenes.
