### ISSUE TITLE
CartLineItemModel missing product title

### ISSUE THREAD

**Issue by zombor** [Shopify/js-buy-sdk#313]
Looking to write a js app on top of shopify data for a store. The cart line item model documentation page has data documented which isn't available: http://shopify.github.io/js-buy-sdk/api/classes/CartLineItemModel.html

For example, it says there's `title` which seems to be missing:

![shopify](https://cloud.githubusercontent.com/assets/170538/23689244/082e2886-037f-11e7-96a0-509eebadd1d8.png)

It appears there's no actual way to get the product title for an item in a cart. Is there another way to get this data?

**Comment by minasmart** [comment]
cart line items are accessed through the getter `lineItems` on the cart object. `attrs` is internal implementation details.

The right way to get to the title attribute is `cart.lineItems[0].title`. If you're accessing it through `attrs`, you're getting the raw data from out APIs before it's been wrapped in a model.

**Comment by pmdownie** [comment]
I'm having a similar problem where the cart.lineItems[0].title value is undefined.

I'm passing the whole variant object through, but is there something else I should be passing the addLineItemToCart function?
