### ISSUE TITLE
Error in IE 11 when accessing product.selectedVariant;

### ISSUE THREAD

**Issue by mcrider** [Shopify/js-buy-sdk#315]
In IE11, I'm getting an error when trying to fetch a product.  Stepping through, it crashes when i try to assign shopifyProduct.selectedVariant to defaultVariant.  The catch statement throws the error 'Invalid option selection for Quantity'.  Any ideas whats going on? Originally referenced from issue #126 .

```
shopClient = ShopifyBuy.buildClient({
      apiKey: 'xxxxxxxx',
      myShopifyDomain: 'xxxxxxxx',
      appId: '6'
    });

    var productId = xxxxxx;
    shopClient.fetchProduct(productId)
      .then(function(shopifyProduct) {
        shopifyProducts = shopifyVariants = {};
        shopifyProducts[productId] = shopifyProduct;
        var defaultVariant = shopifyProduct.selectedVariant;
        shopifyVariants[defaultVariant.id] = defaultVariant;
        setVariants(productId, shopifyProduct.attrs.variants);
      })
      .catch(function(error) {
        console.log('Request failed:' + error);
      });
```

**Comment by mcrider** [comment]
Also, when I log the shopifyProduct object, most of the attributes have valid values out but `options`, `selectedVariant`, `selectedVariantImage`, and `selections` all have the value `<Permission denied>`

**Comment by softpower-lisa** [comment]
I am having exactly the same issue here.

**Comment by softpower-lisa** [comment]
This is fixed when I switch to the latest js file provided: 
http://sdks.shopifycdn.com/js-buy-sdk/v0/latest/shopify-buy.umd.polyfilled.min.js

Reference:
https://github.com/Shopify/js-buy-sdk/issues/258

**Comment by rebeccajfriedman** [comment]
Closing as fixed.
