### ISSUE TITLE
Apple Pay for Buy Now

### ISSUE THREAD

**Issue by sethbibler** [Shopify/js-buy-sdk#323]
My company needs a way to process Apple Pay payments via the Shopify Buy Now feature.

I am not certain if support needs to be added to the SDK. Presumably something should be done to validate SSL on the web host that loads the Buy Now iframe.

**Comment by minasmart** [comment]
Right now we don't have a checkout API that supports this form of tokenized payment over the web, and there aren't immediate plans for it. On the web, this process must remain entirely owned by web checkout for PCI compliance reasons.
