### ISSUE TITLE
How to setup different products, on different pages, connected to one persistent cart?

### ISSUE THREAD

**Issue by eriksilver** [Shopify/js-buy-sdk#332]
1) Is it possible to use the JS Buy SDK to setup different products on different pages of site, connected to one shopping cart that persists throughout the site? 
The examples in the documents always show one product or collection on a page. 

2) At high level, how is this done with the JS Buy SDK?

3) Can you point to an example of this solution on the internet?

**Comment by Enricopv** [comment]
I just started using this and you can create a cart which will have a cart id. You can update and remove products to that cart as well as fetching the cart itself as you navigate through pages.

<pre>
client.createCart().then(cart => {
  console.log(cart.id) // ex. shopify-buy.1459804699118.2
});

client.fetchCart('shopify-buy.1459804699118.2').then(cart => {
  console.log(cart); // The retrieved cart
});
</pre>

You can check out their reference here:
http://shopify.github.io/js-buy-sdk/api/classes/ShopClient.html

**Comment by minasmart** [comment]
You can query as many products by ID as you like, on as many pages as you like. The shopping cart is stored in local storage. Provided you're working on a single domain `client.fetchRecentCart` will always grab the most recent cart, so you don't need to do any ID wrangling.

I'm not sure what you need the most clarification on, but you can use as many permutations of `fetchProduct` documented [here](https://shopify.github.io/js-buy-sdk/api/classes/ShopClient.html#method-fetchProduct) as you like.

**Comment by minasmart** [comment]
We found a resolution via an email discussion. The cart permalink contained a product ID, where it needed a variant ID.
