### ISSUE TITLE
cart.checkoutUrl -> 410 - Link Expired

### ISSUE THREAD

**Issue by Enricopv** [Shopify/js-buy-sdk#334]
I'm having problems using the cart.checkoutUrl. Everytime I use it I just get:
<pre>shopClient.fetchProduct(productId)
      .then(product => {
            shopClient.fetchCart(cartId).then(cart => {
              cart.createLineItemsFromVariants({variant: product, quantity: 1}).then(cart => {
                window.open(cart.checkoutUrl);
              })
            })
          })</pre>
![carturl](https://cloud.githubusercontent.com/assets/7062889/24722294/17fea06c-19f8-11e7-85cb-678ae8d6a613.png)

I do have success using product.selectedVariant.checkoutUrl(1). Where the Url here looks exactly the same as the one generated from cart.checkoutUrl with the exception of the cart id. Is there something I am not considering? Is the cart somehow expiring? Is there something I'm not considering to prevent it from expiring?

**Comment by minasmart** [comment]
Hey there! This seems a little weird. Would you mind shooting me some details about the shop (like the shop domain) and a copy of the cart URL that's being generated? If you're not comfortable posting those details publicly, just shoot an email to mina.smart@shopify.com.

**Comment by Chr15t1an** [comment]
I am having the same issue

**Comment by minasmart** [comment]
@Chr15t1an in the case mentioned here, the product ID, rather than the variant ID was being used. Would you mind opening a new issue with the code you're using and details pertinent to your specific case?
