### ISSUE TITLE
cart.checkoutUrl -> 410 - Link Expired -- Using <variant> <id type="integer">x</id>

### ISSUE THREAD

**Issue by Chr15t1an** [Shopify/js-buy-sdk#363]
Hello, I'm trying to use the Shopify JS SDK and I'm having some issues. 

#I call in the JS lib

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
# I set up my client

```javascript
var shopClient = ShopifyBuy.buildClient({
  accessToken: 'X',
  domain: 'X',
  appId: '6'
});
```

# I get the Variant ID 

```javascript
// fetch a product using resource id
pid = shopClient.fetchProduct('X')
  .then(function (product) {
    varient_id = product.attrs.variants[0].id;
    return varient_id; // I also manually checked it to insure acuracy 
  })
  .catch(function () {
    console.log('Request failed');
  });
```
# Then I attempt to create the checkout URL 

```javascript
// var cart;
cart = shopClient.createCart().then(function (newCart) {
  cart = newCart;
  // do something with updated cart
  cart.addVariants({variant: X, quantity: 1}).then(function (cart) { // Manually entered the Variant ID 
    // do something with updated cart
  });

  document.location.href = cart.checkoutUrl;
});
```

#After all of that I get a 410 error from Shopify saying my link has expired 
# URL => /cart/undefined:1?access_token=XXXXXXXXXXX&_fd=0

Hopefully, I am doing something wrong and it's a quick fix! Thank you in advance.

**Comment by minasmart** [comment]
In this line:

```javascript
 cart.addVariants({variant: X, quantity: 1}).then(function (cart)
```
is `X` the variant? or `variant_id`?

Also, please don't access the variant through attrs. attrs are internal properties. The correct way to access the variant is `product.variant[0]`

**Comment by Chr15t1an** [comment]
In this line " cart.addVariants({variant: X, quantity: 1}).then(function (cart)"
X is the variant id. 
Also, when I try to use **product.variant[0]** I get an error => "index.html:14 Uncaught (in promise) TypeError: Cannot read property '0' of undefined"
_________
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="http://sdks.shopifycdn.com/js-buy-sdk/v0/latest/shopify-buy.umd.polyfilled.min.js"></script>

<script>
var shopClient = ShopifyBuy.buildClient({
  accessToken: '_token_',
  domain: '_domain.com_',
  appId: '6'
});
// fetch a product using resource id
shopClient.fetchProduct('_product-id_').then(function (product) {
varient_id = product.variant[0];
console.log(varient_id);
});
</script>

**Comment by minasmart** [comment]
Sorry, I typoed. It's `product.variants[0]`. Variants is plural.

Also, you should be using the variant object, not the variant id. `addVariants` receives a hash of `{variantObject, quantity}`. Additionally, the method was deprecated and replaced by `createLineItemsFromVariants` since it's more descriptive of what the method does. This method is [documented here](https://shopify.github.io/js-buy-sdk/api/classes/CartModel.html#method-createLineItemsFromVariants), and receives the same parameters: `{variantObject, quantity}`, and not the variant id.

**Comment by Chr15t1an** [comment]
All Good. :) 
Passing the object worked. Thank you. 
__________
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="http://sdks.shopifycdn.com/js-buy-sdk/v0/latest/shopify-buy.umd.polyfilled.min.js"></script>

<script>
var shopClient = ShopifyBuy.buildClient({
  accessToken: 'token-',
  domain: 'domain.com',
  appId: '6'
});

// fetch a product using resource id
shopClient.fetchProduct(product_id).then(function (product) {
varient_obj = product.variants[0];
//return varient_obj;
    var cart;
    shopClient.createCart().then(function (newCart) {
      cart = newCart;
      // do something with updated cart
      cart.addVariants({variant: varient_obj, quantity: 1}).then(function (cart) {
      // do something with updated cart
    });

    x = cart.checkoutUrl;
    });

});

</script>
