### ISSUE TITLE
Find out a collections product count

### ISSUE THREAD

**Issue by ButsAndCats** [Shopify/js-buy-sdk#369]
I can't seem to see a simple way of fetching a collections product count.

Currently I am checking if the query hit the page limit and then fetching the next page until the page limit isn't hit. This makes a really slow and difficult to set up pagination.

From reading closed issues I see other people have had this problem.

Is there a better work around?
Is there anything in the pipeline to resolve this?

**Comment by rebeccajfriedman** [comment]
Unfortunately, this isn't supported. You can always write custom queries (https://github.com/Shopify/js-buy-sdk#expanding-the-sdk) to change the page size, which will reduce the number of pages that you need to navigate through.
