### ISSUE TITLE
Attributes not being sent to cart when creating line items.

### ISSUE THREAD

**Issue by pmdownie** [Shopify/js-buy-sdk#370]
Hi.

I'm running into this problem with the createLineItemsFromVariants method that I hope someone can help me out with.

Basically, when I create a new line item in my cart from an exisiting product's variant, the line item gets created but there are numerous value fields in the cart that are left undefined in each object lineItems.

For example the image, title and product_id fields are black where as the price and total price have values.

Should I be passing these undefined values to the createLineItemFromVariant method individually?

Thanks

**Comment by minasmart** [comment]
Can you post a sample of the code you're using? The most common cause of this is someone passing in only the variant ID, or the  product instead of the variant.

Thanks!!

**Comment by pmdownie** [comment]
This is the function where I call createLineItemsFromVariants:

`addToCart(item) {`
	`this.props.cart.createLineItemsFromVariants({ variant: item, quantity: 1 })`
			`.then(cart => {`
				`this.props.updateCart(cart);`
			`});`
	`}`

And the item that I pass it on click is the first variant option in variants (seeing as every product in the store only has one variant).

Let me know if you need any more.

**Comment by donrodriguez** [comment]
So, how do you solve this problem?

**Comment by StefanSlehta** [comment]
[This PR](https://github.com/Shopify/js-buy-sdk/pull/485) addresses the issue. It won't return all of the info you want, however, it gives you the `product_id` so you can fetch any additional data you want.
