### ISSUE TITLE
Properties line_items not saved

### ISSUE THREAD

**Issue by wholcman** [Shopify/js-buy-sdk#371]
I figured out a problem with createLineItemsFromVariants. Indeed I tried to pass some extras datas to an order like:
`this.cart.createLineItemsFromVariants({ variant: variant, quantity: quantity, properties: { border: border }});
`
In the promise response, I can see in the cart the properties. Otherwise, when I tried to go to /admin/orders.json the properties object is empty.
Besides how can I display these values in the order page admin.

Thanks

**Comment by minasmart** [comment]
Line item properties aren't supported by `v0` of this module, and will not be. If you're feeling ambitious, take a look at [the v1.0-alpha](https://github.com/Shopify/js-buy-sdk/tree/v1.0alpha) version of this library, which includes this support. Additionally, we've included a [migration guide](https://github.com/Shopify/js-buy-sdk/blob/v1.0alpha/docs/MIGRATION_GUIDE.md) to help you get started if you have an existing build using Shopify Buy.

Thanks for passing this along!

**Comment by wholcman** [comment]
Ok, thanks. If I stay with `v0`, is there any way to match the cart with the checkout when we do `window.open`? Actually, I check some events sent by the pop in checkout 
`
const checkoutWindow = window.open(checkoutUrl);
window.addEventListener('message', this.onOrder, checkoutWindow);
`
I need to know for example the order id or something like that.

**Comment by minasmart** [comment]
Do you mind sharing how you're consuming the library? Is this through NPM? Yarn? Which build file are you referencing?

**Comment by wholcman** [comment]
`
npm install shopify-buy@alpha
`
`
import Client, {Config} from 'shopify-buy';

const config = new Config({
  storefrontAccessToken: 'xxx',
  domain: 'xxx.myshopify.com'
});

export default new Client(config);
`

**Comment by wholcman** [comment]
Fixed ! ;)
