### ISSUE TITLE
so the key's are just exposed to the internet?

### ISSUE THREAD

**Issue by francis23** [Shopify/js-buy-sdk#372]
```
const shopClient = ShopifyBuy.buildClient({
  accessToken: 'bf081e860bc9dc1ce0654fdfbc20892d',
  appId: '6',
  domain: 'embeds.myshopify.com'
});

// fetch a product using resource id
shopClient.fetchProduct('8569911558')
  .then(function (product) {
    console.log(product);
  })
  .catch(function () {
    console.log('Request failed');
  });
```

is this okay? just exposing the keys to the browser's f12 or there's another way to do this.

**Comment by minasmart** [comment]
This isn't a secret key. It's intended for public domains. Without a key, we have no ability to lock down the API around any one client that's misbehaving. Having a unique identifier per shop & build gives us that ability.
