### ISSUE TITLE
webpack -p fails when shopify-buy is present in a project

### ISSUE THREAD

**Issue by yantakus** [Shopify/js-buy-sdk#373]
Just this one line `import shopifyBuy from 'shopify-buy';` (I mean even without using it anywhere further) is enough for `webpack -p` to fail with the following error:

```
ERROR in 14.b62c90f89709f107e402.chunk.js from UglifyJs
Unexpected token: name (assign) [14.b62c90f89709f107e402.chunk.js:23263,4]

ERROR in 16.6b6ddd70b6f6c1552acc.chunk.js from UglifyJs
Unexpected token: name (assign) [16.6b6ddd70b6f6c1552acc.chunk.js:19893,4]
```

Any ideas on how to fix this?

**Comment by yantakus** [comment]
This is what I see inside `node_modules/shopify-buy`:

![shopify js e2 80 94 lift-v2 2017-06-09 18-50-19](https://user-images.githubusercontent.com/2179726/26983497-ab6d047c-4d44-11e7-83ae-2b2c2ff6ace1.png)

There's no files you mention.

**Comment by yantakus** [comment]
The version I use: `"shopify-buy": "^0.7.1",`. Did you expect me to use `v1alpha`?

**Comment by yantakus** [comment]
I'm using ES imports. As you can see above I'm using `import shopifyBuy from 'shopify-buy';` and I have `"modules": false` option in `.babelrc` file.

**Comment by yantakus** [comment]
Using `import shopifyBuy from 'shopify-buy/dist/shopify-buy.umd';` helped to solve the issue, thanks.

Why doesn't the UMD build exported as default?

**Comment by minasmart** [comment]
Sorry, I was assuming this was the alpha. Glad you found a solution!

The UMD is not the default, because NPM convention is to support commonjs, and the UMD file is larger, so there's not a ton of advantage.
