### ISSUE TITLE
A way to retrieve product quantity

### ISSUE THREAD

**Issue by cg219** [Shopify/js-buy-sdk#374]
I can't seem to find anywhere in the docs, a way to receive the quantity in stock for a product. I know there is an `available` attribute in the `attrs` of a product, but that is pretty vague. I don't want a customer to add multiples of a product if there is only one for example.

**Comment by minasmart** [comment]
This information isn't available through any public end point. When it has been in the past, it's been used by bots to hold fake reservations on products. Available/Not-Available is all we can provide. Web checkout will alert the user if they've over bought.
