### ISSUE TITLE
Android can not load product images

### ISSUE THREAD

**Issue by TUncleSan** [Shopify/js-buy-sdk#375]
Hi,
my code is only in the  Android can not load product images, and will be an error. The following is an error message:
GET https://cdn.shopify.com/s/files/1/1596/3761/products/20160812173954_3971.jpg?v=1487849894 net::ERR_CONNECTION_TIMED_OUT
My use environment: Galaxy S5, The system comes with a browser
thanks

**Comment by rebeccajfriedman** [comment]
Closing as stale. Please reopen if problem persists.
