### ISSUE TITLE
Weird errors

### ISSUE THREAD

**Issue by wholcman** [Shopify/js-buy-sdk#378]
Hi -

Some issues appeared without doing nothing.
v1.0 alpha 8

![capture d ecran 2017-06-21 a 18 31 00](https://user-images.githubusercontent.com/1247755/27395351-ce9aec38-56af-11e7-8181-43c8616cb983.png)

![capture d ecran 2017-06-21 a 18 26 11](https://user-images.githubusercontent.com/1247755/27395332-b8a03924-56af-11e7-9b3e-6b22a8ce9152.png)

Anyone have an idea ? 
Maybe linked with #376

**Comment by swalkinshaw** [comment]
Yes it's related to that. You'll need to use the latest version on master. We'll release v1.0 alpha.9 right now. Sorry for the delay.

**Comment by swalkinshaw** [comment]
v1.0 alpha.9 has now been published.

**Comment by wholcman** [comment]
Ok thanks, however, the issue is still here.

**Comment by lyninx** [comment]
can you provide the code that's causing the error? are you just using are you just using `client.createCheckout` or are you sending an order query?

**Comment by wholcman** [comment]
Just using functions like `createCheckout | fetchCheckout`. Right now, it works. 
Thanks, guys.
