### ISSUE TITLE
updateLineItems customAttributes

### ISSUE THREAD

**Issue by wholcman** [Shopify/js-buy-sdk#382]
Anyway to do something like: 
`
let customAttributes = [{ key: 'a', value: 'b' }];
client.updateLineItems(this.checkout.id, [{
id: item.id,
			quantity: item.quantity,
			customAttributes: customAttributes
		}]).then((checkout) => {
		});
`

Actually, it triggers an internal error. The `addLineItems` function works but not `updateLineItems`.

**Comment by wholcman** [comment]
Weird. It's working now.

**Comment by swalkinshaw** [comment]
@wholcman this was a bug on our API which we fixed yesterday 👍
