### ISSUE TITLE
Losing Product Model values

### ISSUE THREAD

**Issue by sturdynut** [Shopify/js-buy-sdk#388]
I have a next.js app (Server-side rendered React), so far everything should be pretty straight forward, but I am running into a strange issue with the Product model.  When getting my products via the js-buy-sdk my server-side render is correct, however when it performs the checksum on the client i'm getting the infamous "Warning: React attempted to reuse markup in a container but the checksum was invalid." 

![error](https://user-images.githubusercontent.com/8547391/28142179-8fac5bc2-6714-11e7-8456-a282e93801b9.png)

What appears to be happening is that `title` is populated on my products, but when the client-side render happens it is gone, so i've resorted to grabbing the title from the `attrs` property.  I'm pretty sure this isn't me, but wanted to see if I am doing something dumb or there is something else going on.

Here's an example of how I am using the sdk.  You can see where I have to do `p.title || p.attrs.title`.

Ideas?

```
import React, { Component } from "react";
import ShopifyBuy from "shopify-buy";

const Index = props =>
  <div>
    {props.products.map((p, i) => {
      return (
        <div key={i}>
          {p.title || p.attrs.title}
        </div>
      );
    })}
  </div>;

Index.getInitialProps = async function({ req }) {
  const shopClient = ShopifyBuy.buildClient({
    accessToken: process.env.SHOP_TOKEN,
    domain: process.env.SHOP_DOMAIN,
    appId: process.env.SHOP_APP_ID
  });
  const products = await shopClient.fetchAllProducts();

  return {
    products: products
  };
};

export default Index;
```

**Comment by minasmart** [comment]
There's nothing in the SDK that clears top level properties. The one caveat is that some properties are getters, and if the transport between back end and front end is JSON of the model, the getters will be lost, and only their values will be persisted. That said, there's nothing in our code that would ever unset a set value.

Are you able to provide more detail? Like how the data is being passed from back end to front end? Is next.js not friendly wit ES5 getters?

**Comment by sturdynut** [comment]
Hey @minasmart, thank you for the response.  I put together an example demonstrating the issue so you can see what's going on in isolation.  

I wonder if it has to do with those getters.  The only thing I can think of is that they may be lost when the client-side render happens because of how React is cloning/copying props generated server-side.  I don't understand the depths of what goes on there so I'll continue to dig in and see if I find anything.

### Example Project

* `yarn` or `npm install` and then `npm run dev`

[next-shopify-example.zip](https://github.com/Shopify/js-buy-sdk/files/1145614/next-shopify-example.zip)

**Comment by minasmart** [comment]
ok. found the issue. This was a good find. All the getters are defined using `defineProperty`, and we don't set an `enumerable` value in the property descriptor. The descriptor _should_ have `{ enumerable: true }`. The default value for `enumerable` is `false` (according to the ES5 spec), but I'm pretty sure most browsers didn't actually respect that at the time of writing (because during testing, we could transform objects to json without a problem). Browsers seem to be more consistent now, so when these values get transformed to json, they are not enumerated, and are lost.

Good news is the fix should be pretty easy. I'll update here in the next day or so when I get a fix out.

If you're interested, the code causing this problem is [here](https://github.com/Shopify/js-buy-sdk/blob/master/src/metal/create-class.js#L27-L39)

Thanks for finding this! I'm sure you're not the only one affected.

**Comment by sturdynut** [comment]
Wow, that is interesting.  Not sure if it helps, but I tried to fix by adding the `enumerable: true` to the defineProperty calls but didn't seem to fix it for me.  What I was seeing is that the getter for `title` was blowing up because in the getter `this.attrs` is null.  I see that it is being set in the model constructors, so maybe this is an issue with serialization?  Just speculation...

Here's the errors/stack traces related to the issue with `this.attrs` being null.  The code that was causing this error was `console.log(destination.title);`.

![screen shot 2017-07-13 at 11 53 39 am](https://user-images.githubusercontent.com/8547391/28182850-43058146-67c2-11e7-947c-e79be1732db6.png)

![screen shot 2017-07-13 at 11 54 26 am](https://user-images.githubusercontent.com/8547391/28182851-4325d9be-67c2-11e7-8a4c-d334ff07fe84.png)

Thank you for the help!

**Comment by rebeccajfriedman** [comment]
Closing as stale.
