### ISSUE TITLE
Checkout URL in Google Analytics and Google Tag Manager

### ISSUE THREAD

**Issue by douglas-johnson** [Shopify/js-buy-sdk#389]
In version 0.7.2 the cart model uses the `ga()` function which assumes it will be passed a tracker parameter. This fails when using Google Analytics through Google Tag Manager.

https://github.com/Shopify/js-buy-sdk/blob/v0.7.2/src/models/cart-model.js#L104

A version that uses `ga.getAll()` instead and uses the last tracker in the array is compatible with both GA and GTM.

```js
ga(function(){
  const trackers = ga.getAll();
  if(typeof trackers !== 'object' || trackers.length === 0){
    return;
  }
  linkerParam = trackers[trackers.length-1].get('linkerParam');
});
```

I apologize for not just submitting a pull request myself, but I kept having linting issues and couldn't spend any more time on it.

**Comment by AbeCole** [comment]
+1 - had same experience and used the following similar code to resolve:

        ga(function (tracker) {
          var trackers = ga.getAll();
          if (trackers.length) {
            linkerParam = trackers[0].get('linkerParam');
          }
        });
