### ISSUE TITLE
[1.0alpha] Ability to update checkout properties

### ISSUE THREAD

**Issue by agos** [Shopify/js-buy-sdk#392]
When [creating a checkout](https://github.com/Shopify/js-buy-sdk/blob/v1.0alpha/docs/API_REFERENCE.md#Client+createCheckout), a variety of parameters are accepted, including a shipping address, an order note, and (most importantly for my use case) custom properties. 

While these are very useful, they are not always known at the time of creating a checkout, which I suspect for many SDK users would be at application startup or as soon as a product is added to the cart.

A cart update mutation and a corresponding SDK function would be very helpful, for a variety of use cases, at least for the same fields which are allowed at creation time.

**Comment by swalkinshaw** [comment]
Hey @agos, we do have a `checkoutAttributesUpdate` mutation which does what you want.

This just came up in https://github.com/Shopify/js-buy-sdk/issues/384. We'll be adding it to the SDK at some point soon.

**Comment by isaachinman** [comment]
Was this ever resolved? As far as I can tell, it's still not possible to update email, shipping address, custom props, etc.
