### ISSUE TITLE
Custom Attributes are not saved to Line Item

### ISSUE THREAD

**Issue by aarohmankad** [Shopify/js-buy-sdk#393]
When sending a mutation to add a `line_item` to a checkout with some `customAttributes`, the `customAttributes` are not saved to the line item or returned.

![image](https://user-images.githubusercontent.com/3311321/28682394-9c7a177e-72b1-11e7-9d1d-920eda86bf29.png)

**Comment by swalkinshaw** [comment]
This isn't possible right now from the Storefront API. It's on our roadmap though.

See https://github.com/Shopify/js-buy-sdk/issues/168 for more background.

**Comment by aarohmankad** [comment]
Hey so I seem to have been mistaken earlier. I'm actually wanting to set `properties` of a `line_item` and have it persist all the way to the fulfillment request email.

As of now, I'm able to set a custom property and generate a url, however when the fulfillment email is sent, the properties of my line_item are empty.

**Comment by minasmart** [comment]
Can you post the query, or js code that you're using to set properties?

**Comment by minasmart** [comment]
ok, this is the `v0` client. line item properties are only supported by the current `v1` alpha. There is no API that we can process line item properties with using `v0`.

Also,  as a note: `attrs` is a private property. Please use `cart.lineItems`

**Comment by aarohmankad** [comment]
@minasmart Using `v1` alpha now, I see that I can add `customAttributes` to my line items, great!

In my liquid template email, can I access these attributes using the `properties` or the `customAttributes` key on a `line_item`?

**Comment by minasmart** [comment]
It should have the custom attributes under the `properties` key. Can you confirm that they're not there? Or is it that the name `customAttributes` isn't available in liquid?

**Comment by aarohmankad** [comment]
The `properties` attribute of my `line_item` is an empty array.

**Comment by aarohmankad** [comment]
Updates?

**Comment by minasmart** [comment]
not as of yet.

**Comment by aarohmankad** [comment]
Here is some test input/output from GraphiQL. As you can see, the submitted `customAttributes` are not set or returned.

![image](https://user-images.githubusercontent.com/3311321/28635105-4468729c-71ee-11e7-9a08-466a9f9de428.png)

**Comment by minasmart** [comment]
Thanks for the GraphiQL snippet. We're looking in to this now.

**Comment by aarohmankad** [comment]
No problem! Any chance this issue could be reopened?

**Comment by minasmart** [comment]
We have a fix in our API that should be rolling out soon.

**Comment by minasmart** [comment]
This has been fixed in production. Please create a new issue, or reopen if it recurs.

**Comment by muzuitech** [comment]
How can I set up background colors and other stuffs using createCart() ? Anyone have idea. I am researching but not able to find anything which can solve. 

Thanks

**Comment by rebeccajfriedman** [comment]
@muzuitech Can you please create a new issue for this in the https://github.com/Shopify/buy-button-js repo?

**Comment by Sanjayavidbrio** [comment]
> you post the query, or js code that you're using to set properties?

@minasmart  how I can add lineitem or note in with buy now button 

I try to  add with payload and custom temaptles 

but not working 


`      options: {
            lineItem: {
		templates: {
			customAttributes: '{{#data.customAttributes}}<div><small>{{key}}: {{value}}</small></div>{{/data.customAttributes}}'
		},
		contents: {
			customAttributes: true
		},
		order: [
			'image',
			'title',
			'variantTitle',
			'customAttributes',
			'price',
			'priceWithDiscounts',
			'quantity',
		],
	},
    "product": {
      contents: {
        description: true,
        quantity: true,
        note: true,
        lineItem: true,
        lineItems: true,
        quantityDecrement: true,
        quantityIncrement: true,
      },
      order: [
        'img',
        'title',
        'variantTitle',
        'price',
        'note',
        'options',
        'customAttributes',
        'lineItems',
        'lineItem',
        'description',
         'quantity', 
        'button',
      ], `
