### ISSUE TITLE
[1.0alpha] Checkout lineItems can end up with null variant

### ISSUE THREAD

**Issue by agos** [Shopify/js-buy-sdk#394]
I've noticed instances of checkouts in which one (or possibly more) `lineItem` has the `variant` field set to `null`. Other attributes look fine.

I can't reliably reproduce it, but here's the id of a checkout exhibiting the issue:
`Z2lkOi8vc2hvcGlmeS9DaGVja291dC9jNzYwMjBmZWI1ZDM1NjdhNTM0OTQ3OWU1MjRkYWE0Mz9rZXk9MjZjYzUyZWJmNTE4M2MwYjgzYTQ2ZmM3MmU2MWYzOWI=`

Looking at the relevant [Storefront API Documentation](https://help.shopify.com/api/storefront-api/reference/object/checkoutlineitem), it does indeed look like the `variant` field can be `null`.

Some questions arise:

- Is this really expected behavior?
- What is the meaning / cause of this condition?
- Can / should this be prevented? How?
- Can / should such a checkout be succesfully completed?

**Comment by minasmart** [comment]
Hey there! Without some more information, it's kind of hard to track this down. I need to know the shop, and with what products / variants this is occurring. Even if it's intermittent. Also, can I see the query you're using to produce this? It definitely sounds like there's a bug somewhere, without a little more detail, I can't do much to sort it out. If you're not comfortable sending shop names and IDs through github, please shoot me an email at mina.smart@shopify.com

**Comment by agos** [comment]
I haven't been able to reliably reproduce this behaviour, so I'm closing this. Thanks!
