### ISSUE TITLE
[1.0alpha] fetch is not defined when using fetchAllProducts()

### ISSUE THREAD

**Issue by aarohmankad** [Shopify/js-buy-sdk#395]
I'm rewriting some code using 1.0 because it supports setting properties on `line_items`.

However, when doing a basic test to `fetchAllProducts()`, I'm getting an error that fetch is undefined? I would appreciate any help in resolving this issue.

![image](https://user-images.githubusercontent.com/3311321/28442565-bd9da0ca-6d65-11e7-9c99-770299cad205.png)

**Comment by minasmart** [comment]
right now the constructor expects fetch to be globally available. In node this is tricky. The easiest way around this is to use `node-fetch` and assign it to `globals.fetch`. We're working on a way to pass in constructor options to the internal graphql client, so you can write your own HTTP layer (since in node, this could be whatever). Hope this help!

**Comment by aarohmankad** [comment]
It did! Any chance you got time to read my issue with `customAttributes` in #393? (I added some complications after the issue was closed.)

Thanks again for your help!

**Comment by maziarz** [comment]
Any updates on this issue? I am running into similar problems in a server-side rendered application with NuxtJS

**Comment by minasmart** [comment]
We don't have a build that supports this yet. We will by the time we launch 1.0.

**Comment by M3kH** [comment]
Can be the `fetch` function being injected in the constructor of the client?

**Comment by rebeccajfriedman** [comment]
Closing as stale.

**Comment by craigmichaelmartin** [comment]
Resolution in https://github.com/Shopify/js-buy-sdk/issues/458#issuecomment-352070407:
> The [constructor will take an argument](https://github.com/Shopify/js-buy-sdk/blob/master/src/client.js#L28) for you to supply whichever server side fetch implementation you like.
