### ISSUE TITLE
Allow specifying a fulfillment service per line_item

### ISSUE THREAD

**Issue by aarohmankad** [Shopify/js-buy-sdk#397]
As of right now, a `CheckoutLineItemInput` only allows `customAttributes`, `quantity`, and a `variantId`.

[Relevant Docs Page](https://help.shopify.com/api/storefront-api/reference/input_object/checkoutlineiteminput)

**Comment by aarohmankad** [comment]
Ah this was my mistake, the Admin API allows for setting fulfillment service per product.

**Comment by minasmart** [comment]
Yes, but this isn't the admin API. You need to be authenticated to use this. This API is for operating in untrusted domains (mobile apps, javascript web apps). The scope of behaviour is anything a customer could do through the online store. 😄
