### ISSUE TITLE
Multi-language

### ISSUE THREAD

**Issue by martinrisseeuw** [Shopify/js-buy-sdk#400]
Hi,

Is multi-language supported in combination with apps such as Langify? Or should you create a different store for every language? We would like to have stores for every region but language a bit more flexible. 

http://secridnl.martinr.nl/en/collection/cardprotector?region=nl
http://secridnl.martinr.nl/en/collection/cardprotector?region=us

Changing stores according to regions works well only now we're looking how we can best call different languages from the api.

**Comment by minasmart** [comment]
We only support the features that shopify supports, and at the moment, none of our APIs support multiple languages. Sorry about that.

**Comment by martinrisseeuw** [comment]
@minasmart Would it be possible to create different Metafields with different translations and load these through the API?

**Comment by minasmart** [comment]
metafields contain  both secure, and insecure information. There are apps that pack very private information into metafield that should only ever be merchant facing. Because of this, we cannot expose metafields through an unauthenticated API.
