### ISSUE TITLE
cart.checkoutUrl does not use primary store domain

### ISSUE THREAD

**Issue by andrevvm** [Shopify/js-buy-sdk#408]
```cart.checkoutUrl``` uses the default ```store.myshopify.com``` domain. I've tried replacing the domain manually with my custom store domain, and ```checkout.shopify.com``` is loaded instead.

Is there anyway to ensure the primary domain is used with ```cart.checkoutUrl```?

**Comment by Gomah** [comment]
Hi @andrevvm,

I had the same issue a month ago, apparently, the checkout domain is controlled internally & has to be manually set by your Shopify Merchant Success Manager.

**Comment by darrenjacoby** [comment]
Does this only work with Shopify plus? Are lite/basic users stuck with checkout.shopify.com? I'm getting mixed information, so just want to make sure.

**Comment by rebeccajfriedman** [comment]
@darrenjacoby this is available to everyone - not just Plus merchants.
