### ISSUE TITLE
Buy button not working on checkouts with customer accounts

### ISSUE THREAD

**Issue by parmazhon** [Shopify/js-buy-sdk#409]
We use the buy button on landing pages (not on our Shopify website). And on our Shopify store, we require customer accounts for purchases.

For the buy button, the checkout process works fine when a returning customer logs in to their account. However, if someone needs to register for a new customer account, the checkout process breaks. (After the customer registers for the account it directs them to the account page. There are no items in their cart. They have to start the process all over again)

I was wondering, what are some possible ways to make the buy button work with customer accounts?

Here is an example of a landing page, if you want to see the checkout process: https://blog.donnadowney.com/online-workshops/distressed-flowers

**Comment by rebeccajfriedman** [comment]
This seems like an issue with the checkout flow and customer accounts. If you are still experiencing this issue, please post on the [developer forums](https://community.shopify.com/c/Shopify-Community/ct-p/en).
