### ISSUE TITLE
[1.0alpha] variant doesn't have compare at price

### ISSUE THREAD

**Issue by zendy** [Shopify/js-buy-sdk#413]
When doing a query of a product, I don't get `compare at price` as part of the response.

I had a look at the schema, but I couldn't find `compare_at_price` in it. But looking at the older release, I can find `compare_at_price` in there.

Did I miss anything? Or is it not included in the alpha release just yet?

**Comment by minasmart** [comment]
All properties are camel cased. All variants have `compareAtPrice` in their query, and it is present on the returned models if set in the admin.

**Comment by zendy** [comment]
@minasmart yes it's in the schema, but it's not being queried yet. I made a PR to fix that https://github.com/Shopify/js-buy-sdk/pull/417

**Comment by Jimtattersall** [comment]
I notice compareAtPrice isn't included in the returned cart object also. Is this intentional ?
p.s. huge thanks for an awesome sdk.

**Comment by blakewatson** [comment]
Just following up on this issue. I'm needing compareAtPrice but not seeing it on the variant.

**Comment by dennylouis** [comment]
I'm noticing the same thing. There's no compareAtPrice property coming through in the variants.

**Comment by rebeccajfriedman** [comment]
This is available on the latest release.
