### ISSUE TITLE
[1.0.0-alpha.12] Helpers undefined when attempting to use variantForOptions

### ISSUE THREAD

**Issue by maziarz** [Shopify/js-buy-sdk#418]
variantForOptions is not working. According to the documentation it should be accessible by `Client.Product.Helpers.variantForOptions`.

```
var client =
        new Client(
          new Config({
            domain: 'rokoko-com.myshopify.com',
            storefrontAccessToken: '36e67197c8c66fc986446e2f01740996'
          })
        )

client.Product.Helpers.variantForOptions(data.product.id, {'Size': 'M'})
```

Error: `Uncaught TypeError: Cannot read property 'Helpers' of undefined`

**Comment by minasmart** [comment]
`Product` is a static property of `Client`, not an instance property. Try accessing it as `Client.Product`

**Comment by Jimtattersall** [comment]
I'm seeing the same issue on this. 

`
    client.fetchQueryProducts({ handle: window.product }).then((product) => {
      console.log(Client.Product.Helpers.variantForOptions(product[0], { 'Size': 'S' }))
    })
`
This logs "Undefined" the product has variants with the Size option of 'S'
product[0] when logged returns a valid Object
