### ISSUE TITLE
Ability to query by product_type

### ISSUE THREAD

**Issue by gdenisov** [Shopify/js-buy-sdk#419]
Unless I am missing something from the documentation it does not seem to be possible to filter products by type.

**Comment by minasmart** [comment]
You're completely right, and we should probably add this. I'm going to add it to our API feature backlog.

Good find! Thanks!

**Comment by danielpost** [comment]
@gdenisov As a temporary workaround, I think it's possible to automatically add products to a collection based on their type and then query this collection.

**Comment by rebeccajfriedman** [comment]
Closing this as complete. We can filter by product_type, as seen in our documentation: https://help.shopify.com/api/custom-storefronts/storefront-api/reference/object/shop#products
