### ISSUE TITLE
Documentation incorrectly states the default sort_by value for ShopClient.fetchQueryProducts

### ISSUE THREAD

**Issue by gdenisov** [Shopify/js-buy-sdk#421]
The documentation states that the default sort_by value is `collection-default`. However, it appears that the `updated_at` at sorting is applied when no sort_by value is provided.

Link to documentation: http://shopify.github.io/js-buy-sdk/api/classes/ShopClient.html#method-fetchQueryProducts

**Comment by vpicone** [comment]
No matter what I do, fetchQueryProducts always returns my entire product list regardless of my query. I've tried using tags, collection ID, and changing the sorting to no avail. 

`this.props.client
      .fetchQueryProducts({ tags: ['hat'], sort_by: 'collection-default' })
      .then((products) => {
        console.log(products);
      });`

**Comment by rebeccajfriedman** [comment]
Closing as this relates to v0.
