### ISSUE TITLE
npm run examples:serve FAILS TO START

### ISSUE THREAD

**Issue by ahmedmusawir** [Shopify/js-buy-sdk#423]
My Node version: v8.5.0
My NMP version: 5.4.2
Mac OSX: 10.12.6

Here is the errors:
<pre>
npm run examples:serve

> shopify-buy@0.7.2 examples:serve /Users/shourav/Documents/_DEV/testing-local/shopify/js-buy-sdk
> rimraf .dist-test/; mkdir .dist-test/; rimraf dist/; mkdir dist/; npm run examples:build && concurrently 'npm run umd-shopify-buy:watch' 'http-server -p 4200 .dist-test/'

sh: rimraf: command not found
mkdir: .dist-test/: File exists
sh: rimraf: command not found
mkdir: dist/: File exists

> shopify-buy@0.7.2 examples:build /Users/shourav/Documents/_DEV/testing-local/shopify/js-buy-sdk
> npm run examples:copy && npm run examples-css:build

> shopify-buy@0.7.2 examples:copy /Users/shourav/Documents/_DEV/testing-local/shopify/js-buy-sdk
> cp -r examples .dist-test/examples

> shopify-buy@0.7.2 examples-css:build /Users/shourav/Documents/_DEV/testing-local/shopify/js-buy-sdk
> concurrently 'npm run examples-css-cart:build' 'npm run examples-css-checkout:build'

sh: concurrently: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! shopify-buy@0.7.2 examples-css:build: `concurrently 'npm run examples-css-cart:build' 'npm run examples-css-checkout:build'`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the shopify-buy@0.7.2 examples-css:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shourav/.npm/_logs/2017-09-24T05_17_22_098Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! shopify-buy@0.7.2 examples:build: `npm run examples:copy && npm run examples-css:build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the shopify-buy@0.7.2 examples:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shourav/.npm/_logs/2017-09-24T05_17_22_118Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! shopify-buy@0.7.2 examples:serve: `rimraf .dist-test/; mkdir .dist-test/; rimraf dist/; mkdir dist/; npm run examples:build && concurrently 'npm run umd-shopify-buy:watch' 'http-server -p 4200 .dist-test/'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the shopify-buy@0.7.2 examples:serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shourav/.npm/_logs/2017-09-24T05_17_22_136Z-debug.log
</pre>

**Comment by juanpasolano** [comment]
Just want to share my logs for documentation
node: v6.11.2
npm: 5.5.1
Mac OSX: 10.12.6

```
$ npm run examples:serve
> shopify-buy@0.7.2 examples:serve /Users/juanpablo/Desktop/js-buy-sdk
> rimraf .dist-test/; mkdir .dist-test/; rimraf dist/; mkdir dist/; npm run examples:build && concurrently 'npm run umd-shopify-buy:watch' 'http-server -p 4200 .dist-test/'

sh: rimraf: command not found
mkdir: .dist-test/: File exists
sh: rimraf: command not found
mkdir: dist/: File exists

> shopify-buy@0.7.2 examples:build /Users/juanpablo/Desktop/js-buy-sdk
> npm run examples:copy && npm run examples-css:build


> shopify-buy@0.7.2 examples:copy /Users/juanpablo/Desktop/js-buy-sdk
> cp -r examples .dist-test/examples


> shopify-buy@0.7.2 examples-css:build /Users/juanpablo/Desktop/js-buy-sdk
> concurrently 'npm run examples-css-cart:build' 'npm run examples-css-checkout:build'

sh: concurrently: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! shopify-buy@0.7.2 examples-css:build: `concurrently 'npm run examples-css-cart:build' 'npm run examples-css-checkout:build'`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the shopify-buy@0.7.2 examples-css:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/juanpablo/.npm/_logs/2017-10-26T04_41_37_826Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! shopify-buy@0.7.2 examples:build: `npm run examples:copy && npm run examples-css:build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the shopify-buy@0.7.2 examples:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/juanpablo/.npm/_logs/2017-10-26T04_41_37_875Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! shopify-buy@0.7.2 examples:serve: `rimraf .dist-test/; mkdir .dist-test/; rimraf dist/; mkdir dist/; npm run examples:build && concurrently 'npm run umd-shopify-buy:watch' 'http-server -p 4200 .dist-test/'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the shopify-buy@0.7.2 examples:serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/juanpablo/.npm/_logs/2017-10-26T04_41_37_930Z-debug.log
```

**Comment by minasmart** [comment]
this looks like `npm install` wasn't run. Can you `ls node_modules/.bin`?
