### ISSUE TITLE
[1.0alpha] Query products by handle

### ISSUE THREAD

**Issue by danielpost** [Shopify/js-buy-sdk#429]
In the previous version, you could query products by handle (return all products which handle matches the supplied handle). In this version, it seems you can only query by title using `fetchQueryProducts`. Right now I'm querying all products and looping through them to find the one that matches the supplied handle, but is there any way to do this with a single query?

**Comment by minasmart** [comment]
This is supported in the beta build. There's a `product.fetchByHandle` method.
