### ISSUE TITLE
[1.0alpha] order customerUrl pointing to wrong URL

### ISSUE THREAD

**Issue by formatlos** [Shopify/js-buy-sdk#431]
In my custom storefront I want to display all orders of a user with tracking information etc. 

With each order I get the field `customerUrl` which in my opinion should point to the last step in the checkout, so basically the same link which gets emailed to the customer. But instead it leads to the normal shopify account page for that order. This doesn't make too much sense because I'm creating a custom storefront too not have to deal with the regular shopify kind of things...

I know that I potentially could generate this link manually but this would involve decoding the base64 ids etc. which I'd consider as a hack and not really future proof, as the graphql id's might change I guess. 

Can you provide the Link to the checkout page with the tracking info in this field or in another field?

**Comment by minasmart** [comment]
This was probably a miss in our implementation. I'll look into it. Thanks for noticing!

**Comment by formatlos** [comment]
Do you have any information on how long it'll take to implement this?

**Comment by rebeccajfriedman** [comment]
This can be accessed via the [statusUrl](https://help.shopify.com/en/api/custom-storefronts/storefront-api/reference/object/order#statusurl) on the order object and [orderStatusUrl](https://help.shopify.com/en/api/custom-storefronts/storefront-api/reference/object/checkout#orderstatusurl) on the checkout object.
