### ISSUE TITLE
[1.0beta] Config not being exported

### ISSUE THREAD

**Issue by danielpost** [Shopify/js-buy-sdk#432]
Apologies for all the issues I've been opening. Hopefully this one will be somewhat useful.

I _think_ I found a bug in the exports. In your README, you recommend initialising a store like this: `import Client, {Config} from 'shopify-buy';`. However, while this works fine for `Client`, it seems like `Config` is undefined. Upon taking a closer look at the code, it seems like only `Client` is being exported.

From what I've seen it seems like `Config` is just a wrapper function that maps deprecated keys to their current ones. Based on this, initialising the store like this still works:

```js
import Client from 'shopify-buy'

const config = {
  domain: 'domain.myshopify.com',
  storefrontAccessToken: 'token-here'
}

const client = new Client(config)
```

However, as soon as you use apiKey or accessToken, the code fails. I don't know if Config is being phased out on purpose or if it's just missing, but either way I thought I'd let you know!

**Comment by minasmart** [comment]
You shouldn't use the config class directly. This was updated in the migration guide, but looks like we missed the readme. 

Please use `Client.buildClient`. it wraps up the config class and still gives you useful errors, without requiring you to have to instantiate two separate classes.

**Comment by coalescecreate** [comment]
Sorry this is not super clear as to the intended way to create a new instance of the Client in the beta version. 
The [migration guide recommends](https://github.com/Shopify/js-buy-sdk/blob/v1.0.0-beta.3/docs/MIGRATION_GUIDE.md#initialization) that you also import Config which is not possible as  @danielpost  has mentioned.

**Comment by danielpost** [comment]
@coalescecreate This is how I'm doing it (without import/export).

```js
const Client = require('shopify-buy')

const config = {
  domain: domain.myshopify.com',
  storefrontAccessToken: 'XXX'
}

const shopify = Client.buildClient(config)

module.exports = shopify
```

**Comment by minasmart** [comment]
Yeah, sorry. I thought the docs had been updated. @danielpost has it right 👍

**Comment by blakewatson** [comment]
Had the same issue. Took me a while to realize the docs were outdated. Thanks! This method is more straightforward (now that I know about it).
