### ISSUE TITLE
There is no monified files in npm of v1.0.0-alpha.1~v1.0.0-beta.3

### ISSUE THREAD

**Issue by sufuf3** [Shopify/js-buy-sdk#437]
Hi @minasmart @mikkoh @swalkinshaw @tessalt  ,
We are cdnjs team, we're going to host this library.
CDNJS is one of the most famous free and public web front-end CDN services which is used by ~1,143,000 websites worldwide.

Could you add the minified files of `index.umd.js` and `index.amd.js` in npm?

And we use npm auto-updater to get the files.
I test these two files and they can be used in web front-end.
But there are no `index.umd.min.js` and `index.amd.min.js` in v1.0.0-alpha.1~v1.0.0-beta.3.
Could you provide them?

If you have any suggestions, please let me know.
Thank you.

cdnjs/cdnjs#11923
cdnjs/cdnjs#11909

**Comment by sufuf3** [comment]
@minasmart could you give me suggestion about the monified files in npm of v1.0.0-alpha.1~v1.0.0-beta.3?
Thank you.

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Hi @minasmart, may I ask that if it's possible to keep providing minified release file of umd build in future which could be really useful? Many thanks.

Best,
Peter

**Comment by minasmart** [comment]
We have our own CDN that hosts minified files, but they do not distribute the alpha or beta branches. If you're consuming via an NPM module, it's your responsibility to choose a minifier for your build.

**Comment by PeterDaveHello** [comment]
Thanks for the prompt reply! So besides the website, will the final/stable version of v1.0.0 contains minified files? Ask because the old versions on npm registry contain that, and it'll be great that if we host the 100% same file, for the file integrity, thanks again.

**Comment by minasmart** [comment]
Our new NPM module will likely not contain minified files. They will be provided through our CDN. The NPM module will leave which minifier to use up to the consumer.

**Comment by PeterDaveHello** [comment]
hmmmm ... a little bit sad but still thank you, hope there can be any chances to put it on npm registry or git tagged version in future so that we can host it the latest version back :)
