### ISSUE TITLE
_shopifyBuy.Config is not a constructor

### ISSUE THREAD

**Issue by vasinl124** [Shopify/js-buy-sdk#438]
"shopify-buy": "^1.0.0-beta.3"

Got this error in the console when I am trying to follow the get started tutorial from this repo https://github.com/Shopify/storefront-api-examples/tree/master/react-js-buy.

<img width="537" alt="screen shot 2017-10-15 at 12 19 36 am" src="https://user-images.githubusercontent.com/6901435/31582401-9cbca9b0-b13e-11e7-94ce-408f292d5b4b.png">

**Comment by minasmart** [comment]
I'd need to see your code to understand more, but my guess is, it's related to [this issue](https://github.com/Shopify/js-buy-sdk/issues/432).

There's a working example in there, and the docs need to be updated. If this isn't the fix you need, please let me know.

**Comment by maziarz** [comment]
I have the exact problem, but in a Nuxt project (VueJS)..

**Comment by vasinl124** [comment]
Hi @minasmart  

I tried from the example react-js-buy https://github.com/Shopify/storefront-api-examples/tree/master/react-js-buy
`import Client from 'shopify-buy';

const config = {
  domain: 'graphql.myshopify.com',
  storefrontAccessToken: 'dd4d4dc146542ba7763305d71d1b3d38'
}

export const client = Client.buildClient(config)`

I got another error said `Uncaught TypeError: this.props.client.createCheckout is not a function`

**Comment by minasmart** [comment]
That example is designed to work with the alpha. It hasn't been updated to work with he beta as of yet.

**Comment by benbonnet** [comment]
@minasmart to clarify; one should avoid referring to the README when running the examples; and vice-versa ?

**Comment by minasmart** [comment]
The readme specifies `buildClient` for initializing now as far as I can tell?

**Comment by benbonnet** [comment]
indeed and it is working well now. just getting in; wrongly expected the examples in full sync with the latest version

**Comment by minasmart** [comment]
Which examples aren’t in sync?

**Comment by swalkinshaw** [comment]
https://github.com/Shopify/storefront-api-examples I believe

**Comment by minasmart** [comment]
The comment referenced the examples in the readme though.

**Comment by benbonnet** [comment]
-_- not even on the right repo; my bad sorry for that. but yep had this issue from "storefront-api-examples"

**Comment by samuelmadeu** [comment]
Hi @minasmart, I too am experiencing the error: `App.js:23 Uncaught TypeError: this.props.client.createCheckout is not a function` but I am in the Alpha. 

"shopify-buy": "^1.0.0-alpha.9"

`const Client = require('shopify-buy')

const config = {
  storefrontAccessToken: 'dd4d4dc146542ba7763305d71d1b3d38',
  domain: 'graphql.myshopify.com',
}

const shopify = Client.buildClient(config)

module.exports = shopify`

**Comment by minasmart** [comment]
Any reason why you're not on the release version of `v1`? Everything should be working there.

**Comment by maziarz** [comment]
@minasmart, is all the helper functions implemented in the `v1` release, e.g. `Client.Product.Helpers`?

**Comment by minasmart** [comment]
All helpers are referenced by lower case as `client.<resource>.helpers`, or in this case `client.product.helpers`. The only product helper that's currently necessary is `client.product.helpers.variantForOptions` [which is documented here](https://github.com/Shopify/js-buy-sdk/blob/master/src/product-helpers.js#L6-L20)

**Comment by maziarz** [comment]
@minasmart, excellent! I will begin migrating soon 👍  Cheers.
