### ISSUE TITLE
[1.0.0-alpha.12] "ReferenceError: Can't find variable: fetch" in Safari

### ISSUE THREAD

**Issue by maziarz** [Shopify/js-buy-sdk#444]
Hi there. I have just finished my nuxt.js based application for a SPA, which has problems loading in Safari 9.0.1 on OS X 10.11.1.

The error i am getting is:  `Error while initializing app – ReferenceError: Can't find variable: fetch' 

I guess that this issue is polyfill related?

**Comment by minasmart** [comment]
It's not polyfill related. `nuxt` runs in the context of `node`, and there's no global `fetch` function there. You need to provide one. In the next release, I'll be exposing an additional constructor argument that let's you pass in a fetcher function for the underlying `graphql-js-client`.

**Comment by maziarz** [comment]
Sounds good @minasmart, thanks for the quick response!

**Comment by minasmart** [comment]
Oh, one thing about safari: fetch is only in versions 10 and up. Safari 9 was EOLed in 2016.

**Comment by maziarz** [comment]
Excellent! I added `whatwg-fetch` and problems sort of vanished. I agree that Safari 9 is ancient, but we have quite a lot of users spinning their computers with that browser.

**Comment by minasmart** [comment]
makes sense!

I think in cases like this, it's worthwhile to figure out what environments make sense for you to target, and to provide the appropriate polyfills. I think providing the library pre-packaged with the polyfills Shopify thinks is best won't ever really satisfy a large subset of our developer community.

**Comment by maziarz** [comment]
Absolutely agree with you, one size does not fit all, especially not from a front-end perspective..
