### ISSUE TITLE
"Default Title" Dropdown

### ISSUE THREAD

**Issue by markwbrown** [Shopify/js-buy-sdk#446]
Products with no variants are showing up with Title: and a dropdown "Default Title". 
![screen shot 2017-11-14 at 2 06 58 pm](https://user-images.githubusercontent.com/5036282/32807773-e7c4c5fe-c945-11e7-9368-241e8c8e94e4.png)

**Comment by minasmart** [comment]
There's no such thing as a product with no variant. All products have at least one variant.

Is this a js buy implementation, or is this a buy button issue?

If you're constructing a UI, you need to ensure that there's more than one variant before showing a dropdown.

**Comment by markwbrown** [comment]
js buy implementation. pretty much boilerplate. Makes sense, just wasn't clear where Default Title was coming from.

**Comment by rojakcoder** [comment]
Since there is nothing to fix for this issue, should it be closed?
