### ISSUE TITLE
fetchAllProducts only returns limited number of products

### ISSUE THREAD

**Issue by cmalven** [Shopify/js-buy-sdk#448]
Directly from the documentation for `fetchAllProducts` on http://shopify.github.io/js-buy-sdk/api/classes/ShopClient.html:

```js
client.fetchAllProducts()
.then(function(products) {
  // all products in store
});
```

That `// all products in store` comment definitely seems to imply that this will return _all_ products in the store, especially given that the function takes no params – such as `limit` or `page`.

However, my tests definitely seem to indicate that this will only ever return up to 50 products, regardless of how many products are in the store. So is this just really confusing, inaccurate documentation, or should this actually be returning all products in a store?

**Comment by ericpoon** [comment]
Have you tried the beta1.0 version? The syntax is slightly different, please see below:
```javascript
/**
   * Fetches all products on the shop.
   *
   * @example
   * client.product.fetchAll().then((products) => {
   *   // Do something with the products
   * });
   *
   * @param {Int} [pageSize] The number of products to fetch per page
   * @return {Promise|GraphModel[]} A promise resolving with an array of `GraphModel`s of the products.
   */
  fetchAll(first = 20) {
    return this.graphQLClient
      .send(productConnectionQuery, {first})
      .then(defaultResolver('shop.products'))
      .then(paginateProductConnectionsAndResolve(this.graphQLClient));
  }
```

**Comment by rizedr** [comment]
@ericpoon there is no mention in the docs that you can pass the no. of products `fetchAll` can return. Maybe docs should be updated?

**Comment by evvvritt** [comment]
Understandable there would be a limit (`1.4.0` error response says max is 250.) But why is there no way to query by page number? There also isn't any data in the response on what page you're on and how many pages there are.

[Docs](https://shopify.github.io/js-buy-sdk/ProductResource.html) could also really be improved communicating there is a limit, and the default is 20, rather than "Fetches all products on the shop." everywhere. Thanks

**Comment by rebeccajfriedman** [comment]
You can use [fetchNextPage](https://github.com/Shopify/js-buy-sdk/blob/c91742b2d2fc48c445b0b62b7c20e3f27d710682/src/client.js#L82-L95) to get a subsequent page of models.

> But why is there no way to query by page number? There also isn't any data in the response on what page you're on and how many pages there are.

We use [cursor-based](https://facebook.github.io/relay/graphql/connections.htm) pagination. You can see if there is a next page by looking at the `pageInfo` field.
