### ISSUE TITLE
[help wanted] Finish payment within the web app

### ISSUE THREAD

**Issue by ericpoon** [Shopify/js-buy-sdk#449]
Hi folks, what I want to accomplish is to complete a checkout within the web app I implement using js-buy-sdk, so customers won't have to jump to a web page (the link of the web page is provided in webUrl attribute in checkout json object).

Based on the instruction [here](https://help.shopify.com/api/sdks/sales-channel-sdk/completing-a-payment#integrate-stripe-with-your-sales-channel-app) and [here](https://help.shopify.com/api/reference/checkout#create_payment_session), I have tried to do this 

> POST https://elb.deposit.shopifycs.com/sessions

I post with credit card info, but it always returns 400 Bad Request.

Here's the format of credit card info and the headers I sen:

Body:
```
{
  "credit_card": {
    "number": "1234123412341234",
    "first_name": "ERIC",
    "last_name": "XX",
    "month": "01",
    "year": "19",
    "verification_value": "123"
  }
}
```

Header:
```
Host: https://elb.deposit.shopifycs.com
Content-Type: application/json
Accept: application/json
X-Shopify-Access-Token: e88108afd9f5014de1d0811cd750xxxx
(or X-Shopify-Storefront-Access-Token: 8eabd120cb2daf99a5eaaf0cb353xxxx
```

And it doesn't seem to work, I wonder if there's someone already figured this out or any tips about how I should work this around?

**Comment by minasmart** [comment]
This functionality is intentionally not available. We prefer you use our checkout for PCI compliance reasons, and also because you would never automatically get new features of our checkout by implementing your own off site version.
