### ISSUE TITLE
Version 0.7 Documentation

### ISSUE THREAD

**Issue by alexmilowski** [Shopify/js-buy-sdk#456]
You all need to host the documentation for version 0.7 so that those of us who haven't upgraded yet and still work on our stores.

**Comment by minasmart** [comment]
It's available in the git repo.

You can clone the repository, then:

```bash
$ git checkout v0.7.2
$ rm -rf node_modules
$ npm install
$ npm run doc:serve
```

Github doesn't give us the ability to host versioned docs pages, but git makes sure the history sticks around.
