### ISSUE TITLE
RemoveLineItems doesn't accept array, only single ID string

### ISSUE THREAD

**Issue by AbeCole** [Shopify/js-buy-sdk#457]
The implementation of removeLineItems seems incorrect. Documentation example is as follows:

```
const checkoutId = 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMTgyMTc3ODc1OTI='; // ID of an existing checkout
const lineItemIdsToRemove = [
  'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0Lzc4NTc5ODkzODQ='
];

// Remove an item from the checkout
client.checkout.removeLineItems(checkoutId, lineItemIdsToRemove).then((checkout) => {
  // Do something with the updated checkout
  console.log(checkout.lineItems); // Checkout with line item 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0Lzc4NTc5ODkzODQ=' removed
});
```

However that returns an error, if you instead provide a single product ID it will work:

`const lineItemsIdsToRemove = 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0Lzc4NTc5ODkzODQ='`

Havn't managed to find a way to pass multiple line items.

Edit: I thought you could use updateLineItems and pass an array to work around this however that method also has the same problem (documentation different from implementation).

My current solution is similar to (this is a React & Redux project, shopify function just delegates the 'action', so in this example will return `client.checkout.removeLineItems(checkoutId, itemId)`):

```
const requests = items.map(item =>
      shopify('removeLineItems', checkoutId, item.id),
);
Promise.all(requests).then(
      () => success(),
      err => failed(err),
);
```

**Comment by minasmart** [comment]
Hi there. I'm not able to reproduce this. Are you able to send me the returned `X-Request-Id` header from the network response?

**Comment by AbeCole** [comment]
@minasmart `X-Request-Id` header is `d59b6533-4548-4b1b-8d03-e84e3582191e`.

And the response reads:

`{"errors":[{"message":"Variable lineItemIds of type [ID!]! was provided invalid value","locations":[{"line":1,"column":1259}],"value":[["Z2lkOi8vc2hvcGlmeS9DaGVja291dExpbmVJdGVtLzIwMzkzNmM0NGNjMDU2ZGQ0N2I5YmFmYmVjNGQ2YjEzP2NoZWNrb3V0PTE0MjJhMmRiN2Y2MmEyYzQyYTZkZmI3MjBkM2E5MDQw","Z2lkOi8vc2hvcGlmeS9DaGVja291dExpbmVJdGVtLzZiODljYWZhYTdhMzlmOTU4MDMxYjhmNWFjY2U3YmI3P2NoZWNrb3V0PTE0MjJhMmRiN2Y2MmEyYzQyYTZkZmI3MjBkM2E5MDQw"]],"problems":[{"path":[0],"explanation":"Could not coerce value [\"Z2lkOi8vc2hvcGlmeS9DaGVja291dExpbmVJdGVtLzIwMzkzNmM0NGNjMDU2ZGQ0N2I5YmFmYmVjNGQ2YjEzP2NoZWNrb3V0PTE0MjJhMmRiN2Y2MmEyYzQyYTZkZmI3MjBkM2E5MDQw\",\"Z2lkOi8vc2hvcGlmeS9DaGVja291dExpbmVJdGVtLzZiODljYWZhYTdhMzlmOTU4MDMxYjhmNWFjY2U3YmI3P2NoZWNrb3V0PTE0MjJhMmRiN2Y2MmEyYzQyYTZkZmI3MjBkM2E5MDQw\"] to ID"}]}]}`

**Comment by minasmart** [comment]
Looking at that error, it's it's telling me that you're passing line item ids in as an array of arrays. Are you possibly wrapping your ids in an array twice?

**Comment by AbeCole** [comment]
Ah feel stupid now, I forgot I'm using the spread syntax to collect the additional arguments in my `shopify` function, so it was getting double wrapped as you said. Think I originally didn't process the error response properly as I was wondering why there was no variantId needed (when there is in updateLineItems) but it makes sense now.

Cheers for pointing that out, sorry for wasting your time.

**Comment by minasmart** [comment]
No worries! Happy to help 😄
