### ISSUE TITLE
How to model "search" for products?

### ISSUE THREAD

**Issue by gdenisov** [Shopify/js-buy-sdk#459]
We're trying to model product search via Storefront API and having trouble getting good results.

It seems that the way to search for products is to use `client.product.fetchQuery` with query parameter equaling to the user input (i.e. `query: "sneakers"`). However that does not result in the same product list as `/search?q=sneakers` on the Shopify hosted site.

We've tried playing with different sortKey and reverse settings but the results are never the same. Do you have any advice?

**Comment by minasmart** [comment]
Online store uses a different (and older) search system. It will eventually be migrated to use the same backing as this API, until then, the results will be mismatched. I would hope the results through the API are better though?

**Comment by Alligatore3** [comment]
Hi @minasmart it's a slightly different issue can you provide some [help here](https://github.com/Shopify/js-buy-sdk/issues/529#issuecomment-631942464) ?
Thanks.
