### ISSUE TITLE
cart Class v1 API

### ISSUE THREAD

**Issue by richgcook** [Shopify/js-buy-sdk#462]
Is there a cart Class as part of v1 API? I can't find anything about it on the docs? I can find a bit about checkouts but surely that's on clicking 'Checkout'... not necessarily adding products to a cart?

https://shopify.github.io/js-buy-sdk/index.html

**Comment by swalkinshaw** [comment]
This should be what you're looking for: https://shopify.github.io/js-buy-sdk/tutorial-MIGRATION_GUIDE.html#carts-checkouts
