### ISSUE TITLE
How to retrieve collections in use (that have products)

### ISSUE THREAD

**Issue by richgcook** [Shopify/js-buy-sdk#465]
When retrieving a list of collections only (to create a filter list) is it possible to only return those with products? It returns them all even when blank but there doesn't seem to be an attribute where it shows a product count to then ignore?

`client.collection.fetchQuery({first: 100, sortKey: 'TITLE'}).then(function(collections) {`

I could then loop through `collection.products` on each and get the length that way but seems a little long winded and I'm guessing extra processing?

**Comment by rebeccajfriedman** [comment]
At this time, you cannot filter by product presence. I'm curious what your use case is for having collections with no products in them.
