### ISSUE TITLE
Better type error messages

### ISSUE THREAD

**Issue by dangodev** [Shopify/js-buy-sdk#466]
Recently updated to the 1.x API, and the error messages for an incorrect API were rather confusing. This one got me stuck for a while, from `checkout.updateLineItems`:

```
Uncaught (in promise) TypeError: Cannot read property 'checkoutLineItemsUpdate' of undefined
```

That’s the result from submitting a string for `quantity` rather than a number as it was expecting. Which is very easy to do if you’re reading values from form inputs.

There’s also:

```
Uncaught (in promise) TypeError: Cannot read property 'checkoutLineItemsRemove' of undefined
```

That happens when, in the array, I submitted `[{ id: 'Zhuqp…' }]` to be consistent with the other APIs, rather than just `['Zhuqp…']` as it expected.

In all instances, the error messages seem like they’re an error in the API code rather than simply a bad value, so it took me a while to even realize I had submitted an unexpected value. The [Checkout Resource docs](https://shopify.github.io/js-buy-sdk/CheckoutResource.html) don’t always specify the expected API for each method (or when it does, it often points to an external site and you’re not sure if it’s actually referring to the same method or not).

I’d love it if the error messages were something closer to:
```
checkout.updateLineItems: expected `{ id: String, quantity: Number }`, received `{ id: String, quantity: String }`.
Please refer to https://shopify.github.io/js-buy-sdk/CheckoutResource.html#updateLineItems
```

**Comment by chrisyaxley** [comment]
Thank you so much, I was stuck on this for ages!

**Comment by markbiek** [comment]
This error was driving me crazy too.

Thanks to @dangodev , I figured out I was doing `client.checkout.removeLineItems(lineItems)` instead of `client.checkout.removeLineItems(cartId, lineItems)`
