### ISSUE TITLE
lineItem conents "quantityIncrement" and "quantityDecrement" cannot be disabled when setting them to false

### ISSUE THREAD

**Issue by ChalkyBrush** [Shopify/js-buy-sdk#468]
Using the JS Buy SDK I have the following "contents" block for my lineItem component:

          "contents": {
            "quantity": true,
            "quantityIncrement": false,
            "quantityDecrement": false,
            "quantityInput": false
          },

The desired behavior is to show the quantity of the lineitem in the cart, but not allow the user to hit the + or - buttons, or use the quantity input box to change the quantity when in the cart.

However, only the "quantity" block works; when true it shows all parts of the quantity modifier inputs, and when false it hides everything. Ideally all 4 of these "contents" objects can be true or false in any combination.

**Comment by minasmart** [comment]
Is this an issue for js buy? Or buy-button-js?

JS Buy doesn't have any ui concerns or components.

**Comment by ChalkyBrush** [comment]
I'm using <script src="http://sdks.shopifycdn.com/buy-button/0.1.34/buybutton.js"></script>

I apologize if I am using the wrong tool or on the incorrect repo

**Comment by minasmart** [comment]
That's an issue for https://github.com/Shopify/buy-button-js

**Comment by ChalkyBrush** [comment]
I am sorry and I'll go check that out. Thanks!
