### ISSUE TITLE
updateItemQuantity cart event callback executes before quantities are updated

### ISSUE THREAD

**Issue by ChalkyBrush** [Shopify/js-buy-sdk#469]
I have an event that fires when the cart is updated. When reading the contents of the cart when the event is triggered, the quantities of the items within the cart show the values BEFORE the event was triggered.

I can't think of an instance where we would want to have the values of the quantities of items before the quantity change. We should be able to see the latest data within the cart when the updateItemQuantity event fires.

**Comment by minasmart** [comment]
Is this regarding code in js buy? It sounds like you're talking about ui components.

**Comment by ChalkyBrush** [comment]
I need to move this to https://github.com/Shopify/buy-button-js, I got confused
