### ISSUE TITLE
Initialize with the cdn link in wordpress

### ISSUE THREAD

**Issue by tomkeysers** [Shopify/js-buy-sdk#471]
I'm trying to integrate some buy button functionality in an existing wordpress site, and therefore would like to skip yarn/npm and use the minified cdn source – but I'm having trouble initializing.

In v0 you can just start initializing the connection with `var shopClient = ShopifyBuy.buildClient ...` but in v1 this doesn't seem possible. The initialization `const client = Client.buildClient({ ...` now results in 'ReferenceError: Client is not defined'.

I'm feeling kinda noobie (and rightly so) – could someone get me out of the dark?

**Comment by swalkinshaw** [comment]
If you're using the CDN then it's `ShopifyBuy.buildClient` instead of just `Client`.

Our README should probably mention this.

**Comment by tomkeysers** [comment]
Thanks @swalkinshaw, that works indeed for the initialization.

However, while it also works for fetching all products, it doesn't seem to work for fetching a single one by ID. When I execute this:
```
client.product.fetch('11037068295').then((product) => {
	// Do something with the product
	console.log(product);
});
```
I get `TypeError: e is undefined` at `index.umd.min.js:25:7682`

**Comment by TomS-** [comment]
Spent a while looking for this - Your readme should specify 'ShopifyBuy', I do plan on using build tools in the future but just to get started I'm using the CDN so I don't have to create watches etc.
