### ISSUE TITLE
Retrieve Product ID from LineItem?

### ISSUE THREAD

**Issue by jazozaya** [Shopify/js-buy-sdk#478]
Hello,

I'm just migrating from v0.7 to v1.0 and had two questions. 

In my cart - I would like the title of each item in the cart to be a hyperlink back to it's product page. 
My links are in the form of "www.mywebpage.com/product/?id=MY_PRODUCT_ID"

From the checkout object, it seems I can only get the variant id, but not the product id. And I can't do a client.product.fetch() with the variant id.

Is there a way to recover the product Id from the variant Id?

------ Second question -----------

I am currently storing my checkout ID as a cookie. If a cookie is not found, then a new checkout is created. If someone completes a checkouts I am not notified since it happens on the shopify side.

What happens if I try to add product to a checkout that has already been paid for?

**Comment by jazozaya** [comment]
I have figured out the checkout issue.

I can retrieve a checkout and look at the 'completedBy' field to see if the checkout was paid for. If yes - then create a new checkout and update the cookie with the new id.

**Comment by StefanSlehta** [comment]
[This PR](https://github.com/Shopify/js-buy-sdk/pull/485) addresses the issue.
