### ISSUE TITLE
.hasNextPage returning `false` when there are still products in the store.

### ISSUE THREAD

**Issue by chrisyaxley** [Shopify/js-buy-sdk#480]
Hi,
using the following code:

```
client.fetchNextPage(this.state.products).then((nextPageOfProducts) => {
      if (nextPageOfProducts.data.node.products.pageInfo.hasNextPage) {
        const newProducts = nextPageOfProducts.model;
        newProducts.map(newProduct => this.setState(prevState => (
          { products: [...prevState.products, newProduct] }
        )));
      }
    });
```
`.hasNextPage` returns true the first time, returning the next 20 products, but the next time returns false, leaving 12 products from my store out.

Any ideas?
Thanks,
Chris

**Comment by minasmart** [comment]
With the level of detail provided I'm not sure what to suggest. Are all the products published to the sales channel?

Also, it's generally better to use the `model` attribute of the hash that is sent to the product. We stick `hasNextPage` onto the top level array, so you don't need to traverse as deeply.
