### ISSUE TITLE
Cant add items to checkout

### ISSUE THREAD

**Issue by makunomark** [Shopify/js-buy-sdk#481]
Hello people, I am just getting started with js-buy-sdk on react. Below is a snippet i am using to initialize a client, create an empty checkout and adding an item to checkout:

```js
 checkout() {
    let client = buildClient()
    console.log(client, 'client created')
    createCheckout(client).then(checkout => {
      console.log(checkout, 'checkout created')
      return addLineItems(client, checkout.id, [{ variantId: 497706303537, quantity: 1 }])
    }).then(checkout => {
      console.log(checkout, 'checkout updated')
    })
  }
```

this is the method `addLineItems`:

```js
exports.addLineItems = function addLineItems(client, checkoutId, lineItemsToAdd) {
    return client.checkout.addLineItems(checkoutId, lineItemsToAdd)
}
```

Every time I try to add an item I get this error:
`Uncaught (in promise) TypeError: Cannot read property 'checkoutLineItemsAdd' of undefined`

What could I be doing wrong? PS. I have read the documentation and I still cant seem to figure this out.

`shopify-buy` version: 1.0.2

Thank you in advance.

**Comment by makunomark** [comment]
So sorry for this. I realized after 3 days that I was passing the wrong id :-(

**Comment by Agent2222** [comment]
Experiencing the same problem. Which id did you end up using?
