### ISSUE TITLE
null response, or "function cannot be called on undefined" (client.product)

### ISSUE THREAD

**Issue by thesublimeobject** [Shopify/js-buy-sdk#483]
I'm using 1.0.2 and building the client like so,

`
let test = Client.buildClient({
    storefrontAccessToken: 'TOKEN',
    domain: 'DOMAIN_NAME',
})

test.product.fetchAll().then(products => console.log(products)
`

And every time I seem to get an empty object or a function is undefined, or something similar. If i just return the client itself, it returns a GraphQL query, as does client.product. But for some reason if I then call fetchAll() on that, it claims that client.product is undefined and it can't call that method on the object (or whatever the language is). I found a working example with the old API, but I can't seem to find a good one with the new one, plus most of the docs on your sites are the old API as well. I did find the right API Docs, but either way, you all might want to update that. 

Any ideas why I keep getting these kinds of responses?

**Comment by minasmart** [comment]
Do you know if your private ducts are published to the correct channel?

**Comment by thesublimeobject** [comment]
@minasmart They are, I checked that awhile back as that was the first issue I ran into. I just re-configured and it started working, but it's very odd that sometimes I'm getting it to work and sometimes it's failing with nearly identical functions. Truly the only difference between the first try and second try was I returned an object { products } instead of just returning the result itself.

**Comment by minasmart** [comment]
This is hard to debug or reproduce on our end. Can you provide a shop name and/or a request id(X-Request-Id response header) from a failed request?

**Comment by thesublimeobject** [comment]
Hold on, give me like 24 hours. I've been flipping back and forth between using a couple of different architectures for this project and I want to make 100% sure it's not an error in _my_ system now that I have it working again (it's been going back and forth). I'll close the issue if I figure it out. Thanks for your quick response!

**Comment by thesublimeobject** [comment]
I think I have this working now, but thank you for the quick response anyway. I would advise, if possible, to put the correct documentation in the correct places, because it did take me quite awhile to find all of the right resources. Thanks!
