### ISSUE TITLE
Can't add to cart (change lineitems) after adding discount code

### ISSUE THREAD

**Issue by oscarpan** [Shopify/js-buy-sdk#486]
I noticed an issue with the storefront api, I noticed on some of the checkouts, particularly on the checkouts with a discount code, changing the quantity on a line item is not possible and doesn't return an error. When I remove the discount code then try adding to the quantity, it works. Is there a way to fix this in the API?

For example with this mutation to change lineitem quantity to 4, it comes back as 3 without any errors:
X-Request-Id:1e87c8e8-b133-4a65-973f-daec00bc86ab

@minasmart Are you able to help with this?

**Comment by oscarpan** [comment]
Looks like #495 fixed this issue as well -- closing...

**Comment by isaachinman** [comment]
@oscarpan Are you saying you were able to add a discount code via this SDK? Do you mind pasting some example boilerplate?
