### ISSUE TITLE
Avoid specific JSON attributes - Product JSON data

### ISSUE THREAD

**Issue by abhilash29** [Shopify/js-buy-sdk#487]
`{
  "__typename": "Product",
  "id": "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzIyODA5MjAxODcxNw==",
  "createdAt": "2017-10-23T11:05:40Z",
  "updatedAt": "2018-03-07T08:25:38Z",
  "descriptionHtml": "Aliquam optio qui. Eum dolores magnam fugiat aut quia. Explicabo et eaque perferendis molestias mollitia harum fuga ipsa.",
  "description": "Aliquam optio qui. Eum dolores magnam fugiat aut quia. Explicabo et eaque perferendis molestias mollitia harum fuga ipsa.",
  "handle": "managed-grass-roots-tasty-granite-table",
  "productType": "Games",
  "title": "Managed Grass-roots Tasty Granite Table",
  "vendor": "Ryan, Crist and Koelpin",
  "tags": [
    {
      "value": "data-generator",
      "type": {
        "name": "String",
        "kind": "SCALAR"
      }
    }
  ],
  "publishedAt": "2018-03-07T08:25:38Z",
  "onlineStoreUrl": null,
  "options": [
    {
      "id": "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0T3B0aW9uLzM2NTQ0NDIzNTI5Mw==",
      "name": "Title",
      "values": [
        {
          "value": "Soft mint green - fz7-24s",
          "type": {
            "name": "String",
            "kind": "SCALAR"
          }
        }
      ],
      "type": {
        "name": "ProductOption",
        "kind": "OBJECT",
        "fieldBaseTypes": {
          "name": "String",
          "values": "String"
        },
        "implementsNode": true
      }
    }
  ],
  "images": [],
  "variants": [
    {
      "id": "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zMzczOTAzNjQyNjUz",
      "title": "Soft mint green - fz7-24s",
      "price": "116.00",
      "weight": 0,
      "available": true,
      "sku": "",
      "compareAtPrice": null,
      "image": null,
      "selectedOptions": [
        {
          "name": "Title",
          "value": "Soft mint green - fz7-24s",
          "type": {
            "name": "SelectedOption",
            "kind": "OBJECT",
            "fieldBaseTypes": {
              "name": "String",
              "value": "String"
            },
            "implementsNode": false
          }
        }
      ],
      "product": {
        "id": "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzIyODA5MjAxODcxNw==",
        "images": [],
        "type": {
          "name": "Product",
          "kind": "OBJECT",
          "fieldBaseTypes": {
            "createdAt": "DateTime",
            "description": "String",
            "descriptionHtml": "HTML",
            "handle": "String",
            "id": "ID",
            "images": "ImageConnection",
            "onlineStoreUrl": "URL",
            "options": "ProductOption",
            "productType": "String",
            "publishedAt": "DateTime",
            "tags": "String",
            "title": "String",
            "updatedAt": "DateTime",
            "variants": "ProductVariantConnection",
            "vendor": "String"
          },
          "implementsNode": true
        }
      },
      "type": {
        "name": "ProductVariant",
        "kind": "OBJECT",
        "fieldBaseTypes": {
          "available": "Boolean",
          "compareAtPrice": "Money",
          "id": "ID",
          "image": "Image",
          "price": "Money",
          "product": "Product",
          "selectedOptions": "SelectedOption",
          "sku": "String",
          "title": "String",
          "weight": "Float"
        },
        "implementsNode": true
      },
      "hasNextPage": false,
      "hasPreviousPage": false,
      "variableValues": {
        "id": "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzIyODA5MjAxODcxNw=="
      }
    }
  ],
  "type": {
    "name": "Product",
    "kind": "OBJECT",
    "fieldBaseTypes": {
      "createdAt": "DateTime",
      "description": "String",
      "descriptionHtml": "HTML",
      "handle": "String",
      "id": "ID",
      "images": "ImageConnection",
      "onlineStoreUrl": "URL",
      "options": "ProductOption",
      "productType": "String",
      "publishedAt": "DateTime",
      "tags": "String",
      "title": "String",
      "updatedAt": "DateTime",
      "variants": "ProductVariantConnection",
      "vendor": "String"
    },
    "implementsNode": true
  }
}`

As seen in the above JSON response, I don't want the following fields in the JSON response.
 like `hasPreviousPage`, `hasNextPage`, `type`.  I only want the product values based data. 

Is there a way to do that?

**Comment by minasmart** [comment]
these values are necessary for pagination to function properly. If you only want specific fields, I recommend you access the storefront API directly, using whichever GraphQL client makes sense for you. The API is documented [here](https://help.shopify.com/api/storefront-api/reference)
