### ISSUE TITLE
Performance Decrease

### ISSUE THREAD

**Issue by rizedr** [Shopify/js-buy-sdk#488]
I am currently updating a custom shop built with React to the latest version of `js-buy-sdk` and, compared to v0.5, I am seeing some performance decrease.

Look at this measurement comparisons:
![image](https://user-images.githubusercontent.com/3323353/37257639-f8e272f6-2574-11e8-88c7-b6f91020d78f.png)

Am I doing something wrong or is there a way to increase performance with this version?

**Comment by FistMeNaruto** [comment]
GraphQL queries such as adding to cart, modifying quantity take ~1.5 second to complete on first action and ~1 second on subsequent actions. This isn't a connection issue, as most of the time is spent on waiting for first byte:
![screenshot from 2018-06-18 03-16-53](https://user-images.githubusercontent.com/13431677/41513501-4280936a-72a6-11e8-9f29-7038a59efbc1.png)
This results in significant input lag and hopefully this can be improved.

**Comment by tentonaxe** [comment]
We're experiencing this problem as well.

![image](https://user-images.githubusercontent.com/370072/53431313-e546d880-39b5-11e9-8517-51a50750b40a.png)

All of the above calls are caused by various checkout interactions, such as adding to checkout, changing quantity, removing from checkout, etc. It's too slow to use directly to the point where we're considering only using this process when the user clicks checkout, before we send them to the shopify checkout.

**Comment by arobbins** [comment]
Experienced the same issue ... maybe found a solution.

I'm using the `client.product.fetchQuery` method to fetch products. Before, I was setting a `pageSize` param to the size I wanted. Using `10` would always load pretty quick. However setting this to `250` would literally take 15 seconds to load. `100` would take about 5 seconds.

I replaced `pageSize` instead with `first` (per the docs) and the TTFB immediately dropped from 15 seconds to > 1.5 second for a page size of 250.

What's interesting is that `pageSize` worked at all. Perhaps there was an expensive redirect happening?

**Comment by rebeccajfriedman** [comment]
Closing this as stale. If you are still experiencing a performance degradation, please open a new ticket with updated performance concerns, and we can look into those.

**Comment by domnantas** [comment]
Coming back to this after 2 years - not much has improved. TTFB is still 500ms - 1000ms on simple queries like adding a product to cart or changing quantity.
