### ISSUE TITLE
Number of Products Returned by collection.fetchWithProducts

### ISSUE THREAD

**Issue by rizedr** [Shopify/js-buy-sdk#489]
If you want to get the products that a collection holds you can use the `fetchWithProducts` method:
```javascript
client.collection.fetchWithProducts('Xk9lM2JkNzFmNzIQ4NTIY4ZDFiZTUyZTUwNTE2MDNhZjg==').then((collection) => {
  // Do something with the collection
})
```

This will return onto the `collection` object a 20 products array. There is **no way you can specify the number of products this method should return**.

I propose to add an optional param after `id`, called `pageSize` as the [`product.fetchAll`](http://shopify.github.io/js-buy-sdk/product-resource.js.html#line32) has.

**Comment by aaronzdavis** [comment]
Would love to see this update as well.

**Comment by Highspeed7** [comment]
Thirded! Can we get a response on this please? At least acknowledgement

**Comment by rebeccajfriedman** [comment]
Hi folks. This is an open source repo! Feel free to make a PR to contribute back this change.

**Comment by FutureHits3Dev** [comment]
Anything on this?

**Comment by Highspeed7** [comment]
Shopify just wants us to pay for their "Experts" instead of fixing broken stuff... How nice. Looks like I'll be looking for an alternative to Shopify, if this is how they treat their customers.

**Comment by rebeccajfriedman** [comment]
We have released a new version that includes this fix. Read more about it in the [CHANGELOG](https://github.com/Shopify/js-buy-sdk/blob/master/CHANGELOG.md).
