### ISSUE TITLE
Redirect to non existing storefront when following checkout url

### ISSUE THREAD

**Issue by maciekpaprocki** [Shopify/js-buy-sdk#492]
I have issue that's quite hard to reproduce. It happened already to three different users all based in USA and using Safari. When I try to reproduce that using proxy everything seems to go as planned, so there need to be other factors.

What is happening:

When user goes to cart address returned by:
`api.fetchCart(cart_id).then((cart)=>{cart.checkoutUrl})` 
they seem to be redirected to storefront and as my website doesn't have one he is shown 'this website doesn't have a store yet. If you are store owner please log in here'. 

Fortunately one of the users having this problem managed to record the error:
https://palmstudios.co.uk/app/uploads/2018/03/video-1521048829.mp4

Am I missing something obvious here?

Obviously for me is important that:
1. User would not get redirected at all, 
2. If user is redirected he shouldn't go to storefront but to my website. 

Website in question is:
https://palmstudios.co.uk/

**Comment by lloydstubber** [comment]
Bumping this. I'm almost certain it has something to do with my issue here regarding cookies/Safari: https://github.com/Shopify/buy-button-js/issues/456

(Hi Maciej 😉)

**Comment by darth-weber** [comment]
Hey, would you have an update on this case?  
The merchant can't sell to their customers who are using Safari.

Greetings, 
Markus

**Comment by lloydstubber** [comment]
Hey @maciekpaprocki / @darth-weber I've just received an email from support saying this is fixed. Tested it on my end and it's working perfectly in Safari on Mac and iOS.

**Comment by maciekpaprocki** [comment]
sorry. Missed that. I did not have any complains for some time, so I assume the issue is fixed. Thanks.
