### ISSUE TITLE
Cannot change item quantity in cart

### ISSUE THREAD

**Issue by agos** [Shopify/js-buy-sdk#495]
The mutation I was using (`checkout.updateLineItems`) has stopped changing the quantity of the items. They return with the quantity unchanged, but with no errors. Issue #486 might be related?

For example, see X-Request-ID: 69c4f19a-23b9-423b-b3b0-fcd84c5ec9fa

**Comment by sturoid** [comment]
We are getting the same thing but with any update and delete functions. I tried updating the library but it doesn't help.

**Comment by Jimtattersall** [comment]
We are also getting this, we've tried contacting support several times but to no avail. This has taken down 5 of our stores. All stores were working fine until about 7 hrs ago. Seems mad that with this being an issue for almost a day that it's not even reached their status page.

**Comment by minasmart** [comment]
@agos I'm not seeing an error in that request. I'm seeing two line items being sent, both with the quantity of two. Can you verify that the response isn't echoing the supplied input?

**Comment by sturoid** [comment]
@Jimtattersall same here. Our main store is basically non-operational.

**Comment by sturoid** [comment]
@minasmart The response back for us is just the exact cart data that gets sent. I'm guessing it's the same thing he is seeing.

**Comment by minasmart** [comment]
If the response is the cart data that's sent, then it's working correctly? If you send `quantity: 2` on a line item, it should respond with `quantity: 2`.

The only way this is an error is if the data doesn't match. Can you show me the request and response?

**Comment by minasmart** [comment]
Or even send me a shop where things are broken and I can inspect the network requests?

**Comment by Jimtattersall** [comment]
@minasmart a few examples:

**Comment by sturoid** [comment]
Our store is weboost.com. You can check that as well. We are storing the cart in local storage under weboost_cart.

**Comment by minasmart** [comment]
Thanks for the examples. I've engaged our checkout team.

**Comment by Jimtattersall** [comment]
Thanks @minasmart super appreciated.

**Comment by minasmart** [comment]
I think we've got a fix that should be rolling out in the next hour.

**Comment by agos** [comment]
it's now working for us. Thanks @minasmart for the quick turnaround time (and sorry for the lack of details in the issue), and thanks to everybody who chimed in with additional data
