### ISSUE TITLE
Update checkout object's customAttributes using mutations - Express JS

### ISSUE THREAD

**Issue by abhilash29** [Shopify/js-buy-sdk#496]
I'm currently using Express JS. I've successfully integrated the JS buy SDK and I'm successfully able to create/update/delete checkouts and their lineItems.
I also managed to create customAttributes during checkout creation.
However, what I'm not able to figure out is the correct syntax/code to use mutations as mentioned in [checkoutAttributesUpdate][1] link .
Unfortunately, there doesn't seem to be an out of the box function to do this as in case of `client.checkout.addLineItems`.

This is how I added customAttributes.

    const input = {
        customAttributes: customAttributes
    };
    
    client.checkout.
    
    client.checkout.addLineItems(checkoutId, lineItemsToAdd).then((checkout) => {
        resolve({
            status: "success",
            statusMessage: "Items added to cart successfully",
            data: checkout
        })
    }).catch(function(error) {
        reject({
            status: "failure",
            statusMessage: error.message
        })
    });

  [1]: https://help.shopify.com/api/storefront-api/reference/mutation/checkoutattributesupdate#interactive-example

**Comment by minasmart** [comment]
You can do this during `checkout.addLineItems` or `checkout.updateLineItems`.

The input shapes for those mutations are reflected [here for updating](https://help.shopify.com/api/storefront-api/reference/input_object/checkoutlineitemupdateinput) and [here for adding](https://help.shopify.com/api/storefront-api/reference/input_object/checkoutlineitemupdateinput).

**Comment by abhilash29** [comment]
I was talking about the customAttribute array that is located inside the root of `checkout` object, not inside lineItems.
Please check my edited question. @minasmart
