### ISSUE TITLE
Providing or updating type definitions for TypeScript

### ISSUE THREAD

**Issue by saitho** [Shopify/js-buy-sdk#497]
Hey there,

I'm trying to move my JavaScript implementation to TypeScript.
There are type definitions in the DefinitelyTyped project for an older version of this package.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/shopify-buy/index.d.ts

It would be great if you could provide typings with the package or update the typings on the DefinitelyTyped project. I'd totally do that, but I don't know the structure as I only started working with the SDK yesterday. ^^

**Comment by minasmart** [comment]
Those definitions aren’t maintained by us. Sorry!
