### ISSUE TITLE
Checkout LineItems Order

### ISSUE THREAD

**Issue by rizedr** [Shopify/js-buy-sdk#501]
Currently the order of [LineItems](https://help.shopify.com/api/storefront-api/reference/object/checkoutlineitemconnection) in the Checkout seems to be ad-hoc which creates a bad UX.

If user adds Product A, then Product B & then Product C, he would expect to see them in Checkout in that order. However, he sees something like: Product C, Product A, Product B which makes him lose track of what product is what.

Furthermore, in the shopify checkout page, the products seem to be in the order the user would expect. Can we do the same for the SDK?

**Comment by minasmart** [comment]
This is a factor of the API andnlt the SDK itself. It’s a known issue and we’re tracking it internally. 

Thanks!!

**Comment by rizedr** [comment]
Localstorage workaround solution it is then.

Thank you @minasmart for the prompt reply. Feels bad that there is no `AddedAt` property for lineItems.

**Comment by jordan-sowers** [comment]
Any updates here? Thanks!

**Comment by jordan-sowers** [comment]
Hi Mina, 

Is there an update to this issue? I'm running in to the same problem. 

+1 for the AddedAt property!

**Comment by rebeccajfriedman** [comment]
I recommend storing the line items locally, and using the [replaceLineItems](https://github.com/Shopify/js-buy-sdk/blob/master/src/checkout-resource.js#L204-L223) mutation instead. The mutations `addLineItems ` / `removeLineItems ` / `updateLineItems` are deprecated, and so we are unlikely to update the functionality.

**Comment by rizedr** [comment]
The way I went around it was to avoid the sdk itself and implement graphQL in my client with my custom queries:

```javascript
export const QUERY_CHECKOUT = gql`
  query ($id: ID!) {
    node(id: $id) {
      id
      ... on Checkout {
        ...CheckoutFragment
      }
    }
  }
  ${CheckoutFragment}
`;
```
Where `CheckoutFragment` is:
```javascript
const CheckoutFragment = gql`
  fragment CheckoutFragment on Checkout {
    id
    webUrl
    completedAt
    subtotalPrice
    totalTax
    totalPrice
    lineItems (first:250) {
      pageInfo {
        hasNextPage
        hasPreviousPage
      }
      edges {
        node {
          id
          title
          quantity
          variant {
            id
            title
            image {
              id
              src
            }
            price
            product {
              handle
              images(first: 1) {
                pageInfo {
                  hasNextPage
                  hasPreviousPage
                }
                edges {
                  cursor
                  node {
                    id
                    src
                    altText
                  }
                }
              }
            }
          }
        }
      }
    }
  }
`;
```

**Comment by etabard** [comment]
Hi there,
This issue still seems to exist. You said this issue was tracked internally back in 2018. Do you have any news ? 

Thanks a lot for your help
