### ISSUE TITLE
graphQLClient.fetchAllPages: null is not an object (evaluating 'checkout.lineItems')

### ISSUE THREAD

**Issue by paulisloud** [Shopify/js-buy-sdk#503]
Hello,

I am receiving the following error, thrown by graphQLClient, as implemented by the Shopify JS Buy SDK. Here is the code which fails:

     */
    value: function fetch(id) {
      var _this2 = this;
      return this.graphQLClient.send(query$11, { id: id }).then(defaultResolver('node')).then(function (checkout) {
        return _this2.graphQLClient.fetchAllPages(checkout.lineItems, { pageSize: 250 }).then(function (lineItems) {
          checkout.attrs.lineItems = lineItems;
          return checkout;
        });
      });

Specifically the call to fetchAllPages.

The error happens only occasionally, say 20 times / day, vs on every page load

I'm not sure what part of my implementation of the JS Buy SDK (v1.2.0) is calling this, but it is a result of a call to: https://mysite.myshopify.com/api/graphql

Any idea what could be causing this sporadically?

**Comment by paulisloud** [comment]
So I believe I've narrowed this down to this file:
`/src/checkout-resource.js`

In particular:

<pre>
  fetch(id) {
    return this.graphQLClient
      .send(checkoutNodeQuery, {id})
      .then(defaultResolver('node'))
      .then((checkout) => {
        return this.graphQLClient.fetchAllPages(checkout.lineItems, {pageSize: 250}).then((lineItems) => {
          checkout.attrs.lineItems = lineItems;
          return checkout;
        });
      });
  }
</pre>

However, what I can't grok is why checkout would be null after the query. Here's the relevant setup on my end:

<pre>
var config = {
  domain: 'mysite.myshopify.com',
  storefrontAccessToken: '1234567890'
};

client = Client.buildClient(config);

let checkoutId = localStorage.getItem('checkoutId');
if(checkoutId) {
  console.log('There was an existing cart');
  // We have a checkoutId, let's see if it has been completed
  client.checkout.fetch(checkoutId).then(function(remoteCart) {
    console.log('fetched checkout');
    // The checkout was not completed, grab its contents
    if (remoteCart.completedAt === null) {
      cart = remoteCart;
      cartLineItemCount = cart.lineItems ? cart.lineItems.length : 0;
      prepareProductPage();
    // The checkout was completed, remove the localStorage item
    // Start from scratch
    } else {
      localStorage.removeItem('checkoutId');
      createNewCart();
    }
  });
  // There was no checkoutId, so we'll start from scratch
} else {
  console.log('There was an existing cart');
  createNewCart();
}
</pre>

Given that we're checking for an existing checkoutId, why would `checkout.lineItems` ever be null, since we're in the callback of a resolved graphQL query?

And it's actually happening about 100 times / day.

**Comment by minasmart** [comment]
Is the checkout null? Checkouts expire. An ID isn’t guaranteed to exist.

**Comment by paulisloud** [comment]
Well we don't know if it's null until we fetch the checkout. And it looks like the SDK doesn't allow for an expired cart, if I'm not mistaken. For instance `this.graphQLClient.fetchAllPages(checkout.lineItems` is from your library, so by the time I get the result from `fetch`, it may have already errored out.

**Comment by minasmart** [comment]
Have you tried throwing a `.catch` on the promise and seeing what error comes out?

**Comment by paulisloud** [comment]
Yeah don't know why I didn't think of that. Will deploy that solution and update this thread once I have data.

**Comment by paulisloud** [comment]
No errors in the last two hours, this `.catch` appears to have been the ticket.

Never occurred to me previously that checkouts could expire. Is this documented and I simply missed it?

Will update this thread with more data tomorrow if it's still open.

**Comment by paulisloud** [comment]
Here's what this part of my cart looks like now, in case anyone else runs in to this:

<pre>
var config = {
        domain: 'mysite.myshopify.com',
        storefrontAccessToken: '1234567890'
      };

      client = Client.buildClient(config);

      let checkoutId = localStorage.getItem('checkoutId');
      if(checkoutId) {
        console.log('There was an existing cart');
        // We have a checkoutId, let's see if it has been completed
        client.checkout.fetch(checkoutId)
          .then(function(remoteCart) {
            console.log('fetched checkout');
            // The checkout was not completed, grab its contents
            if (remoteCart.completedAt === null) {
              cart = remoteCart;
              cartLineItemCount = cart.lineItems ? cart.lineItems.length : 0;
              prepareProductPage();
            } else {
              // The checkout was completed, remove the localStorage item
              // Start from scratch
              localStorage.removeItem('checkoutId');
              createNewCart();
            }
          })
          .catch((error) => {
            // While the cart ID exists, the checkout has expired.
            // So we need to clear out localStorage and create a new cart.
            console.log('The cart must have been expired', error);
            localStorage.removeItem('checkoutId');
            createNewCart();
          })
        // There was no checkoutId, so we'll start from scratch
      } else {
        console.log('There was no existing cart');
        createNewCart();
      }

</pre>

**Comment by dsshap** [comment]
@minasmart how long does a checkout exist for? I am seeing variables length of time before they expire. 

Wouldn't everyone want the checkout to exist for a long time? If a customer returns, they will expect their cart to be full of items they previously added?

**Comment by minasmart** [comment]
The brief answer is, we delete checkouts / carts that were created more than 3 months ago, and that haven't been touched in a week. This, however, may change. We try to base our retention based on what makes sense in our system, what data's been added to the checkout, and what shows the possibility of converting.

It's best if you build your app to handle the case that the checkout may not exist. If this retention policy doesn't suit you, you can always persist the cart data to local storage or something, and recreate the checkout if it's been swept up.

**Comment by dsshap** [comment]
@minasmart I am sometimes seeing errors from your servers after only an hour of a cart being created...

I even added a retry to make sure the cart is actually missing. It still returns null.

**Comment by dsshap** [comment]
@minasmart this is happening in production.

**Comment by minasmart** [comment]
It depends what data has been set on the checkout. Are these checkouts with line items and customer data?

**Comment by dsshap** [comment]
@minasmart line items, no customer data yet.

**Comment by dsshap** [comment]
@minasmart any updates on this?

**Comment by minasmart** [comment]
I can't really dig into this without a request id or a checkout Id and shop, or even a code sample. In all tests i can run locally, the info I gave above is accurate. I'll need more to go on to validate this behaviour and figure out what's going on.

**Comment by dsshap** [comment]
@minasmart Had it happen again.

Details:
```
ShopId: 26434130
Request-Id: fc27d648-fd88-4dc5-b626-c9bfe08e958e
```
response: `{"data":{"node":null}}`

**Comment by dsshap** [comment]
@minasmart any updates on this?

It is important to us to get this resolved asap as we are seeing this in production.

**Comment by minasmart** [comment]
It looks like you have two API clients, each with its own channel, and you're querying for a checkout created on one API client with the other API client, which our security doesn't allow.

**Comment by dsshap** [comment]
@minasmart - good catch, the way I was saving the checkout was being overwritten by different environments.

**Comment by mahaboobkhan29** [comment]
Hi,
anyone please tell me how to Retrieve a cart by using graphQLClient 

iwant to change the below code call into graphQLClient method 

cart(id:"Z2lkOi8vc2hvcGlmeS9DYXJ0L2QzNTNhODQxYjQ1Y2VmYjY3ZTQ1NjdiZGUzMzU4MjFh") {
    id
    createdAt
    updatedAt
    lines(first:10) {
      edges {
        node {
          id
          quantity
          merchandise {
            ... on ProductVariant {
              id
            }
          }
          attributes {
            key
            value
          }
        }
      }
    }
    attributes {
      key
      value
    }
    estimatedCost {
      totalAmount {
        amount
        currencyCode
      }
      subtotalAmount {
        amount
        currencyCode
      }
      totalTaxAmount {
        amount
        currencyCode
      }
      totalDutyAmount {
        amount
        currencyCode
      }
    }
    buyerIdentity {
      email
      phone
      customer {
        id
      }
      countryCode
    }
  }
}
