### ISSUE TITLE
Cannot read property 'checkoutCreate' of undefined 

### ISSUE THREAD

**Issue by abhilash29** [Shopify/js-buy-sdk#507]
![screenshot at apr 10 15-49-14](https://user-images.githubusercontent.com/1309199/38551438-c19c9d84-3cd6-11e8-94ef-c6b81526736b.png)

I've successfully managed to created StoreFrontAccessToken through APIs. However, when I try to  create a checkout `client.checkout.create(input).then((checkout)`, I get the error `Cannot read property 'checkoutCreate' of undefined `

**Comment by JesseTheDev** [comment]
Hey i'm getting the same thing, only when i'm using an input. Did you find anything out here?

**Comment by abhilash29** [comment]
@JesseTheDev In my case, the problem was with the way I was adding the custom attributes. This is what I did to fix it.

```
const input = {
    customAttributes: [{
        key: 'somekey',
        value: 'somevalue'
    }]
};
```
