### ISSUE TITLE
StorefrontAccessToken Issue

### ISSUE THREAD

**Issue by abhilash29** [Shopify/js-buy-sdk#509]
If I create a private app through admin dashboard and grant store front privileges to it, then the store front API token that is generated works completely fine with my app. I get all the products when I call `client.product.fetchAll()` function

However, when I generate that same token through the API (which gives me an object like below), I get an **internal server error** as an exception while calling `client.product.fetchAll()` function.

```
{
  "storefront_access_token": {
    "access_token": "fab794b3bff3928e5fc42f2788542629",
    "access_scope": "unauthenticated_read_product_listings",
    "created_at": "2018-03-21T11:42:36-04:00",
    "id": 1053727608,
    "title": "Test"
  }
}
```

**Comment by minasmart** [comment]
I don't think I can give a full answer here, but you may be missing scopes [as documented here](https://help.shopify.com/api/reference/storefrontaccesstoken). The private app access tokens are granted all of those scopes.

Additionally, I'd need to see your config to ensure that your api url and access token all match.

**Comment by abhilash29** [comment]
I've used all the scopes. `unauthenticated_read_content,unauthenticated_read_product_listings,unauthenticated_read_collection_listings,unauthenticated_write_checkouts,unauthenticated_read_checkouts,unauthenticated_write_customers,unauthenticated_read_customers

![screenshot at apr 12 09-05-36](https://user-images.githubusercontent.com/1309199/38655151-b33b4c30-3e30-11e8-831c-436956fd0f3e.png)
`

**Comment by abhilash29** [comment]
API URL would be `https://quinto-test-store-part-2.myshopify.com/admin/storefront_access_tokens.json`

Note: The current access token (`5081277d08e51ea8d6418e5d220d543d`) that works, is the one that I created from the admin dashboard. 

Other than this, the remaining access tokens that were generated through the API do not work.
![screenshot at apr 12 09-34-34](https://user-images.githubusercontent.com/1309199/38655910-babb483a-3e34-11e8-852c-6fa5cb41bf1f.png)

**Comment by swalkinshaw** [comment]
hey @abhilash29 the issue here is that the app you are using to create the storefront access token is *not* a channel. The Storefront API only works in the context of a sales channel app.

We've recently updated our docs to include that requirement: https://help.shopify.com/api/storefront-api/getting-started#authentication

(see "Via REST API")

**Comment by abhilash29** [comment]
In that case, why does the storeFrontAccess token work if it's created via. the admin GUI?

**Comment by swalkinshaw** [comment]
When you enable Storefront API access for a private app, we automatically make that app a sales channel.

**Comment by emilioMoreira** [comment]
@swalkinshaw - do you have an example of calling the `/admin/storefront_access_tokens.json` endpoint? I'm trying to use Node.js & express and am getting the following error...

`TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type object`

`
    const shop = req.query.shop;

    if (shop) {
        /*#################### START CALL TO DESIRED FUNCTION #################### */
        const accessToken = "f24c1215650febf0992a49f582930d7a";
        const storefrontTokenRequestUrl = "https://" + shop + "/admin/storefront_access_tokens.json";
        const shopRequestHeaders = {
            'X-Shopify-Access-Token': accessToken,
        };
        console.log("QT/shopify/callback :: shopRequestHeaders <" + JSON.stringify(shopRequestHeaders) + ">");

        const storefrontTokenPayload = {
            "storefront_access_token": {
                title: "Test",
                access_scope: "unauthenticated_read_product_listings"
            }
        };
        console.log("QT/shopify/callback :: storefrontTokenPayload <" + JSON.stringify(storefrontTokenPayload) + ">");

        request.post(storefrontTokenRequestUrl, {
                json: storefrontTokenPayload,
                headers: shopRequestHeaders
            })
            .then((storefrontResponse) => {
                console.log("QT :: storefrontResponse.access_token <" + storefrontResponse.access_token + ">");
                console.log("QT :: storefrontResponse.access_scope <" + storefrontResponse.access_scope + ">");
                console.log("QT :: storefrontResponse.created_at <" + storefrontResponse.created_at + ">");
                console.log("QT :: storefrontResponse.title <" + storefrontResponse.title + ">");
                res.end(storefrontResponse);
            })
            .catch((error) => {
                console.log("QT :: ERROR in Promise!!! " + error);
                //DEL: res.status(error.statusCode).send(error.error_description);
                if (error.statusCode >= 100 && error.statusCode < 600) {
                    res.status(error.statusCode);
                } else {
                    res.status(500);
                }
                res.end("Something BAD happened!!!\n" + error);
            });
        /*#################### END CALL TO DESIRED FUNCTION ####################*/
    } else {
        res.status(400).send('Missing \'shop\' parameter');
    }
`

**Comment by Rathnakreeswaran** [comment]
For me this api /admin/storefront_access_tokens.json  gives "internal server error".how to generate the stront front end access token
