### ISSUE TITLE
fetchAll() returning only 20 items

### ISSUE THREAD

**Issue by abhilash29** [Shopify/js-buy-sdk#510]
Is there a way to retrieve all products in a store and not just the first 20?

**Comment by minasmart** [comment]
products are intentionally paginated. fetching all in one request is too expensive for most shops, so there's a page size limit. [fetchAll takes a pageSize parameter](https://shopify.github.io/js-buy-sdk/ProductResource.html#fetchAll) but your performance may vary depending on the number of variants and images that you have on each product.

**Comment by thislogancall** [comment]
I can understand the reasoning behind this, but I believe there is a case when retrieving all products would be useful. For instance, I'm looking into building storefronts with React Static (a static site generator). Ideally, getting all of the products during a build of the site would actually cause fewer queries in the long run as the data is stored in JSON during the build. With this setup, Shopify is only queried during a build, not for each time someone visits a storefront.

Still, I can see why you have this limited, and possibly the best approach with a static site generator is just to go through each "page" of product data to get all products during the build.

**Comment by chrisworman-pela** [comment]
@minasmart I understand that fetching all products is too expensive for most shops, but then why is this method called `fetchAll`?  I would expect `fetchAll` to fetch page 1, then page 2, etc., then finally collate the results.

What about adding an optional parameter to follow pages and collate: `fetchAll(first = 20, followAndCollate=false)`, or something similar?  Either that or rename the method to `fetchPage`.
