### ISSUE TITLE
Is it possible to create an app that allows crypto payments on shopify?

### ISSUE THREAD

**Issue by Andriy-Kulak** [Shopify/js-buy-sdk#513]
Hi Team!

I am looking into if it's possible to create a shopify app or that allows customers to pay with cryptocurrency such as bitcoin, litecoin, ethereum, etc. Is this something that feasible at the moment with current Shopify API and third party developer access?

Thanks!
Andriy

**Comment by Cam** [comment]
This looks like something more suited to the forums https://ecommerce.shopify.com/c/shopify-apis-and-technology

**Comment by Andriy-Kulak** [comment]
Ahh I was looking in the wrong place. I was looking in the apps sections, here and the api. But it appears there are already payment providers working with shopify such as coinbase.
https://help.shopify.com/manual/payments/alternative-payments/cryptocurrency
