### ISSUE TITLE
Retrieve multiple Products and Collections by ID [Feature]

### ISSUE THREAD

**Issue by EricNetsch** [Shopify/js-buy-sdk#516]
Please add the GraphQL "nodes" query to this SDK. This allows the SDK to retrieve multiple nodes by ID during the same network call.
Most of the other shopify storefront SDK's support this... 

Let me know if I can provide clarification but this should be a very simple addition.

**Comment by EricNetsch** [comment]
@minasmart 
Any thoughts on this? If this isn't a priority, my team can look deeper into submitting PR.
Thanks,

**Comment by EricNetsch** [comment]
@minasmart Thanks for the note. I am referring to retrieving multiple products and collections by Ids. This is something the other Storefront SDK's have available so in my opinion, should be added to this one as well.

The end result would look like this:

```
client.product.fetchWithIds([productId]).then((products) => {
  // Do something with the products
  console.log(products);
});

client.collection.fetchWithIds([collectionId]).then((collections) => {
  // Do something with the collections
  console.log(collections);
});
```

The nodes query does specify an object type when using it so it would be a very simple addition. See example:

```
nodes(ids: [productIds]) {
    ... on Products {


     }
}
```

**Comment by minasmart** [comment]
Cool! This sounds good. I can work out the add.

Just a note about GraphQL though: A fragment on an interface does not specify the type. It specifies the fields to include if that type is present in the response. You could still send in mixed IDs, and you would simply get nothing back for the IDs of types you didn't include fragments for, and no errors.

**Comment by EricNetsch** [comment]
@minasmart Thanks! 
Oh I understand how the fragment now. Interesting. 
Happy to help on this once I dig into the JS code more. 

Thanks again Mina

**Comment by rebeccajfriedman** [comment]
This is supported by `fetchMultiple` on the [product resource](https://github.com/Shopify/js-buy-sdk/blob/master/src/product-resource.js#L69).
