### ISSUE TITLE
Synchronise checkout with Liquid theme's cart?

### ISSUE THREAD

**Issue by abhilash29** [Shopify/js-buy-sdk#520]
![screenshot at apr 20 23-23-58](https://user-images.githubusercontent.com/1309199/39066233-fce616d6-44f1-11e8-9a69-5a0c2388bcd7.png)
Is there a way where I can sync my checkout with the website's cart? As you can see in the screenshot, there is 1 item added to the cart. However, that was done using the add to cart button on the web page itself.
What I'm looking for is something where the cart/checkout that consists of line items which I created using JS Buy SDK can also be seen as I've pointed in the screenshot.

**Comment by minasmart** [comment]
Online store is a separate sales channel from whatever you're using the storefront API with. If you created a private app, that app is a sales channel and has access to a different product and collection set than online store. Additionally, a merchant's sales attribution go to the sales channel that owns the checkout. For this reason, channels are essentially blind to each other, and data is not synced between them.
