### ISSUE TITLE
Object doesn't support property or method 'assign'

### ISSUE THREAD

**Issue by dsshap** [Shopify/js-buy-sdk#523]
Getting this error from Internet Explorer version 11.

Looks be be happening when calling ```client.checkout.create().then(function...```

**Comment by rebeccajfriedman** [comment]
We intentionally don't provide polyfills with this library. It's worthwhile to figure out what environments make sense for you to target, and to provide the appropriate polyfills. I think providing the library pre-packaged with the polyfills Shopify thinks is best won't ever really satisfy a large subset of our developer community.
