### ISSUE TITLE
client.checkout.create() returns null

### ISSUE THREAD

**Issue by dsshap** [Shopify/js-buy-sdk#525]
@minasmart I am seeing a number of error reports coming from customer browsers when I try to init a new checkout (sentry error tracking).

The error that is returned in the `.catch(function(err) {...` is `Failed to fetch`.

I see that the fetch returned `null`
![image](https://user-images.githubusercontent.com/1558338/39634897-976a0f20-4f81-11e8-9e33-c807f572a43c.png)

When this happens, I add a retry that fires 500ms later. That request also returns null.

I unfortunately do not have a way to capture the request ID since this call is buried in the js-buy-sdk library.

**Comment by minasmart** [comment]
"Failed to fetch" is not an error returned by our API or this library. I'd need to see more code, or a network error to help with this.

**Comment by dsshap** [comment]
@minasmart 

I am overwriting fetch using polyfill https://github.com/github/fetch

Sometimes your api calls throw an error and "Failed to fetch" comes from here: https://github.com/github/fetch/blob/master/fetch.js#L439

**Comment by minasmart** [comment]
The error from that polyfill suggests that the error message should be `Network request failed`. Either way: Do you have the body of the error passed to the call to `.catch`, the request body, or the response body? There's not much I can do with the data given.

**Comment by dsshap** [comment]
@minasmart originally I was using windows built in fetch. That fetch returned `Failed to fetch`. Now I am using the polyfill and that is what is returning. `.catch` is returning `Network request failed` - I also hoped there would be more, but unfortunately your service does not return anything, which is why it failed.

**Comment by dsshap** [comment]
As the title of this issue suggests, it happens on checkout create.

**Comment by minasmart** [comment]
Our service returns something, wether it's an http status code, or a set of headers or a full json payload with an errors hash. Similarly, do you have access to the payload you're sending the API? Just knowing that there's some error happening on checkout create is really not enough information to go on.

**Comment by dsshap** [comment]
@minasmart this is the issue, the service doesn;t return an error hash.

Here is the request details that I was able to capture.

```
{  
  headers:{  
    accept: application/json,
    content-type: application/json,
    x-sdk-variant: javascript,
    x-sdk-version: 1.4.0,
    x-shopify-storefront-access-token: c353e91716e1b011872b566ea1959915
  },
  method: POST,
  mode: cors,
  url: https://xyz.myshopify.com/api/graphql
}
```

The polyfill is throwing the error from this line: `xhr.onerror`, https://github.com/github/fetch/blob/master/fetch.js#L438
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequestEventTarget/onerror

As a reference, https://github.com/github/fetch/blob/master/fetch.js#L427 never gets called.

It seems to be happening predominately on Chrome 66.0.33*.

**Comment by dsshap** [comment]
@minasmart I am sure it supports native fetch. js-buy-sdk has many issues with some version of edge (where fetch is broken), so we elected to use polyfill across all browsers (for consistency, until this issue being discussed is resolved). There should be no reason that polyfill works everywhere except with this version.

I am unable to use a network inspector... these errors are happening to my customers (in production, and being reported by sentry).

Are you not able to query API requests by `store` x `user-agent` x `errors`?

**Comment by minasmart** [comment]
is the shop `scoutalarm.myshopify.com`? Over the past week, there have been zero non-200 response codes on that shop from the graphql API out of over 10000 events. This tells me the payload is either coming down with an errors hash in the result, or something is breaking before the fetch is sent.

**Comment by dsshap** [comment]
@minasmart 

It is my store. As mentioned in the previous post it never reaches https://github.com/github/fetch/blob/master/fetch.js#L427

So if it is returning an errors hash, I do not see where that would be happening inside this particular fetch library.

Please advice where in `js-buy-sdk` library I should add code to capture context for request / response that both succeeded and failed.
