### ISSUE TITLE
How to sort the products received from the collection id

### ISSUE THREAD

**Issue by Kasirajan7** [Shopify/js-buy-sdk#527]
client.collection.fetchByHandle(url_parts.query.handle).then((collection) => {
                //collection contains products which i need to sort in some orders
               var body = {};
                body.success = true;
                body.platform = 'Shopify';
                body.products = collection;
                response.send(body);
                return;
            }).catch(function(err) {
                errorlog(err);
                response.send({ "status": "failure", 'message': 'Error fetching products', 'products': [] });
            });

//I need to sort the products by ascending order how to achieve it.

**Comment by juanlet** [comment]
Did you get an answer for this issue?

**Comment by Kasirajan7** [comment]
@juanlet I didn't find any possible way to sort this product received from fetchByHandle .Instead, we use the Shopify REST Admin API to achieve this.

**Comment by juanlet** [comment]
thanks my friend, can you provide which client you used(the npmjs package name) to query the REST admin API?

**Comment by rebeccajfriedman** [comment]
You can actually do this using a custom query: https://github.com/Shopify/js-buy-sdk#expanding-the-sdk

```
const sortKey = this.props.client.graphQLClient.variable('sortKey', 'ProductCollectionSortKeys')
const testQuery = this.props.client.graphQLClient.query([sortKey], (root) => {
  root.add('collectionByHandle', {args: {handle:  HANDLE}}, (collection) => {
    collection.add('id')
    collection.addConnection('products', {args: {sortKey: sortKey, first: 50, reverse: true}}, (product) => {
      product.add('createdAt')
      product.addConnection('variants', {args: {first: 50}}, (variant) => {
        variant.add('id')
        variant.add('price')
        variant.add('selectedOptions', (opts) => {
          opts.add('name')
          opts.add('value')
        })
      })
    })
  })
});

this.props.client.graphQLClient.send(testQuery, {sortKey: "CREATED"}).then(({model, data}) => {
  // Do something with the products
  console.log(data);
});
```

Notice how the example sorts the products by "CREATED" and also `reverse: true`
