### ISSUE TITLE
Parameters for pagination

### ISSUE THREAD

**Issue by pmdownie** [Shopify/js-buy-sdk#531]
Hi guys.

Again, trying to find specific answers for this in the docs but can't seem to find them.

I was wondering if there was another way to paginate products within a collection without sending the whole current array of products?

For example could you send the collection id as a parameter to fetchNextPage?

Thanks

**Comment by minasmart** [comment]
pagination in graphql connections works off of the cursor associated with the last element. The client baked into this library takes the array of products (or the last element) and generates the relevant query off of the provided node. The collection ID is insufficient.
