### ISSUE TITLE
client.fetchNextPage() returns TypeError

### ISSUE THREAD

**Issue by pmdownie** [Shopify/js-buy-sdk#532]
I'm trying to paginate a collection using the `fetchNextPage()` but it returns the following error:

`TypeError: node.nextPageQueryAndPath is not a function
    at Client.fetchNextPage`

I've set up an express api to handle my shopify queries, and I access this pagination controller through a post request so I can attach the product to the body:
here's how I call the function:

`const paginateCollection = () => async (req, res, next) => {
const collection = await client.fetchNextPage(req.body.product);
res.send(collection);
};`

Very sorry if this a mistake by me. Can't seem to rectify the mistake :)

Thanks

**Comment by minasmart** [comment]
you should be calling `client.fetchNextPage` takes an array of products returned from the SDK. If you can show us where `req.body.product` is coming from, that may be more helpful.

**Comment by pmdownie** [comment]
Hi. Thanks for the reply.
Of course. Just FYI I changed `req.body.product` to `req.body.products` and am now posting the entire product array to the node api.

`req.body.products` is coming from an axios call within a redux action.

Here's the redux action and axios call.
```
export const paginateCollection = prodArr => (dispatch, getState) => {
	const QUERY_STRING = `${process.env.APP_DOMAIN}/storefront-api/paginate-collection`;
	axios
		.post(QUERY_STRING, { products: prodArr })
		.then(response => console.log(response));
};
```
In this call, `prodArr` is the array of products returned from the initial SDK call to `client.fetchCollectionByHandle`. 

Just incase it's relevant, the version of shopify-buy I'm using is 1.4.0

Let me know if you need anything else from me.

**Comment by minasmart** [comment]
This doesn't show the call in the buy sdk that yields product array. Without that, I really can't tell you why anything isn't working, or if the products array is getting mangled from when it comes out of the SDK, to when you're trying to paginate off of it.

**Comment by pmdownie** [comment]
Hi again.
You were right, the error was in the product array call. 

The collection model is returned as a GraphModel when called from the node server, but when it gets sent to  the redux action through axios it gets flattened, and kills the nextPageQueryAndPath method.

I was able to paginate collections when using the shopify client from the front end.

As said in the earlier comments, I created a node api which calls the shopify client, and I communicate with it through axios in my frontend.
I would like to keep the structure the way it is but I'm having trouble trying to find how to send the data received from the shopify Client down to the frontend whilst still keeping it as a GraphModel and not flattening it.
Would you have any advice on how to best handle that?

Thanks in advance for bearing with it.

**Comment by pmdownie** [comment]
Hi there.
Sorry to bother but would you have any info to help solve this problem?
Trying to keep the object in the GraphModel shape from server to client?

Best

**Comment by minasmart** [comment]
I can't think of any immediate solution to this, since serialization of functions can't really work across a json exchange layer. I think any change to support this would have to take place at the graphql client layer. We'd likely have to remove any context tracking and state from the model, which would require a large refactor of that code base, and that's not currently roadmapped out.

**Comment by Januszpl** [comment]
@pmdownie what solution did you implement in the end?

@rebeccajfriedman @minasmart any changes in the roadmap?
