### ISSUE TITLE
Combine JS-Buy-SDK and "traditional" shopify flow

### ISSUE THREAD

**Issue by sww314** [Shopify/js-buy-sdk#533]
**Is your feature request related to a problem? Please describe.**
I have a client that has custom product builder. The product has several custom options that are selected using product variants. This is currently built using the JS Buy SDK.

The store also has basic products (gift card) etc. These products are added through the "normal" flow of a Shopify cart.  
However, the carts are different when created in the JS-BuySDK vs on the normal store flow. 

**Describe the solution you'd like**
I want to make the carts the same for both flows. I think I should be able to do this by getting by a cookie value and using it in the request to get a checkout. Or the reverse of saving the cookie, when the product is first added via the SDK calls.

    const checkoutId = convertId('Checkout',`${getCookie('cart')}&key=${getCookie('cart_sig')});
 
     this.props.client.checkout.fetch(checkoutId).then(res => {
       this.setState({
         checkout: res,
      });

     // Where convertId does something like this:
    return btoa(`gid://shopify/${type}/${databaseKey}`);

This does not work. The SDK throws an error trying to access lineItems when it is null. The checkout ids are a different format for the GraphQL interface. I can could not find any documentation on how to do this.

**Comment by minasmart** [comment]
An app using the buy SDK counts as a channel. Channels don't have access to each others carts (both for security, and clarity with publications, since all products in a cart from one channel may not be available on another channel). The SDK is appropriately throwing an error here since you are attempting to access another channel's data.
