### ISSUE TITLE
Translate query from Shopify GraphiQL App to js-buy-sdk?

### ISSUE THREAD

**Issue by lapidus** [Shopify/js-buy-sdk#534]
I have this query in Shopify GraphiQL App:
(Getting all products within a collection based on a handle)

```
{
  collectionByHandle(handle: "my-collection-handle") {
    id
    storefrontId
    products(first: 20) {
      edges {
        node {
          id
        }
      }
    }
  }
}
```

How do I fetch the same using the js-buy-sdk?
Can I pass a custom query like the above or have to rely on particular higher-level methods like client.collection.someMethod()?

**Comment by minasmart** [comment]
All the js buy SDKs queries are pre-built. If you want custom data, please use graphql directly.
