### ISSUE TITLE
Regarding Buy SDK + Shopify Scripts

### ISSUE THREAD

**Issue by kisuka** [Shopify/js-buy-sdk#535]
Our business uses Shopify Plus to handle our product purchasing for our service. We've been using it for about 3 or 4 years now.

We implemented the Buy SDK a while back on our main site which allows the user to quickly purchase a product instead of going to the store subdomain. They're able to click on a 'buy button' and be prompted with a list of variants of the product, then they hit checkout and are immediately taken to checkout.

This was all great until we started wanting to use Shopify Scripts to give discounts to our users who are VIP members. When one of these users places an order through the actual Shopify hosted storefront, the Line Item scripts run and apply discounts just fine.

However, when the user uses the Buy Button SDK on our main site, Line Item Scripts do not run at all during checkout. This results in a mess of a situation for us where some users get the discounts when going directly through the store, and other users do not. This results in customers sending us support tickets asking for partial refunds for their discount.

Why do Line Item scripts not apply for checkouts generated via the Buy SDK? It seems very weird that they are limited only to a POST request from the Shopify hosted site to /cart on the Shopify hosted site.

Is there a reason why they cannot be applied at the initialization of any checkout? Is there plans to support them at all when creating a checkout via the buy sdk? Is there a solution at all to make sure they trigger while still keeping our current flow from Our Site -> Shopify Checkout?

**Comment by oscarpan** [comment]
We're running into the same issue as you @kisuka - would love to see a solution given by Shopify.

**Comment by petomi** [comment]
We're running into the same issue as well. I'm considering using a script on the checkout page to add and remove a $0 product to the cart, thereby mutating the cart and hopefully triggering the line item script, but it would be great to see an official solution for this instead of having to look for strange workarounds.

**Comment by kennyburns1967** [comment]
We are also having the same issue. Any word or workarounds for this? Its not exactly ideal.

**Comment by firescript** [comment]
Same issue here.

**Comment by mike-rotate** [comment]
Yep, same issue here - why does this limitation exist and could we get a timeline for its fix?

As plus paying customers hopefully it might be a faster fix turnaround than normal?

**Comment by morganmccunn** [comment]
Hey folks - we know this has been a limitation for some time. We don't have a timeline for this work just yet, but we are working through planning our work for the upcoming year and this is on the radar. I will post an update here once I have more information.

**Comment by kennyburns1967** [comment]
Appreciate the reponse, but it's not good enough to be honest. We raised this issue, amongst others, months ago and keep getting fobbed off with the workarounds and fudges. Your API/SDK for checkouts is, in my opinion, currently unusable in its current state and I cannot for the life of me understand why scripts only load if you come from the cart page?

We pay a significant sum of money each month to Shopify for it's services, but the problems we have faced trying to integrate our shop and checkout process as part of a website flow left a lot to be desired. We might have to look elsewhere.

**Comment by cgenevier** [comment]
Has there been any movement on this? We're also experiencing the same issue and would love a solution.

**Comment by morganmccunn** [comment]
Hey @cgenevier there has been some great progress on this, but there are a few blockers we are sorting through before we can launch.

**Comment by kilinkis** [comment]
I'm having the same issue. Looking forward this implementation, makes no sense that the scripts won't run if the checkout is generated via the BUY SDK.

**Comment by rebeccajfriedman** [comment]
Scripts are now available for private apps: https://developers.shopify.com/changelog/storefront-api-updates-metafields-scripts-and-more

**Comment by kilinkis** [comment]
@rebeccajfriedman the link returns 404 :) very excited about this!

**Comment by rebeccajfriedman** [comment]
@kilinkis thanks for reporting that! The link should be working now!
