### ISSUE TITLE
Error : Checkout is already completed

### ISSUE THREAD

**Issue by Julian164** [Shopify/js-buy-sdk#537]
**Describe the bug**
Hello,

I'm currently migrating my code to the newest version to v1, which worked out good but now I am having an issue where the documentation is not helping me anymore : 

Once an order has been placed and the checkout process was successful and I reopen the webshops website again I can not add any products to my checkout because "the checkout is already completed". Seems like I have to reset the checkout once it was successful - but how?

Haven't had this problem with v0.7

**Expected behavior**
In version 0.7 there was no extra code needed. Once the checkout was completed, a new "cart" was created when the site got reopened. 

**Environment (please complete the following information):**
- Mac OS 10.13.3
 - Browser : Chrome
 - SDK Version v1

**Additional context**

**Bug Report Checklist**
- [x] I have read and agree to the [CODE_OF_CONDUCT.md](https://github.com/Shopify/js-buy-sdk/blob/master/CODE_OF_CONDUCT.md)
- [x] I have read the [CONTRIBUTING.md](https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md) guidelines.
- [x] I have provided a detailed description of the bug, including code samples, and/or network data.
- [x] I have provided information about my development environment, including SDK version.

**Comment by StefanSlehta** [comment]
Hi Julian! You need to create a new checkout once it's been completed. Take a look at how `buy-button-js` does it [here](https://github.com/Shopify/buy-button-js/blob/master/src/components/cart.js#L157)

**Comment by Julian164** [comment]
Thanks! 

That was exactly the little piece of code I was looking for. 
Works perfectly, thanks!
