### ISSUE TITLE
Documentation Updates

### ISSUE THREAD

**Issue by itsdarrylnorris** [Shopify/js-buy-sdk#544]
- There seem to be a broken link in the documentation under examples. This is the line that contain the broken link https://github.com/Shopify/js-buy-sdk/blame/master/CONTRIBUTING.md#L64 . 
  - Should we link the project page rather than broken link?
- In the documentation it looks like the user is encourage to use NPM and there is not mention of using Yarn in the documentation. However, it looks like yarn is the standard for contribution since there is `yarn.lock` and there is not a `package-lock.json` 
  - Should we change the documentation to have the instructions using Yarn rather than NPM?

**Bug Report Checklist**
- [x] I have read and agree to the [CODE_OF_CONDUCT.md](https://github.com/Shopify/js-buy-sdk/blob/master/CODE_OF_CONDUCT.md)
- [x] I have read the [CONTRIBUTING.md](https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md) guidelines.
- [x] I have provided a detailed description of the bug, including code samples, and/or network data.
- [x] I have provided information about my development environment, including SDK version.

I will be more than welcome to submit a PR to improve the documentation.

**Comment by owenfi** [comment]
Sorry to piggyback on this issue, but another item is the example:

    import Client from 'shopify-buy';

    const client = Client.buildClient({
      domain: 'your-shop-name.myshopify.com',
      storefrontAccessToken: 'your-storefront-access-token'
    });

where it seems it should actually be:

`const client = ShopifyBuy.buildClient({`

**Comment by rebeccajfriedman** [comment]
@darol100 @owenfi I have update the broken link. Feel free to open PRs to address the other suggestions!
