### ISSUE TITLE
sort by price

### ISSUE THREAD

**Issue by lisadreamer** [Shopify/js-buy-sdk#547]
fetching products sorted out by price so that when when fetching next page of products it would keep the order. it currently works for me by title and date. According to Storefront API docs only ProductCollectionSortKeys has price (not ProductSortKeys). 

now we have only this fetchQuery in v1 both for product and collection where we can pass arguments object. This object has sortKey but its done for ProductSortKeys and CollectionSortKeys. is it possible to use ProductCollectionSortKeys?

Currently, I could sort products when i receive them but it obviously is broken when i fetch next page.

**Comment by minasmart** [comment]
Sorting products in collections is, unfortunately, not the same as sorting products fetched off of a shop. It's something we've roadmapped, but not something I have an ETA on. Sorry.

Closing for now, since there's no fix for the time being.
