### ISSUE TITLE
Dead links in reference

### ISSUE THREAD

**Issue by wirsing** [Shopify/js-buy-sdk#550]
There seem to be some dead links in the docs:

https://shopify.github.io/js-buy-sdk/CollectionResource.html

Under 'fetchQuery'

This link seems to be dead:
https://help.shopify.com/en/api/storefront-api/reference/object/shop#collections

thanks!

**Comment by minasmart** [comment]
Thanks for pointing this out! This seems to be an issue with our docs system. I'll update with either better links, or get the docs fixed. If it's helpful, the new URL for that topic is here:

https://help.shopify.com/en/api/custom-storefronts/storefront-api/reference/object/shop#collections

**Comment by wirsing** [comment]
@minasmart thanks for the quick response! yes, it seems there are tons of dead links right now.
