### ISSUE TITLE
Thoughts on how to support availableShippingRates on checkout?

### ISSUE THREAD

**Issue by darol100** [Shopify/js-buy-sdk#553]
**Is your feature request related to a problem? Please describe.**
- Well, I will like to get the ability to query `availableShippingRates` from the `js-buy-sdk`.

**Describe the solution you'd like**
- A reusable method to provide the `availableShippingRates` without duplicating to much code.

**Describe alternatives you've considered**

1. I tried to add `availableShippingRates` as part of `CheckoutFragment` but that seems to fail and I strongly believe is because when I am creating the checkout I do not have a valid address yet. From the StoreFront API documentation, "The available shipping rates for this Checkout. Should only be used when checkout `requiresShipping` is true and the shipping address is valid." I believe that is the reason why is failing.

2. Another alternative that did not work, I created a new `NodeQuery` and new `fetch()` and new `CheckoutFragment`, which has a `availableShippingRates` in the new `CheckoutFragment`. This will allow me to fetch my checkout data after I added my shipping data, however, this does not seem to be working. This is the error that I am getting:
```
checkout#/:1 Uncaught (in promise) [{…}] 0 : locations : Array(1) 0 : column : 530 line : 1 __proto__ : Object length : 1 __proto__ : Array(0) message : "Parse error on "}" (RCURLY) at [1, 530]" __proto__ : Object length : 1 __proto__ : Array(0)
````

Where should we add the `availableShippingRates` for checkout?

**Comment by darol100** [comment]
> Another alternative that did not work, I created a new NodeQuery and new fetch() and new CheckoutFragment, which has a availableShippingRates in the new CheckoutFragment. This will allow me to fetch my checkout data after I added my shipping data, however, this does not seem to be working. This is the error that I am getting:

The problem was related to lack of fields under `availableShippingRates`. I found a solution for my problem.

However, I still would like to contribute back `availableShippingRates` at some level but some direction and where `availableShippingRates` should be? Maybe it should be something separate from `CheckoutFragment`?

**Comment by rebeccajfriedman** [comment]
You could instead write a custom query to pull the `availableShippingRates` or any other exposed fields that you need: https://github.com/Shopify/js-buy-sdk#expanding-the-sdk
