### ISSUE TITLE
addDiscount not found in NPM version

### ISSUE THREAD

**Issue by givo-matan** [Shopify/js-buy-sdk#554]
The NPM version of the SDK does not support the addDiscount method.

To Reproduce:
run the example code from the docs:
 
client.checkout.addDiscount(checkoutId, discountCode).then(checkout => {
  // Do something with the updated checkout
  console.log(checkout);
});
 will throw an error: 'client.checkout.addDiscount is not a function..'

Expected behavior:
client should support the ability to add a discount code to a checkout

 - OS: Windows
 - Node v 8.1
 - SDK Version 1.6

**Comment by kwent** [comment]
Let's release a version on npm, i need that feature as well :)

**Comment by blakewatson** [comment]
Is this a situation where it's in the source but didn't get compiled?

**Comment by givo-matan** [comment]
looks like it.
See src/checkout-resource.js line 132

**Comment by minasmart** [comment]
A release with this function hasn't been cut and sent to NPM. I can do that shortly.

**Comment by minasmart** [comment]
`v1.7.0` is headed to NPM.
