### ISSUE TITLE
FetchQuery via Tag does not work

### ISSUE THREAD

**Issue by naiduasn** [Shopify/js-buy-sdk#555]
**Describe the bug**
I am trying to get the products which has a certain tag. 
It gives empty results though I have products which match my tag.

**To Reproduce**
Steps to reproduce the behaviour:

        const query = {
            query: 'title: mayo'
          };
        
        const query1 = {
            query: 'tag: [mayo]'
          };

            client.product.fetchAll().then((products) => {
                console.log("Naidu " + products)
             });

             client.product.fetchQuery(query1).then((products) => {
                console.log("Naidu tag" + products)
             });

             client.product.fetchQuery(query).then((products) => {
                console.log("Naidu title" + products)
             });

**Expected behavior**
fetchAll & fetchQuery via title yields results for me. but if i use tag, it does not work.
I was not sure if i am making any mistake in the way i wrote the query or an issue with API itself.

**Environment (please complete the following information):**
 - OS: Android
 - SDK Version [API 27]
 - js-buy-sdk Version: 1.7.0

**Bug Report Checklist**
- [x] I have read and agree to the [CODE_OF_CONDUCT.md](https://github.com/Shopify/js-buy-sdk/blob/master/CODE_OF_CONDUCT.md)
- [x] I have read the [CONTRIBUTING.md](https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md) guidelines.
- [x] I have provided a detailed description of the bug, including code samples, and/or network data.
- [x] I have provided information about my development environment, including SDK version.

**Comment by naiduasn** [comment]
Can someone help me out here?

**Comment by naiduasn** [comment]
If anyone faced the same issue: Removing whitespace next to tag solved my issue.
New Query looks like this:

const query1 = {
        query: 'tag:mayo'
      };

**Comment by juanlet** [comment]
Do you know how to build that object to query for 2 different things? Let's say for a tag and for title....
