### ISSUE TITLE
docs font weight

### ISSUE THREAD

**Issue by tessalt** [Shopify/js-buy-sdk#56]
I'm finding courier new _really_ tough to read in the docs because it's so thin. Shopify docs uses a stack of `Menlo, Monaco, Consolas, "Lucida Console", monospace` which seems much easier to read. @d10k @harismahmood89

**Comment by harismahmood89** [comment]
Agreed - it looks fine in FF and IE but rubbish on Chrome. I tried increasing the weight to 500 but it looks too heavy.

**Comment by d10k** [comment]
Agreed. Let's do 'Menlo' then. The type looks thicker so we might need to drop down the size.
