### ISSUE TITLE
Unable to add items to an existing checkout with a deleted product

### ISSUE THREAD

**Issue by noambonnie** [Shopify/js-buy-sdk#560]
**Describe the bug**
I'm trying to handle a case where a product was deleted from the store. There might be checkouts that contain that product. 

When I fetch such checkout with a deleted product, I'm unable to add new items to the checkout. However, there is no error/promise rejection. The operation appears to have succeeded.

My issues/questions are:
1. What's the correct way to handle deleted products in existing checkouts.
2. addLineItems should fail in such a case with a clear error.

Currently my plan is to check each checkout I fetch. If it has a deleted product in one of the line items (line item with no variantId) I will delete the entire checkout.

**To Reproduce**
Steps to reproduce the behaviour:
```
let checkout = await client.checkout.create({
    email: "noam-test@hello.com",
    note: "This is a test"
);

try {
    checkout = await client.checkout.addLineItems(checkout.id, [{ variantId: "<your product id>", quantity: 5 }]);
    checkout.lineItems.forEach((item) => {
        console.log(`${item.title} (${item.quantity}) LineItemId: (${item.id})`);
    })
}
catch(err) {
    console.error(err);
}
```
Now go to the admin page and delete the product that you added.

Then this does not throw an exception but does not add the product either:
```
let checkout = await client.checkout.fetch("<the checkout ID we created>");

try {
    // This has the appearance of succeeding. No exception caught. However, the loop below only prints 
    // the line item of the deleted product. 
    checkout = await client.checkout.addLineItems(checkout.id, [{ variantId: "<valid variant id>", quantity: 5 }]);
    checkout.lineItems.forEach((item) => {
        console.log(`${item.title} (${item.quantity}) LineItemId: (${item.id})`);
    })
}
catch(err) {
    console.error(err);
}
```

Now, if I remove the line item of the deleted product and try again, it all works as expected:
```
    await client.checkout.removeLineItems(checkout.id, ["<The faulty line item's id>"]);
    try {
        checkout = await client.checkout.addLineItems(checkout.id, [{ variantId: "<valid variant id>", quantity: 5 }]);
        checkout.lineItems.forEach((item) => {
            console.log(`${item.title} (${item.quantity}) LineItemId: (${item.id})`);
        })
    }
    catch(err) {
        console.error(err);
    }
```

**Expected behavior**
Add line item should fail with an error, or probably better to return an error when fetching an invalid checkout. There's a product question here of how to handle checkouts with deleted products. 

**Environment (please complete the following information):**
 - OS: MacOS High Sierra
 - Browser: N/A (Node.js 8.9.1)
 - SDK Version SDK Version 1.8.0

**Bug Report Checklist**
- [X] I have read and agree to the [CODE_OF_CONDUCT.md](https://github.com/Shopify/js-buy-sdk/blob/master/CODE_OF_CONDUCT.md)
- [X] I have read the [CONTRIBUTING.md](https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md) guidelines.
- [X] I have provided a detailed description of the bug, including code samples, and/or network data.
- [X] I have provided information about my development environment, including SDK version.

**Comment by StefanSlehta** [comment]
Hey @noambonnie , the invalid `checkout` doesn't raise an exception, but you should be able to get the [`userErrors`](https://help.shopify.com/en/api/custom-storefronts/storefront-api/reference/object/usererror) associated with it. 
In your example : 
```
// This has the appearance of succeeding. No exception caught. However, the loop below only prints 
// the line item of the deleted product. 
checkout = await client.checkout.addLineItems(checkout.id, [{ variantId: "<valid variant id>", quantity: 5 }]);
```
If you try to access `checkout.userErrors` is it empty for you?

**Comment by noambonnie** [comment]
@StefanSlehta thank you for the response. I do get userErrors as you suggested. My issues are:
1. Nowhere in the docs could I find this. Is error checking in that way documented anywhere? (Asking for the next person to come across this issue).
2. The message I get in this case is 'Variant is invalid' - which can be misleading because the variant I'm adding is valid. It's the one that's already in the checkout that's invalid.

In any event, as far as I'm concerned this issue is resolved.

Thanks again.

**Comment by noambonnie** [comment]
Addendum: I think the userErrors should also be returned when fetching a checkout so apps can immediately know that the checkout is invalid rather than try to add an item first. From what I've seen, when I fetch the checkout I see no userErrors.

**Comment by minasmart** [comment]
User errors are only the result of a mutation. Adding a product to the checkout and that product later being invalidated is definitely an edge case but one we should definitely return a different error for.
