### ISSUE TITLE
checkout.webUrl not relative to domain? can it be with configuration?

### ISSUE THREAD

**Issue by chrisallick** [Shopify/js-buy-sdk#564]
**Describe the bug**
I have a verified domain and am using the JavaScript SDK. When I call checkout.webUrl the URL it creates is set to my_store_name.myshopify.com but my_actual_verified_url.com is what I'd prefer. Is that possible? Or do I need to parse it and recreate the checkout URL?

**To Reproduce**
Steps to reproduce the behaviour:

```
					this.shopifyClient.checkout.updateAttributes(checkoutId, input).then((checkout) => {
					  	// Do something with the updated checkout
  						// console.log( checkout.lineItems ); // Array with one additional line item
						// console.log( checkout );
  						console.log( checkout.webUrl );
  						console.log( checkout );
					});
```

**Expected behavior**
I expect a way for checkout.webUrl to print out URLs that using my verified domain instead of my_store_name.myshopify.com

**Environment (please complete the following information):**
 - Browser Chrome
 - SDK Version master

**Bug Report Checklist**
- [ x ] I have read and agree to the [CODE_OF_CONDUCT.md](https://github.com/Shopify/js-buy-sdk/blob/master/CODE_OF_CONDUCT.md)
- [ x ] I have read the [CONTRIBUTING.md](https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md) guidelines.
- [ x ] I have provided a detailed description of the bug, including code samples, and/or network data.
- [ x ] I have provided information about my development environment, including SDK version.

**Comment by ilievskizoran** [comment]
Hey @chrisallick.

This is indeed possible. I ran into this issue with GA not attributing visitors to channels because they were "landing" on our .myshopify domain which counted them as referrers from that domain.

All you need to do it initialize the shopClient with your custom domain.

```
const client = Client.buildClient({
  domain: 'www.domain.com',
  storefrontAccessToken: 'your-storefront-access-token'
});
```

Hope that helps.

**Comment by chrisallick** [comment]
Oh. Hah, that worked perfectly. I had tried that, but an error was thrown. It must have been something else. Thanks!
