### ISSUE TITLE
Unable to create checkout

### ISSUE THREAD

**Issue by owenfi** [Shopify/js-buy-sdk#570]
**Describe the bug**
Create a javascript client and attempt to create a template. It returns an error pertaining to a promise error.

It seems fairly likely that this: https://github.com/Shopify/js-buy-sdk/issues/379 has been reintroduced. It seems the resolution to that issue was to move off the alpha, but I don't think I've ever been using any alpha and it was working fine up until a bit ago (though perhaps I had a slightly old version of the library cached so maybe it was broken recently).

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/1295934/47415792-263d9080-d729-11e8-9acf-5e2ef6d17d8a.png">

**To Reproduce**
Steps to reproduce the behaviour:

This code was working previously (and also slightly more complicated code based on it).

    var client = ShopifyBuy.buildClient({
      domain: 'slime-of-the-day.myshopify.com',
      storefrontAccessToken: '9a07b705370e7b3972757c18f9db9b11',
    });

    client.checkout.create().then((checkout) => {
      alert("Created a checkout");
    });

If the error you're dealing with is a network / API issue, please include the value of the `X-Request-ID` response header, the data sent to the API, and the payload of the response.

**Expected behavior**
I expect a checkout to be created or the error to be pertinent to the failure. Instead the error is thrown:
Unhandled Promise Rejection: Error: Connections must include the selections "pageInfo { hasNextPage, hasPreviousPage }".

**Environment (please complete the following information):**
 - OS: Mac / iOS
 - Browser: Safari
 - SDK Version [e.g. `v1.2.0`]
<script src="https://sdks.shopifycdn.com/js-buy-sdk/v1/latest/index.umd.min.js"></script>
On October 24th 2018.

**Additional context**
Possibly I'm getting throttled as I've been doing some debugging around a facebook browser issue and hitting the endpoint a bunch of times (not programmatically though so fewer than a few hundred this evening)

**Bug Report Checklist**
- [x] I have read and agree to the [CODE_OF_CONDUCT.md](https://github.com/Shopify/js-buy-sdk/blob/master/CODE_OF_CONDUCT.md)
- [x] I have read the [CONTRIBUTING.md](https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md) guidelines.
- [x] I have provided a detailed description of the bug, including code samples, and/or network data.
- [x] I have provided information about my development environment, including SDK version.

**Comment by StefanSlehta** [comment]
A fix has been shipped in version `1.9.1` #571 . Thanks for bringing this up!
