### ISSUE TITLE
Creating checkout fails with "access denied"

### ISSUE THREAD

**Issue by freder** [Shopify/js-buy-sdk#582]
**Describe the bug**
creating a new checkout fails.
![image](https://user-images.githubusercontent.com/724844/47615402-9d1eb480-daae-11e8-837c-4519a067b1f8.png)

**To Reproduce**

- create store
- create private app
- set permissions:
![image](https://user-images.githubusercontent.com/724844/47615381-65b00800-daae-11e8-94cf-fd6f649a2369.png)

```js
global.fetch = require('node-fetch');
const Client = require('shopify-buy');

const main = async () => {
	const client = Client.buildClient({
		domain: 'xyz.myshopify.com',
		storefrontAccessToken: 'asdf',
	});

	await client.checkout.create({
		lineItems: [],
	})
		.then((checkout) => {
			console.log(checkout);
		})
		.catch((err) => {
			console.log(err);
		});
};

main();
```

**Expected behavior**
should not fail (since it obviously has the respective permission set).

**Environment (please complete the following information):**
`shopify-buy` 1.9.1

**Additional context**
retrieving product information works just fine.

**Comment by rebeccajfriedman** [comment]
@freder Are you still experiencing this issue? Do you experience it on shopify-buy 1.8.0?

**Comment by freder** [comment]
> someone on slack said it might be due to the account I'm working with being on the lite plan. could that be?

can you confirm that? @rebeccajfriedman

**Comment by rebeccajfriedman** [comment]
No, that is incorrect. You can use the Storefront API and js-buy-sdk on the lite plan.

I cannot reproduce this on my end. At this time, I recommend that you reach out to support directly at custom-storefronts@shopify.com and provide the name of your shop and private app.

**Comment by freder** [comment]
for completeness: querying for products, etc. does indeed work – it's just `checkout` that's causing problems.

**Comment by rebeccajfriedman** [comment]
Adding the answer here, since it may be useful for others.
The default [CheckoutFragment.graphql](https://github.com/Shopify/js-buy-sdk/blob/master/src/graphql/CheckoutFragment.graphql) returns an `order` field. In order to access this field, "Read and modify customer details" must be enabled, since orders are dependent on customers.

**Comment by freder** [comment]
good to know! – thanks @rebeccajfriedman

**Comment by viraths** [comment]
In my case I had to tick this option `unauthenticated_read_product_listings` as well.
