### ISSUE TITLE
Uses deprecated field names in GraphQL queries

### ISSUE THREAD

**Issue by freder** [Shopify/js-buy-sdk#586]
<img width="370" alt="screenshot 2018-11-01 at 20 57 54" src="https://user-images.githubusercontent.com/724844/47876164-e9eced00-de18-11e8-9cbd-475d5021016e.png">

these are the ones I noticed. there might be more.

**Comment by rebeccajfriedman** [comment]
Thank you for flagging this. These fields are deprecated, but we have not yet set a removal date. If you have time, I encourage you to create a PR to include the new fields that have replaced these.

**Comment by BitterChris** [comment]
We've added aliasing for `available` and `src` to their new field names of `availableForSale` and `originalSrc` respectively in #600. This allows us to keep this library consistent for now, while querying the new non-deprecated fields from the Storefront API.
