### ISSUE TITLE
Using the settings "DOMEvents" breaks the buy button

### ISSUE THREAD

**Issue by gregersen12** [Shopify/js-buy-sdk#590]
In the process of configuring the buy button, using the customization options found here: http://shopify.github.io/buy-button-js/advanced/ I was unable make the DOMEvents settings work, without the button crashing.

I am using the buy button DOMEvents to set up tracking on button click. This is what my option settings look like: 

```
"product": {
    "DOMEvents": {
      'click .shopify-buy__btn': function () {
        fbq('track', 'InitiateCheckout', '{content_category: "accessories", currency: "DKK", value: 299}');
  		fbq('trackCustom', 'UnbounceInitiateCheckout');
      }
    },
...
```
Now when this code is entered, the button will correctly register on-click events (hurraaay!), but suddenly stop using the normal functionality of actually opening the shop. So in essence it just becomes a click-to-track button, that doesn't do anything.
I know everything else is fine, because if I remove the DOMEvents part, everything works.

Secondly I want to mention I am running with the `iframe: false` option on both `product` and `cart` as well as having `popup: false` on the `cart` in order to make the current page become the checkout (I was having issues with mobile browsers detecting the popup).

I believe there is a bug, I don't think it's supposed to break when setting up the DOMEvents.

**Comment by rebeccajfriedman** [comment]
Hi @gregersen12 - this will override the default click behaviour, as expected. Feel free to post in the https://github.com/Shopify/buy-button-js repo if you have any other concerns.

**Comment by julianCast** [comment]
> Hi @gregersen12 - this will override the default click behaviour, as expected. Feel free to post in the https://github.com/Shopify/buy-button-js repo if you have any other concerns.

That is true for PRODUCT, but not for CART (checkout button), it won't override the default click. 
The original action and the logic inside your function both will work. (Ex: the checkout popup window will open and your logic will work too).

Is this intended @rebeccajfriedman ?
