### ISSUE TITLE
Add product URL / handle to checkout line items

### ISSUE THREAD

**Issue by arobbins** [Shopify/js-buy-sdk#592]
I have a particular use case where it would be really useful to have a product `handle` property on each line item returned from `checkout.lineItems`. If possible, it would also be great to have the Shopify URL for this particular product added as a property as well. Perhaps something like: `lineItem.handle` and `lineItem.url`.

I need the ability to allow users of my app to link their products directly to the Shopify product detail page. This feature allows for embedding products for display, but then driving their users directly to Shopify to continue the add to cart process.

I've tried to "build" the product URL myself by cherry picking the pieces I need from things like `shop. primaryDomain.url` and the handle from the product resource response. However I find this annoying for a couple reasons:

1. Fragility by relying on manual url construction
2. Unnecessary boilerplate code to get a couple simple values

I've attached a screenshot below of the lineItem object where it would be great to have these two properties set.

<img width="549" alt="2018-11-10 at 5 57 pm" src="https://user-images.githubusercontent.com/961947/48307499-f86f8e80-e513-11e8-96ca-2b81510cd9a1.png">

**Comment by swalkinshaw** [comment]
This is possible if you're able to use a custom query since you can do: line items -> product variant -> product -> `onlineStoreUrl`.

But right now only the product `id` is included: https://github.com/Shopify/js-buy-sdk/blob/master/src/graphql/VariantWithProductFragment.graphql#L4

**Comment by arobbins** [comment]
@swalkinshaw Thanks for the direction here. 

I'm hoping to avoid having to write any custom Graph QL queries myself as I can't figure out to construct them for the life of me. But if this is the direction the team is considering I'll just have to bite the bullet and learn how to do them.

Are there any helper libraries out there that make sending GQL queries easier?

**Comment by rebeccajfriedman** [comment]
There is a workaround, and that is to make 2 queries. 

The checkout line items will contain the product id (as Scott mentioned above). You can then make a [product query](https://github.com/Shopify/js-buy-sdk/blob/master/src/product-resource.js#L43-L45) using the id from the response, and that will return both the handle AND the online store url.

Hope this helps!

**Comment by abishekrsrikaanth** [comment]
@rebeccajfriedman, i just tried to use 2 queries based on your suggestion and this seems to be time consuming and doesn't offer good ux with the latency of each query executing for the number of lineitems. It would be great if the product handle/url is added to the line item as an enhancement.

**Comment by rebeccajfriedman** [comment]
As Scott mentioned above, the other thing you can do is write a custom query. We have added some basic instructions to the [README](https://github.com/Shopify/js-buy-sdk#expanding-the-sdk) on how to get started using this. There are also some examples of how to build queries [here](https://github.com/Shopify/graphql-js-client#creating-and-sending-a-query).

**Comment by theskillwithin** [comment]
Does someone have an example of how to build a checkout query?
