### ISSUE TITLE
Field availableForSale not returned when fetching all products

### ISSUE THREAD

**Issue by philspitler** [Shopify/js-buy-sdk#594]
When fetching all products using the js-buy-sdk, "client.product.fetchAll()", the **availableForSale** _Getter_ is no longer available.  This did work, but I don't see a code change in this library or this would be a pull request instead of an issue.  My code worked for quite some time with this working.  This seems like a very recent change.

**To Reproduce**
Call client.product.fetchAll() and see the results, they do not contain the **availableForSale** _Getter_.

Please see returned Objects below:
```javascript
GraphModel {
    id: [Getter],
    createdAt: [Getter],
    updatedAt: [Getter],
    descriptionHtml: [Getter],
    description: [Getter],
    handle: [Getter],
    productType: [Getter],
    title: [Getter],
    vendor: [Getter],
    tags: [Getter],
    publishedAt: [Getter],
    onlineStoreUrl: [Getter],
    options: [Getter],
    images: [Getter],
    variants: [Getter],
    refetchQuery: [Getter],
    type: [Getter],
    nextPageQueryAndPath: [Function],
    hasNextPage: Scalar { value: true },
    hasPreviousPage: Scalar { value: true },
    variableValues: { first: 20 } },
  GraphModel {
    id: [Getter],
    createdAt: [Getter],
    updatedAt: [Getter],
    descriptionHtml: [Getter],
    description: [Getter],
    handle: [Getter],
    productType: [Getter],
    title: [Getter],
    vendor: [Getter],
    tags: [Getter],
    publishedAt: [Getter],
    onlineStoreUrl: [Getter],
    options: [Getter],
    images: [Getter],
    variants: [Getter],
    refetchQuery: [Getter],
    type: [Getter],
    nextPageQueryAndPath: [Function],
    hasNextPage: Scalar { value: true },
    hasPreviousPage: Scalar { value: true },
```

**Comment by philspitler** [comment]
Please see the documentation for the product object:

https://help.shopify.com/en/api/custom-storefronts/storefront-api/reference/object/product#fields

RE:
```
availableForSale   (Boolean!)
Indicates if at least one product variant is available for sale.
```

And this was working just a couple days ago.

**Comment by jamiemtdwyer** [comment]
Sorry about that, I see that now. The linked PR will add `availableForSale` to the Product query fragment.

As for this working a couple days ago, I'm not sure how that would have been possible. The field is not included in the query fragment, and the history for that file does not show that it's been included at any point.

**Comment by philspitler** [comment]
Hey @jamiemtdwyer no worries.  After looking at the fix, I realized I actually patched the build under node_modules and then basically updated my project.  (totally boneheaded move on my part).  Now I've forked the project, fetched the branch, built locally, removed line from .gitignore and pushed to my repo.  When this gets merged, I'll point back to the public Shopify managed package.
