### ISSUE TITLE
Share created checkout cart with existing Shopify site

### ISSUE THREAD

**Issue by baptistebriel** [Shopify/js-buy-sdk#601]
**Is your feature request related to a problem? Please describe.**
Sooo, I'm building this experience site using the JS Buy SDK to create a cart, add products & then redirect to the checkout page. The experience itself is running completely separated to the actual Shopify site as it's just using the REST API.

The client had to host the experience within Shopify (I'm uploading all assets—JS, CSS, etc—throught the admin) and we only have one custom page within the Shopify site, where the experience lives. The client would like to have Shopify's site header on the experience as well and be able to keep sync the cart from the JS Buy SDK to the actual site and Shopify cart.

Is there a way of doing this?

**Describe the solution you'd like**
Not sure how this could be done. 😅

**Describe alternatives you've considered**
Tell the client to not have the Shopify header on the experience site 😅

**Comment by rebeccajfriedman** [comment]
Correct me if I'm wrong, but it sounds like you are using the JS Buy SDK on a page within the online store and you'd like to sync the JS Buy SDK cart with the online store cart. In that case, I'm not sure that JS Buy SDK is the right choice for you. Can you build the experience by customizing the liquid template for the page?

**Comment by baptistebriel** [comment]
Yes, that's correct. Originally the experience should have lived outside of Shopify, so we wouldn't have had access to the liquid templates. I guess this is a very specific use case and I agree with you, it doesn't really make sense to work on such a thing. Thanks!
