### ISSUE TITLE
AddLineItems unexpectedly increases the qty by 2

### ISSUE THREAD

**Issue by jordan-sowers** [Shopify/js-buy-sdk#607]
I have an add to cart button that triggers **checkout.addLineItems**. This works correctly the first time. The event adds the variant and correct quantity to checkout. 

If I hit the button again, it increases the qty by 2 (totaling 3, when it should be 2). This is a consistent behavior. Clicking add to cart continues to increase the item in the cart by 2, even when the quantity I've set within the function is 1. 

Should I be using the  **updateLineItem** method if the line item already exists in the cart? I was assuming the **addLineItems** method could be clicked multiple times (through an add to cart button) and it would follow whatever quantity was assigned and update that line item in the cart. Maybe that's where I'm running into this increase of 2 problem.

Clicking add to cart triggers:
```
const lineItemsToAdd = [
  {variantId: selectedVariant, quantity: 1}
];

// Add an item to the checkout
shopifyClient.checkout.addLineItems(checkoutId, lineItemsToAdd).then((checkout) => {
  console.log(checkout.lineItems);
});
```

Console log on first click:
<img width="999" alt="screen shot 2018-12-27 at 2 16 32 pm" src="https://user-images.githubusercontent.com/5034755/50496058-26386600-09e2-11e9-9283-d223c49e4661.png">

Console log on second click — quantity should be 13:
<img width="1005" alt="screen shot 2018-12-27 at 2 16 38 pm" src="https://user-images.githubusercontent.com/5034755/50496067-2f293780-09e2-11e9-9e9b-e375e931d08c.png">

After checking, I don't have multiple event listeners triggering at once through the button click.

**Comment by rebeccajfriedman** [comment]
> I was assuming the addLineItems method could be clicked multiple times (through an add to cart button) and it would follow whatever quantity was assigned and update that line item in the cart.

Every time you click the button, it should add the passed in quantity to the quantity on the checkout. If you click the button that you shared above, it should update the quantity of the selectedVariant to be one greater than it previously was. I have tested this on my shop, and it is working as expected.

It's hard to help you diagnose this further. Can you step through your code to make sure that nothing else could be affecting the quantity?
