### ISSUE TITLE
client.collection.fetchAllWithProduct() times out on certain stores

### ISSUE THREAD

**Issue by ar7casper** [Shopify/js-buy-sdk#608]
**Describe the bug**
when using the js-buy-sdk's `client.collection.fetchAllWithProduct()` I'm getting a proper response for one store but a timeout for the other. - `{"errors":[{"message":"Timeout"}]}`

I checked - 
- [x] Private App proper creds
- [x] All of the headers
- [x] Excluded Cookies

**To Reproduce**
Not sure, works great on one store, the same code for another fails. 

Please include code samples.

If the error you're dealing with is a network / API issue, please include the value of the `X-Request-ID` response header, the data sent to the API, and the payload of the response.
`X-Request-ID` - 266b5fa2-66f3-4c5b-9a65-1e804f36e0de
Response -  {"errors":[{"message":"Timeout"}]}

**Expected behavior**
A list of collection

**Environment (please complete the following information):**
 - OS: maxOS
 - Browser Opera / Chrome / Safari
 - SDK Version 1.11.0

**Additional context**

**Bug Report Checklist**
- [x] I have read and agree to the [CODE_OF_CONDUCT.md](https://github.com/Shopify/js-buy-sdk/blob/master/CODE_OF_CONDUCT.md)
- [x] I have read the [CONTRIBUTING.md](https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md) guidelines.
- [x] I have provided a detailed description of the bug, including code samples, and/or network data.
- [x] I have provided information about my development environment, including SDK version.

**Comment by rebeccajfriedman** [comment]
We're actively tracking this issue (https://github.com/Shopify/js-buy-sdk/issues/488). Thanks for bringing this up!

**Comment by ar7casper** [comment]
@rebeccajfriedman sorry, don't understand how they relate.
My issue relates to the fact this method isn't working at all.

**Comment by rebeccajfriedman** [comment]
As mentioned above, the timeout would be related to underlying performance.
