### ISSUE TITLE
No type of Automatic Discount Application found in schema

### ISSUE THREAD

**Issue by donovanroubos** [Shopify/js-buy-sdk#614]
**Describe the bug**
On our webshop we've automatic discounts. The user wasn't able to add more than 3 products because the API gave an error: "No type of Automatic Discount Application found in schema".

**Environment**
 - OS: iOS
 - Browser: Safari, Chrome and Firefox
 - SDK Version `v1.9.1`

**Additional context**
The symatic versioning of the package had a breaking change in `v1.9.1`. For this version you had to communicate that it was broken and for the future it's better to do a bigger version bump. So that it wouldn't auto update on all applications.

We've fixed the error by downgraded the package version from `v^1.8.0` satisfied `v1.9.1` to `v1.8.0`. This isn't the expected behavior of such a big api.

**Comment by rebeccajfriedman** [comment]
Thank you for flagging this. We are tracking this issue in our backend. Automatic Discounts are supported in the latest version (`v2.0.1`). Sorry for any inconvenience that this has caused you.

**Comment by rebeccajfriedman** [comment]
This is foward fixed in the latest release: [v2.1.1](https://github.com/Shopify/js-buy-sdk/releases/tag/v2.1.1). We have added support for falling back when interface objects can't be translated.
