### ISSUE TITLE
Outdated LineItem appears with null variant

### ISSUE THREAD

**Issue by ttillberg** [Shopify/js-buy-sdk#615]
**Describe the bug**
I'm using the JS API to display products and create a custom shopping cart.
I'm having an issue with the checkout cart and I believe it happens when you add a product to the cart that in its turn gets deleted from stock (from an admin point of view). 

What happens is that after fetching the cart again (with the session ID of the cart stored in `localstorage`), the outdated product still exists within the `lineItems` array but this time the `variant` is set to `null`. Because the variant is no more accessible I can't display the cart item properly with for example a warning message (i.e. thumbnail and price missing from the variant node). What's even more confusing - and this one seems to be hard to get around - is that the Total actually includes the price of the missing product/variant.

Now, if I go to the checkout page, I'm actually getting a warning saying *"Variant out of stock / Some items are no longer available. Your cart has been updated."* (However I don't think a customer would go to the checkout when the price displaying is wrong)

For now the only way I can figure to solve this would be to iterate the line items at the beginning of the session and check if there's a product with a missing variant. If so, return a new cart instead of the erroneous. 

**To Reproduce**

Note: I'm not allowed to play around with the real products since the shop is live but I do have a cart ID with which I can replicate the error (a product I added to the checkout got deleted after xmas).  This is how I proceeded:

Step 1 - Customer:
- Create a new checkout
- Add Item A (50$)
- Add Item B (10$)
- Leave the site for a while without checking out (in my case 2 weeks)

Step 2 - Admin: 
- Delete Item B (or its variant?) from stock

Step 3 - Customer:
- Come back to the website and fetch saved session / checkout
- Open cart, now Item B doesn't have a variant (throws in my case) - Total is still at 50 + 10 = 60$

I don't think there's any relevant code here apart from the `GraphModel` containing a `LineItem` with `variant: null`

**Expected behavior**
I would expect `LineItems` corresponding to discarded products would:
- either be removed automatically when fetching the cart
- or still exist but work as usual with a variant etc. until you get to the checkout.

**Environment (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - SDK Version 1.6.0

**Additional context**

**Bug Report Checklist**
- [x] I have read and agree to the [CODE_OF_CONDUCT.md](https://github.com/Shopify/js-buy-sdk/blob/master/CODE_OF_CONDUCT.md)
- [x] I have read the [CONTRIBUTING.md](https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md) guidelines.
- [x] I have provided a detailed description of the bug, including code samples, and/or network data.
- [x] I have provided information about my development environment, including SDK version.

**Comment by rebeccajfriedman** [comment]
I think you have a few options:
- You can make a new cart.
- You can start storing variant information in localStorage. This way, when the variant is null, you can supplement it with whatever information you've previously stored. 
- You can probably also make a server call to update the cart to remove the line item for the deleted variant.
