### ISSUE TITLE
Tacking Ad Campaigns Through To Orders

### ISSUE THREAD

**Issue by beardedbadger** [Shopify/js-buy-sdk#620]
**Describe the bug**

We've tried a number of ways to use the SDK to attach the UTM parameters we track through to the cart to the Order that is ultimately made by a customer.  

In the checkout API, this would be similar to posting to the `source_name` property.  

There doesn't appear to be a documented way to do this with the `js-buy SDK`.  Is this just a bug in the documentation?

**Bug Report Checklist**
- [x] I have read and agree to the [CODE_OF_CONDUCT.md](https://github.com/Shopify/js-buy-sdk/blob/master/CODE_OF_CONDUCT.md)
- [x] I have read the [CONTRIBUTING.md](https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md) guidelines.
- [x] I have provided a detailed description of the bug, including code samples, and/or network data.
- [x] I have provided information about my development environment, including SDK version.

**Comment by jamiemtdwyer** [comment]
Hi @beardedbadger,

Tracking conversion details (UTM parameters) for orders is only supported for Shopify Online Store currently.

In the meantime, if you want to keep track of some additional data about checkout, you could use [checkout attributes](https://help.shopify.com/en/api/custom-storefronts/storefront-api/reference/mutation/checkoutattributesupdatev2), but these won't be tracked in any reporting by Shopify.

**Comment by alexdupre** [comment]
@jamiemtdwyer is this still the current situation? Having the ability to add `utm` parameters to the checkout url so that shopify can properly track orders seems a relatively important feature.
