### ISSUE TITLE
Update or Change Order Status URL to point to the custom store front

### ISSUE THREAD

**Issue by abishekrsrikaanth** [Shopify/js-buy-sdk#624]
Is there a way to set the Order Status URL using the SDK. Currently the email that the customer receives has the URL pointing to store.myshopify.com. Is there a way to set it up to use the URL of custom store front?

**Comment by jamiemtdwyer** [comment]
Hey abishekrsrikaanth,

The return value of `orderStatusUrl` depends on the hostname which the API request was made to.

When initializing the buy client, you set the hostname via the `domain` argument:

```
const client = Client.buildClient({
  domain: 'your-shop-name.myshopify.com',
  storefrontAccessToken: 'your-storefront-access-token'
});
```

If you have configured a custom domain through Shopify admin (via Online Store -> Domains), you can input your custom domain as the `domain` argument, and the Checkout URLs and Order Status URLs returned by the API will be prefixed by your custom domain.

--

If instead you are creating a totally custom "order status" page on your own hosted storefront, you'll need to implement some logic on the client side to construct this URL. Updating the email templates in Shopify to point to your custom order status page will probably be challenging though.

**Comment by jamiemtdwyer** [comment]
Feel free to re-open this issue if this solution isn't clear.

**Comment by abishekrsrikaanth** [comment]
@jamiemtdwyer I do see the property `orderStatusUrl` on the Checkout object. Is there a way to set this property when creating the checkout object or a way to set it afterwards. I am building a self hosted storefront and I can construct the URL, but I am not sure how to set the url on the checkout object.
