### ISSUE TITLE
cant fetch single product data?

### ISSUE THREAD

**Issue by umxr** [Shopify/js-buy-sdk#629]
So im just trying to create a basic product detail view. the object that gets returned doesnt allow me to get the title or anything.Im trying to access the properties using normal dot notation. (product.title)  am i doing something wrong?. (withContext has the initialised client, paired it with a HOC so that i can easily allow any part of my app to fetch products etc) This is the code

```
import React from 'react';
import { Section } from 'rbx';
import { withRouter } from 'react-router-dom';

import Layout from '../components/Layout/Layout';
import { compose } from 'recompose';
import { withContext } from '../components/Context/WithContext';

class ProductDetail extends React.Component {
  state = {
    product: null
  };

  componentDidMount() {
    const id = this.props.match.params.id;
    this.props.context.shop.product.fetch(id).then(product => {
      this.setState({
        product
      });
    });
  }

  render() {
    console.log(this.state.product);
    return (
      <Layout>
        <Section>hi</Section>
      </Layout>
    );
  }
}

export default compose(
  withRouter,
  withContext
)(ProductDetail);

```

Resolved

**Comment by AlexanderProd** [comment]
@umxr How did you fix it?

**Comment by umxr** [comment]
@AlexanderProd Sorry for the late reply, I ended up fetching the product via the handle instead of the id

**Comment by juanlet** [comment]
how did you fetch by handle?
