### ISSUE TITLE
Is there any way to fetch a product with only variants that are in stock?

### ISSUE THREAD

**Issue by robskrob** [Shopify/js-buy-sdk#633]
Right now, if I execute `client.product.fetch(id).then((product) => {...})` of course I get the full product detail with its variants -- in stock or not.  I'd like to get the product with its in stock variants only. Is that possible?

I see this example in [the docs](https://shopify.github.io/js-buy-sdk/ProductResource.html):
```js
client.product.fetchQuery({first: 20, sortKey: 'CREATED_AT', reverse: true}).then((products) => {
  // Do something with the first 10 products sorted by title in ascending order
});
```

Is there any query I can pass that will return a product with only its in stock variants?

**Comment by rebeccajfriedman** [comment]
Hi @robskrob - we don't support that functionality right now. 

There is an [`available` field](https://github.com/Shopify/js-buy-sdk/blob/master/src/graphql/VariantFragment.graphql#L6) on the variant response that will indicate whether or not the variant is in stock. As a workaround, you could filter the list of variants that are returned on that `available` value.
