### ISSUE TITLE
Checkout Multiple Discount Codes

### ISSUE THREAD

**Issue by nataliaesthetic** [Shopify/js-buy-sdk#634]
Hi!
Are you guys planing to add interface to apply multiple discount codes for checkout. 
In our scenario customer might choose multiple items to checkout and each one comes with discount
code.
Thank toy!

**Comment by morganmccunn** [comment]
Hey there! This is a great question and something we are exploring. We have an issue in our backlog for this and can follow up here once there is more progress.

**Comment by nataliaesthetic** [comment]
Sounds great Morgan! 
Very appreciate your prompt response.  Look forward and will keep watching as well hope yours backlog tail not that long :)
Best regards!
