### ISSUE TITLE
No field of name "tags" found on type "Product" in schema

### ISSUE THREAD

**Issue by peeppirnpuu** [Shopify/js-buy-sdk#646]
Hello

I am using js-buy-sdk version 2.1.1. I used the exact example given on querying product tags:

```
// Build a custom products query using the unoptimized version of the SDK
const productsQuery = client.graphQLClient.query((root) => {
  root.addConnection('products', {args: {first: 10}}, (product) => {
    product.add('title');
    product.add('tags');// Add fields to be returned
  });
});

// Call the send method with the custom products query
client.graphQLClient.send(productsQuery).then(({model, data}) => {
  // Do something with the products
  console.log(model);
});
```

However I am getting `"Uncaught Error: No field of name "tags" found on type "Product" in schema"`

Private apps' Storefront API's "Read product tags" is allowed.

What could be the cause for this?

**Comment by morganmccunn** [comment]
Hey @peeppirnpuu - you need to ensure that your private app settings allow you to show your product tags. Under apps > Manage private apps (at the bottom) > open your app and update the configurable settings as follows:
[![alt](https://screenshot.click/25-50-9su33-xz0j3.jpg 
)](https://screenshot.click/25-50-9su33-xz0j3.jpg 
)

Hope that helps! please reopen if this is not the issue.

**Comment by peeppirnpuu** [comment]
I can confirm that “Read product tags” is set to allowed.

What else could cause this issue?

**Comment by teodormalmborg** [comment]
Hey!

I have the same issue but my app configuration looks different:
<img width="910" alt="Skärmavbild 2022-11-28 kl  08 50 27" src="https://user-images.githubusercontent.com/8415765/204223077-96fe627c-00b5-42a8-b5c4-56faeb3136a4.png">
