### ISSUE TITLE
No field of name "tags" found on type "Product" in schema

### ISSUE THREAD

**Issue by peeppirnpuu** [Shopify/js-buy-sdk#647]
Reopening issue https://github.com/Shopify/js-buy-sdk/issues/646

Confirming that "Read product tags" is checked, so what else could be the cause?

**Comment by StefanSlehta** [comment]
Hey @peeppirnpuu . For some context, take a look at #598

**Comment by peeppirnpuu** [comment]
Thank you @StefanSlehta, changing the import to `shopify-buy/index.unoptimized.umd` solved this issue for me.
