### ISSUE TITLE
How to fetch collection by handle and sort at the same time??

### ISSUE THREAD

**Issue by juanlet** [Shopify/js-buy-sdk#648]
I know I can fetch products by handle with the client.collection.fetchByHandle method. I know I can sort using client.collection.fetchQuery method indicating the sortKey and the order with the reverse property. But What I don't know what to do is to do both things at the same time. How can I accomplish that? This is my working code that is fetching the collections by handle correctly but I would like the ability to fetch them sorted by a criteria at the same time as using the handle to fetch my collections.

```
const fetchProductsInCollection = async (client, handle = null) => {
  // Fetch a single collection by ID, including its products
  let res;
  try {
    res = await client.collection.fetchByHandle(handle);
    return res;
  } catch (error) {
    console.log(error);
    throw new Error(error);
  }
};
```

**Comment by jamiemtdwyer** [comment]
I don't _think_ this is possible to achieve using the methods provided by the SDK, but you can build the [unoptimized](https://github.com/Shopify/js-buy-sdk/blob/5fbe92d05858926634ba5741b67f168a763be941/README.md#expanding-the-sdk) version and supply a query like this:

```
query {
  collectionByHandle(handle: "your-collection-handle") {
    products(first: 100, sortKey: TITLE) {
      edges {
        node {
          title
          description
        }
      }
    }
  }
}
```

Hope this helps!

**Comment by juanlet** [comment]
Any way of suplying raw queries to this client? the docs are not clear on that.

**Comment by jamiemtdwyer** [comment]
Hey @juanlet,

You can supply a raw query by following these steps in the README: https://github.com/Shopify/js-buy-sdk/blob/5fbe92d05858926634ba5741b67f168a763be941/README.md#fetching-products-1
