### ISSUE TITLE
Missing fields

### ISSUE THREAD

**Issue by peeppirnpuu** [Shopify/js-buy-sdk#651]
Hello

I noticed that Storefront API reference suggests using `availableForSale`, `compareAtPriceV2` and `priceV2` instead of deprecated `available`, `compareAtPrice` and `money`.

With version ^2.1.1, however, I can reliably access access only the deprecated fields. When trying to add `compareAtPriceV2` and `priceV2` into my product's variant connection, I get
`Uncaught Error: No field of name "compareAtPriceV2" found on type "ProductVariant" in schema` and same for `"priceV2"`.

What's even bizarre: when trying to add variant's `selectedOptions` into the query, I get an error:
```
errors: [
  {
    message: "Parse error on "}" (RCURLY) at [1, 423]"
  }
]
```

This is what my function looks like:
```
const productsQuery = shopify.graphQLClient.query((shop) => {
  shop.addConnection('products', {args: {first: 50}}, (product) => {
    product.add('id')
    product.addConnection('variants', {args: {first: 50}}, (variant) => {
      variant.add('id')
      variant.add('selectedOptions')
    })
  })
})
```

I am using unoptimized build in order to utilize graphQLClient custom query.

Could someone shed some light why:
1. js-buy-sdk version ^2.1.1 seems to support deprecated fields but not the new fields documented in Storefront API reference?
2. Why can I not access variant's selectedOptions while it is present with the same version using `shopify.product.fetchAll()`?

Thanks in advance!

**Comment by rebeccajfriedman** [comment]
> I noticed that Storefront API reference suggests using availableForSale, compareAtPriceV2 and priceV2 instead of deprecated available, compareAtPrice and money.

These fields are not yet available in the JS Buy SDK - sorry! We are hoping to release them this week.

> What's even bizarre: when trying to add variant's selectedOptions into the query, I get an error:

Selected options needs to be passed fields - here's an example. 

```
const productsQuery = shopify.graphQLClient.query((shop) => {
  shop.addConnection('products', {args: {first: 50}}, (product) => {
    product.add('id')
    product.addConnection('variants', {args: {first: 50}}, (variant) => {
      variant.add('id')
      variant.add('selectedOptions', (opts) => {
        opts.add('name')
        opts.add('value')
      })
    })
  })
})
```

**Comment by mariusa** [comment]
Hi @rebeccajfriedman 

The fields are also missing from [bulk queries](https://shopify.dev/api/usage/bulk-operations/queries), although they are documented at https://shopify.dev/api/storefront/2021-10/objects/ProductVariant#top

```js
                {
                        "field": [
                                "query"
                        ],
                        "message": "Invalid bulk query: Field 'compareAtPriceV2' doesn't exist on type 'ProductVariant'"
                },
      
                {
                        "field": [
                                "query"
                        ],
                        "message": "Invalid bulk query: Field 'priceV2' doesn't exist on type 'ProductVariant'"
                }
        ]
```

Where would be the best place to report this?

Thanks!
