### ISSUE TITLE
Any way of providing the client with a raw query?

### ISSUE THREAD

**Issue by juanlet** [Shopify/js-buy-sdk#652]
I would like to send a raw query in some cases and since the client is configured with the correct headers it would be nice to be able to pass it a raw query for certain queries that don't require pagination or one time queries. Any method to achieve that through this client?

**Comment by jamiemtdwyer** [comment]
Hey @juanlet,

You can find an example in the README here: https://github.com/Shopify/js-buy-sdk/blob/5fbe92d05858926634ba5741b67f168a763be941/README.md#fetching-products-1

**Comment by jamiemtdwyer** [comment]
If you need any additional help with this, please feel free to re-open the issue :)
