### ISSUE TITLE
Applying fixed discounts on CODEs and Automated Discounts

### ISSUE THREAD

**Issue by kilinkis** [Shopify/js-buy-sdk#653]
**Is your feature request related to a problem? Please describe.**
It seems like the only way to apply discounts via the BUY SDK is to apply discounts, which is not what we want.

**What we want:** you buy A + B so you get $20 off B

**What I tried:**

Case 1: discount codes don't take fixed discounts. Right now it just let's you choose between FREE and % discounts.

Case 2: Shopify Scripts won't run if the checkout is generated using the Buy SDK. [(Already discussed here)](https://github.com/Shopify/js-buy-sdk/issues/535)

Case 3: Similar to discount codes, Automatic Discounts don't support fixed amounts to discount, just FREE or %.

Case 4: support suggests we look for a 3rd party app to do this. None of them are free, most of them will charge big money if you're on Shopify Plus and not sure how well they integrate with this SDK.

**Describe the solution you'd like**
A: Shopify Scripts should also run on Buy SDK generated checkouts.
B: Automatic discounts should support fixed amount discount
C: Discounts codes should support fixed amount discount
D: Apply fixed discount via Buy SDK. The .addDiscount() method just takes discount codes at the moment.
E: At the moment, line item discounts are only applied via Shopify POS. Would be nice to have this feature also available in the Buy SDK.

Thanks :)

**Comment by rebeccajfriedman** [comment]
We're investigating allowing Scripts to solve this problem. I'll update on this ticket when we do!

**Comment by kilinkis** [comment]
That would be amazing, thanks!

**Comment by rebeccajfriedman** [comment]
Script discounts are supported for Plus stores. See the [help center](https://help.shopify.com/en/manual/apps/apps-by-shopify/script-editor) for more information.
