### ISSUE TITLE
Cross-Origin Read Blocking (CORB) blocked cross-origin response

### ISSUE THREAD

**Issue by agjs** [Shopify/js-buy-sdk#657]
This morning we started getting warnings with our Shopify SDK and our store no longer works.

Every time we try to add a product to the cart we are getting warnings:

> Cross-Origin Read Blocking (CORB) blocked cross-origin response https://SHOP_NAME.myshopify.com/api/graphql with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.

We had no recent updates to our codebase and this same codebase has been working for more than 6 months now.

We would really appreciate some help urgently as our shop doesn't work at all anymore.

**Comment by cavellblood** [comment]
@agjs We are experiencing the same issue. I think this issue might be related to issue https://github.com/Shopify/js-buy-sdk/issues/656.

**Comment by rebeccajfriedman** [comment]
@agjs @cavellblood Are you still experiencing this issue?

**Comment by agjs** [comment]
It's fixed now :). Thanks for asking @rebeccajfriedman.

**Comment by Etto91** [comment]
i have the same problem. someone can help me?

**Comment by littlefroginnovations** [comment]
I am still getting this same error in version 2.2.2

**Comment by cavellblood** [comment]
Yes, we also experience this issue too. @rebeccajfriedman it seemed to have disappeared not long after this issue was closed but now I checked our site and I do see this same warning in the console.

**Comment by arobbins** [comment]
Also getting this warning in version `2.2.1`.

**Comment by jegra** [comment]
We are seeing the same thing - currently using 2.0.1...

**Comment by mahlingam** [comment]
We are seeing the same thing - currently using 2.2.1. with buybutton 0.11.1. Buy button does not appear. @rebeccajfriedman fyi, this is a blocker for an upcoming enterprise release.

**Comment by mikeymicrophone** [comment]
We are having this issue intermittently on a store we just brought live this week.

**Comment by mikeymicrophone** [comment]
ok I see on the status page that there was a brief outage
