### ISSUE TITLE
LineItems Duplicate keys detected with Automatic Discounts

### ISSUE THREAD

**Issue by Patrick-ISKN** [Shopify/js-buy-sdk#658]
**Describe the bug**
The following error `Duplicate keys detected: '(lineitem id)' This may cause an update error.` is shown when the customer wants to add one more quantity of a product that already have an automatic discount applied, so the customer cannot update this lineitem quantities anymore.

**To Reproduce**
The automatic discount is applied with this following behaviour: if the customers orders 10x a specific product, he can get an accessory for free. 
- When ordering this accessory, the cart is well updated, the total price is adjusted with the discount, and the checkout URL brings me to the right recap of the order.
- Let's say we want to add one more same accessory (no matters if we have one free): the cart is updated correctly, adding a new line to the recap, but the duplicated key error appears. Even if we have the error, if we go to the checkout recap, the checkout is adjusted with my last modifications.
- Now If we want to update those last accessories quantites, the error persists and at this point the cart is not updated anymore, due to the conflict between the accessory key. The following error appears : `Uncaught (in promise) Error: [{"field":null,"message":"Line item with id (lineitem id) not found","code":"LINE_ITEM_NOT_FOUND"}]`

Please include code samples.
This is a Vue/Nuxt project but the essential code for the bug is there: 
For example to implement quantity, When click on button to update here's the method called:
```
const lineItemToAdd = [
 {
   id: product.shopifyData.id, //local custom of the lineitem id
   quantity: product.shopifyData.quantity + 1, //local custom of the lineitem quantity
  },
];
 this.$store.dispatch('shopify/updateItemInCheckout', lineItemToAdd)
  .then(() => {
          //some nuxt stuff
   });
```
And the Vuex Store call : 
```
  async updateItemInCheckout(
    { commit, state, getters },
    lineItemsToUpdate,
  ) {
    const checkoutId = state.checkout.id; //local state to stock the checkout
    await getters.shopifyClient.checkout
      .updateLineItems(checkoutId, lineItemsToUpdate)
      .then((checkout) => {
        //some nuxt stuff
      });
  },
```
**Expected behavior**
The cart should update its contents correctly. I don't really understand why this error appears because I manipulate the same lineitem, no matter if it gets a discount or not.

**Environment:**
 - OS: [Windows 10]
 - SDK Version [`v2.2.0`]

**Bug Report Checklist**
- [x] I have read and agree to the [CODE_OF_CONDUCT.md](https://github.com/Shopify/js-buy-sdk/blob/master/CODE_OF_CONDUCT.md)
- [x] I have read the [CONTRIBUTING.md](https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md) guidelines.
- [x] I have provided a detailed description of the bug, including code samples, and/or network data.
- [x] I have provided information about my development environment, including SDK version.

**Comment by rebeccajfriedman** [comment]
Hey @Patrick-ISKN - this is something we are looking into. Thanks for adding all these specific details!

**Comment by rebeccajfriedman** [comment]
As a temporary workaround, instead of using `updateLineItems`, you could use [replaceLineItems](https://github.com/Shopify/js-buy-sdk/blob/master/src/checkout-resource.js#L205-L224).

**Comment by Patrick-ISKN** [comment]
Thank you for your answer @rebeccajfriedman , i tried to temporary replace `updateLineItems` by `replaceLineItems`, and I now get the following error (my cart doesn't update anymore) : `Uncaught (in promise) TypeError: Cannot read property 'checkoutLineItemsReplace' of undefined`. Am I missing something?

**Comment by rebeccajfriedman** [comment]
This sounds like you are getting an error response. Can you inspect the graphql network request to see what errors are returned?

I just tested this code and am not seeing any errors:
```
const checkoutId = checkout.id;
const lineItems = [{variantId: checkout.lineItems[0].variant.id, quantity: 5}];

this.props.client.checkout.replaceLineItems(checkoutId, lineItems).then((checkout) => {
  console.log(checkout);
});
```

**Comment by Patrick-ISKN** [comment]
Okay this code is actually working but it replaces all my lineItems in my checkout by the last lineItem I ordered, and this is not really what I want to get. I don't think `replaceLineItems` would temporary solve my problem, I'm searching to adapt my checkout line items quantities right if those last ones have automatic discounts applied on them

**Comment by rebeccajfriedman** [comment]
To use `replaceLineItems`, you'd have to:
- Keep a local copy of the line items that should be in the cart
- Update the local copy to reflect the quantity change
- Submit the line items (updated) to the `replaceLineItems` mutation to attach them to the checkout object.

Or you could just wait for a fix on the `updateLineItems` mutation.

**Comment by jmignac** [comment]
Hey, folks! This issue should now be fixed. Please open a new issue if the problem persists.

**Comment by Patrick-ISKN** [comment]
Hey @jmignac , thank you for your fix, the problem is resolved 👍 ! But I keep get the `Duplicate keys detected` error in the console everytime I update my cart. It is not that important, but this error can be redundant everytime I update the cart (if I update my cart 5 times for examples, I get 35 duplicate keys errors in the console). Could there be a way (in the API?) to prevent this error to appear at every cart updates?
