### ISSUE TITLE
[DOCS] Generic methods should be private

### ISSUE THREAD

**Issue by richgilbank** [Shopify/js-buy-sdk#66]
Methods like https://github.com/Shopify/js-buy-sdk/blob/master/src/shop-client.js#L111-L133 should be hidden by default on the docs, unless explicitly toggled on. Right now they're listed as public.

**Comment by minasmart** [comment]
I'm pretty sure these are all marked as private now. Good to close?

**Comment by richgilbank** [comment]
Definitely, though I just realized the methods are still listed in the right navigation :/ - will open another issue
