### ISSUE TITLE
sortKey doesn't work on product connection in the unoptimized sdk

### ISSUE THREAD

**Issue by adrianocr** [Shopify/js-buy-sdk#662]
**Describe the bug**
If I add sortKey as an arg to the products connection in the unoptimized sdk, either I get a `PRICE is undefined` error or the client's call returns nothing and I get `model is undefined` instead of graphql specific error

Here's the code:

```js
try {
  const productsQuery = client.graphQLClient.query((root) => {
    root.add('shop', (shop) => {
      shop.addConnection('collections', {args: {first: 10, query:"title:" + this.collectionTitle}}, (collection) => {
        collection.addConnection('products', {args: {first: 150, sortKey:PRICE}}, (product) => {
          product.add('title');
          product.add('handle');
          product.add('availableForSale');
          product.add('tags');
          product.add('onlineStoreUrl');
          product.addConnection('images', {args: {first: 50}}, (image) => {
            image.add('src')
          })
          product.addConnection('variants', {args: {first: 50}}, (variant) => {
            variant.add('id');
            variant.add('title');
            variant.add('price');
            variant.add('compareAtPrice')
            variant.add('availableForSale')
          })
        });
      });
    });
  });
  client.graphQLClient.send(productsQuery).then(({model}) => {
    this.results = model.shop.collections[0].products;
    client.graphQLClient.fetchNextPage(this.results).then((products) => {
      let objects = this.results.concat(products.model);
      this.results = objects;
    });
  });
} catch (error) { console.log(error) }
```

On line 5 if I remove `sortKey` then it works perfectly. BUT this project needs to be able to sort by price, best selling, etc. 

**Expected behavior**
I expect the client to return the specific collection's products sorted by the key.

**Comment by StefanSlehta** [comment]
Hi @adrianocr ! Can you try constructing an enum using `client.graphQLClient.enum('PRICE')`, so your sortKey becomes `sortKey: client.graphQLClient.enum('PRICE')`.

**Comment by adrianocr** [comment]
@StefanSlehta  that did it, many thanks! 

I didn't see that documented anywhere and I read through the source code but didn't see any references to enums either. But now I see it in the graphql schema. 

Lastly (and let me know if I should open a separate issue for this or ask elsewhere), is there a way to do what I achieved above in a simpler form? Getting products for a specific collection..

**Comment by adrianocr** [comment]
@StefanSlehta also, the sortKey `UPDATED_AT` or `UPDATED_AT` both return an error. `PRICE` and `BEST_SELLING` work perfectly though

**Comment by Adu88** [comment]
@StefanSlehta you just saved me a day of work! thank you so much :)
