### ISSUE TITLE
Document pagination

### ISSUE THREAD

**Issue by lecoueyl** [Shopify/js-buy-sdk#669]
**Is your feature request related to a problem? Please describe.**
More detailed use case for pagination
- The example in https://shopify.github.io/js-buy-sdk/client.js.html#line28 is very basic and does not give an it how to make a proper pagination system (how to fetch a specific page)
- There is no code exemple in https://github.com/Shopify/storefront-api-examples

Maybe I don't really understand how the pagination system work within this GraphQL client, but I don't see how to build a pagination index system (eg: go to page [1 2 3 4 5]) with the current example

**Describe the solution you'd like**
In order to use simply use the API, add an example how to build a pagination system
- How to fetch the previous page
- How to get the total of pages

**Describe alternatives you've considered**
Fetching all products list with an other call and parse the result with the number of items to show per pages. But this denature the usage of GraphQL

**Comment by giotiskl** [comment]
+1 any updates or guidance on how to make use of pagination?

**Comment by lecoueyl** [comment]
I personally moved by using Apollo and using my own queries and mutation for more flexibility
