### ISSUE TITLE
[DOCS] Document listings queries

### ISSUE THREAD

**Issue by richgilbank** [Shopify/js-buy-sdk#67]
For methods like [`fetchQueryProducts`](http://shopify.github.io/js-buy-sdk/api/classes/ShopClient.html#method-fetchQueryProducts), we need to document what queries are supported. From poking around a bit, it seems a little inconsistent - `collection_id: ...` and `product_ids: [...]` work, but not `handle: '...'`, `title: '...'`, etc. 

@awd, is there any public documentation for these queries? Also, given it's a query, we should probably be returning an empty object when no resources match, instead of the full set of products. Any reason to return everything?

**Comment by awd** [comment]
We have an issue now for `handle` param: https://github.com/Shopify/shopify/issues/68294

I believe there is some google doc with the support query params: @alexaitken would know where that ended up.

Which query params are returning full sets instead of empty sets?

**Comment by richgilbank** [comment]
Looks like the full set is returned only for unsupported requests. i.e. `product_id: 'foo'` returns all the products in my shop (whereas `product_ids: ['foo']` returns the empty set, as expected). So, not a top priority case, just a little confusing as an error state.

**Comment by richgilbank** [comment]
Looks like the queries are documented here: https://docs.shopify.com/api/sdks/sales-channel-sdk/reading-products

**Comment by alexaitken** [comment]
I don't think that is wrong.  we don't validate all the params you send us work, just ignore things that don't make sense.

**Comment by richgilbank** [comment]
Fixed by https://github.com/Shopify/js-buy-sdk/pull/72
