### ISSUE TITLE
updateLineItems() doesn't work well when updating an item with discount

### ISSUE THREAD

**Issue by kilinkis** [Shopify/js-buy-sdk#673]
**Describe the bug**
I have an automated discount: When you buy one X item, you get one Y item with discount. X and Y are specific products.
So if I buy one X and 10 Y, one of the Y items will have the discount applied.
This works well.
In the Checkout page, those 10 Y items are split into two lines: 9 without discount in one row, and 1 with discount.
When I try to update the quantity of Y, let's say to 11. The API returns quantity 21. So, the existing 10 + the new 11.
Also, doesn't work if I try to decrease the quantity, it always sums the new quantity to the existing one.
If I disable the Automated Discount, it updates as expected.

I suspect that the splitting of the product has something to do with this. When I console log all items in the cart, I see the item split into two as well. Two nodes that are equal with the only difference being the quantity. One has the quantity of items have the discount applied and the other one, the remainder.

**To Reproduce**
Have several of the same item in the cart where at least one of them has a discount.
Then try to update the quantity.

Code samples.

```
if (this.state.product.isAlreadyAdded) {
  /**
   * If product is already added to the checkout, we want to update the quantity of it
   */

  this.options.shop.updateProductById(
    [
      {
        id: this.state.product.id,
        quantity: parseInt(this.quantity as any, 10), // this quantity is accurate
        variantId: this.variantId,
      },
    ] as any,
    () => this.syncControlsWithCheckout()
  );
} 
```

**Expected behavior**
Being able to update the quantity of an item that has a discount applied and get the proper calculation.

**Environment (please complete the following information):**
 - OS: Mojave
 - Browser: chrome
 - SDK Version `v1.8.0`

**Bug Report Checklist**
- [x] I have read and agree to the [CODE_OF_CONDUCT.md](https://github.com/Shopify/js-buy-sdk/blob/master/CODE_OF_CONDUCT.md)
- [x] I have read the [CONTRIBUTING.md](https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md) guidelines.
- [x] I have provided a detailed description of the bug, including code samples, and/or network data.
- [x] I have provided information about my development environment, including SDK version.

**Comment by kilinkis** [comment]
@rebeccajfriedman sorry to ping you here, but can we have some verify this please? thanks in advance

**Comment by jmignac** [comment]
Hey there! I created a snippet to try that scenario, and everything seems to be fine.
Here is what I did:

```
client.checkout.create().then((checkout) => {
  const checkoutId = checkout.id
  const lineItemsToAdd = [
    {
      variantId: ${variant1Id},
      quantity: 1
    },
    {
      variantId: ${variant2Id}
      quantity: 10
    }
  ];

  client.checkout.addLineItems(checkoutId, lineItemsToAdd).then((checkout) => {
    // => lineItem[1], regarding variant 2 and without the discount has quantity 9
    // => lineItem[2], regarding variant 2 and with the discount has quantity 1

    const extraLineItemToAdd = [
      {
        variantId: '${variant2Id},
        quantity: 1
      }
    ];

    client.checkout.addLineItems(checkoutId, extraLineItemToAdd).then((checkout) => {
      // => lineItem[1], regarding variant 2 and without the discount has quantity 10
      // => lineItem[2], regarding variant 2 and with the discount has quantity 1

     const lineItemsToUpdate = [
        {
          id: lineItem[2].id, // the one with the discount
          quantity: 2
        }
      ];

      client.checkout.updateLineItems(checkoutId, lineItemsToUpdate).then((checkout) => {
        // => lineItem[1], regarding variant 2 and without the discount has quantity 11
        // => lineItem[2], regarding variant 2 and with the discount has quantity 1
      });
    });
  });
});

```

The example above use both `addLineItems` and `updateLineItems` checkout functions.
Could you please let us know which function you are trying to use and what params are being passed in?

**Comment by kilinkis** [comment]
thank you for this @jmignac. I'll check it when I have some time.

**Comment by kilinkis** [comment]
hello again @jmignac, indeed, it works fine, there was an error in my code's logic.
Thanks for your time.
