### ISSUE TITLE
Concern of usage with shopify lite

### ISSUE THREAD

**Issue by mankamhung1** [Shopify/js-buy-sdk#675]
I have originally planned to use shopify basic plan.
But would it be possible to use this module with shopify lite instead of the basic one?
Ps. We don't need the shopify store, we would have our own web frontend store.

**Comment by StefanSlehta** [comment]
Hi @mankamhung1 
Yes, you can use shopify lite plan with buy button. Take a look [here](https://www.shopify.ca/lite)
