### ISSUE TITLE
Line Item Properties to Cart

### ISSUE THREAD

**Issue by jfefes** [Shopify/js-buy-sdk#68]
As per a discussion I had with the team at Unite-- I know this is coming, but this will help our team know when the update has been pushed.

Thanks!

**Comment by richgilbank** [comment]
Thanks @jfefes! Will follow up on the status of this as things progress :smile:

**Comment by minasmart** [comment]
Added to #51 (v0.2.0 punch list). Closing here in favour of that issue 😄

**Comment by ntdb** [comment]
Hey all, I see that `line item properties` has been crossed off from the list in #51. Is there a new ETA for this functionality?

**Comment by minasmart** [comment]
Hey @ntdb! I'm sorry I don't have a great answer for this, other than it is being worked on right now. It will be part of the `v1.0.0` release of the SDK. Once I have some resources dedicated to this feature I can post more updates.

In the mean time, new developments and functionality will slowly become visible in the [graphql branch](https://github.com/Shopify/js-buy-sdk/tree/graphql).

**Comment by hymnzzy** [comment]
Is there any timeline set for this for now?

**Comment by minasmart** [comment]
This is available on the beta branch, which should be rolling out shortly. It's currently being held up by a pagination bug that may be fixed today, or monday.

**Comment by napter** [comment]
@minasmart was this moved to production? Is there any documentation on it? I've been searching but haven't successfully found any. Is it also available on the buy button or just the buy sdk? 
Thank you!

**Comment by rebeccajfriedman** [comment]
https://github.com/Shopify/js-buy-sdk/blob/master/src/checkout-resource.js#L77-L99

**Comment by rebeccajfriedman** [comment]
https://github.com/Shopify/js-buy-sdk/tree/a8157554116795d184f65461d1c4a5ebcb76c381#updating-checkout-attributes

**Comment by rebeccajfriedman** [comment]
I updated the [README](https://github.com/Shopify/js-buy-sdk/blob/master/README.md#adding-line-items) to show how you can assign customAttributes to line items.

**Comment by napter** [comment]
@rebeccajfriedman thanks! I want to do this with an embedded cart using buy-button-js but I can't figure out how to get the checkout ID.  client.checkout.id on the cart below is undefined. How do I get the checkout ID?

`		ui.createComponent('product', {
			id: 2461692624960,
			node: document.getElementById('shopifynode'),
			options: {
				product: {
				buttonDestination: 'cart',
				},
				cart: {
					startOpen: true,
					'events': {
					}
				}
			}
		}).then((c) => {

        const lineItem = {variantId: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8yMjkyOTcwMjU4NDM4NA==', quantity: 1};
        client.checkout.addLineItems(client.checkout.id, [lineItem]).then((updatedCheckout) => {
          //checkoutWindow.location = updatedCheckout.webUrl;
		  console.log(checkout.lineItems);
        });
		}
`

**Comment by rebeccajfriedman** [comment]
@napter I suggest you ask on the buy-button-js repo!

**Comment by napter** [comment]
@rebeccajfriedman ok I will do. Are the line item customAttributes in that readme the same as "line item properties" referenced [here](https://help.shopify.com/en/themes/liquid/objects/line_item#line_item-properties) and [here](https://help.shopify.com/en/themes/customization/products/features/get-customization-information-for-products)? 

Thanks
