### ISSUE TITLE
404 on preflight requests v2.6.1

### ISSUE THREAD

**Issue by stevenwu** [Shopify/js-buy-sdk#687]
**Describe the bug**
Versioned endpoint introduced in 2.6.1 returns 404 on `OPTIONS` requests.

**To Reproduce**
```
> curl -X OPTIONS https://graphql.myshopify.com/api/2019-07/graphql -i
HTTP/2 404
date: Fri, 05 Jul 2019 21:41:47 GMT
content-type: text/html; charset=utf-8
content-length: 0
set-cookie: __cfduid=d500248605dc981f74e50769ff0dbe0481562362907; expires=Sat, 04-Jul-20 21:41:47 GMT; path=/; domain=.myshopify.com; HttpOnly
x-sorting-hat-podid: 55
x-sorting-hat-shopid: 13120893
x-request-id: 518f4b46-9106-4c98-9b61-78de6041bd9a
```

**Expected behavior**
```
> curl -X OPTIONS https://graphql.myshopify.com/api/graphql -i
HTTP/2 200
date: Fri, 05 Jul 2019 21:41:30 GMT
content-type: text/html
set-cookie: __cfduid=db1375e40cf6ad54775d3d0324b5fd50a1562362890; expires=Sat, 04-Jul-20 21:41:30 GMT; path=/; domain=.myshopify.com; HttpOnly
x-sorting-hat-podid: 55
x-sorting-hat-shopid: 13120893
vary: Accept-Encoding
allow: POST, OPTIONS
x-request-id: 8541c0f7-a794-4bc9-beb4-66decf1d1629

```

**Environment (please complete the following information):**
 - SDK Version [`v2.6.1`]

**Bug Report Checklist**
- [x] I have read and agree to the [CODE_OF_CONDUCT.md](https://github.com/Shopify/js-buy-sdk/blob/master/CODE_OF_CONDUCT.md)
- [x] I have read the [CONTRIBUTING.md](https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md) guidelines.
- [x] I have provided a detailed description of the bug, including code samples, and/or network data.
- [x] I have provided information about my development environment, including SDK version.

**Comment by swalkinshaw** [comment]
Thanks for sharing the `curl` requests. Did you actually run into this issue with the sdk itself?

For `OPTIONS` to work, you still need the proper json content-type and accept headers:

`curl -X OPTIONS https://graphql.myshopify.com/api/2019-07/graphql -i -H "Content-Type: application/json" -H "Accept: application/json"`

However you are correct that there's a difference between the unversioned and versioned endpoints so we'll look into that 👍

**Comment by jordan-mcrae** [comment]
Running into this issue with the SDK as well. Dropping back to `2.6.0` fixed the issue for me,

**Comment by rebeccajfriedman** [comment]
This should now be working as intended in `v2.6.1`.
I'll leave this issue open so that you can confirm!

**Comment by stevenwu** [comment]
Can confirm it's working. Thanks!
