### ISSUE TITLE
How to fetch SEO title and description?

### ISSUE THREAD

**Issue by denny64** [Shopify/js-buy-sdk#688]
**Describe the bug**
I am currently using the standard `client.product.fetchAll()`. No SEO title or description returns. How Do I retrieve these fields?

**To Reproduce**
Steps to reproduce the behaviour:

`client.product.fetchAll().then((data) => {
    res.status(200).json(data);
  });`

**Expected behavior**
Data returns as expected, but how do I retrieve the SEO fields?

**Bug Report Checklist**
- [x] I have read and agree to the [CODE_OF_CONDUCT.md](https://github.com/Shopify/js-buy-sdk/blob/master/CODE_OF_CONDUCT.md)
- [x] I have read the [CONTRIBUTING.md](https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md) guidelines.
- [x] I have provided a detailed description of the bug, including code samples, and/or network data.
- [x] I have provided information about my development environment, including SDK version.

**Comment by StefanSlehta** [comment]
Hi @denny64 , you can fetch an SEO field only on [Admin schema](https://help.shopify.com/en/api/graphql-admin-api/reference/object/product) product, but not on [Storefront API](https://help.shopify.com/en/api/storefront-api/reference/object/product) which is what this library uses.

**Comment by Huetarded** [comment]
Unless I am reading the API docs wrong, it looks like the SEO field is now available via the Storefront API. If this is true it would be very helpful to get it added in a future release.
