### ISSUE TITLE
Fetching a product by a nonexistant handle throws a difficult to understand error

### ISSUE THREAD

**Issue by s3ththompson** [Shopify/js-buy-sdk#690]
**Describe the bug**
Fetching a product by a nonexistant handle throws an error.

**To Reproduce**
A call to `client.product.fetchByHandle('does-not-exist')` fails with the following error:

```
TypeError: Cannot read property 'images' of null
    at /node_modules/shopify-buy/index.js:2322:50
    at Array.reduce (<anonymous>)↵    at fetchResourcesForProducts (/node_modules/shopify-buy/index.js:2320:31)
    at /node_modules/shopify-buy/index.js:2336:12
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

presumably because there is no check [here](https://github.com/Shopify/js-buy-sdk/blob/master/src/fetch-resources-for-products.js) for whether or not `productOrProduct` is null.

**Expected behavior**

I would expect the returned product to be null or a more descriptive error to be thrown.

**Environment (please complete the following information):**
 - OS: N/A
 - Browser: N/A
 - SDK Version: 2.6.1

**Bug Report Checklist**
- [x] I have read and agree to the [CODE_OF_CONDUCT.md](https://github.com/Shopify/js-buy-sdk/blob/master/CODE_OF_CONDUCT.md)
- [x] I have read the [CONTRIBUTING.md](https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md) guidelines.
- [x] I have provided a detailed description of the bug, including code samples, and/or network data.
- [x] I have provided information about my development environment, including SDK version.

**Comment by rebeccajfriedman** [comment]
Closed by https://github.com/Shopify/js-buy-sdk/pull/699
