### ISSUE TITLE
Meta Fields Retrieval using optimized js-buy-sdk 

### ISSUE THREAD

**Issue by naiduasn** [Shopify/js-buy-sdk#696]
**Is your feature request related to a problem? Please describe.**
Hi,
To fetch meta fields from storefront API, I have to use the unoptimized version of js-buy-sdk.
is it in the future plans of yours to automatically include this during product query?

**Describe the solution you'd like**
I should be able to get metafields when i query for products which are whitelisted by graphql admin api 

**Describe alternatives you've considered**
I will have to use unoptimized version which increases my size of apk

**Additional context**
NA

**Comment by naiduasn** [comment]
Ignore this. un-optimized version works for me

**Comment by jornwildenbeest** [comment]
Hi naiduasn, could you show the query you wrote to get the meta fields?
