### ISSUE TITLE
Products not rendering in IE 11

### ISSUE THREAD

**Issue by AdamChlan** [Shopify/js-buy-sdk#700]
**Describe the bug**
Products are not loading in on IE 11. Not seeing any console errors though.

**To Reproduce**
View https://coastguardfoundation.org/ways-to-give/merchandise in IE 11

**Expected behavior**
Would expect a grid of products to load in, like in other browsers.

**Environment (please complete the following information):**
 - Windows
 - IE 11
 - SDK Version: 1.2.0 on the link above, but tested 2.7.1 locally with no luck

**Additional context**
This is a Nuxt.JS site, which could also be playing a role. Would appreciate any thoughts that could help troubleshoot this issue.

**Bug Report Checklist**
- [x] I have read and agree to the [CODE_OF_CONDUCT.md](https://github.com/Shopify/js-buy-sdk/blob/master/CODE_OF_CONDUCT.md)
- [x] I have read the [CONTRIBUTING.md](https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md) guidelines.
- [x] I have provided a detailed description of the bug, including code samples, and/or network data.
- [x] I have provided information about my development environment, including SDK version.

**Comment by rebeccajfriedman** [comment]
Hi @AdamChlan - We've tested other sites on IE 11 and they are working as expected. I'm going to close out this issue, but if you see an error response from our GraphQL call in your Network tab, please reopen this issue and provide a snippet.
