### ISSUE TITLE
Uncaught (in promise)

### ISSUE THREAD

**Issue by Thornlock** [Shopify/js-buy-sdk#702]
**Describe the bug**
Our client has partner sites that use a buy button. The buy button sends info to our client's Shopify store's orders. The point is to send the partner site's address in a variable to the order's additional details like so: **var attributeValue = window.location.hostname;**
This usually works, but sometimes it doesn't and the reason is unclear.
I have however, bumped into an error like this:
```
(index):1 Uncaught (in promise) 
[{…}]
0: {message: "Variable id of type ID! was provided invalid value", locations: Array(1), extensions: {…}}
length: 1
__proto__: Array(0)
```

**To Reproduce**
Steps to reproduce the behaviour:
Error can usually be seen the first time when visiting one of our clients partner shops, for example: https://karateliitto.fi/fi/varustekauppa/puvut-ja-vyot/
However, if I reload the site this error won't pop up again.

**Code samples:**
**The error:**
```
Uncaught (in promise) [{…}] |  
-- | --
Promise.then (async) |  
ShopifyBuyInit @ (index):299 |  
load (async) |  
loadScript @ (index):286 |  
(anonymous) @ (index):278 |  
(anonymous) @ (index):587 |  
```

**The code:**

```
function loadScript() {
        var script = document.createElement('script');
        script.async = true;
        script.src = scriptURL;
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(script);
        script.onload = ShopifyBuyInit;
      }
```

**Part of the ShopifyBuyInit function. I cut off the end part of it because it mostly included stylings etc, so don't wonder if the function looks broken. The most important stuff is supposedly here:**

 ```
function ShopifyBuyInit() {
        var client = ShopifyBuy.buildClient({
          domain: 'budolandfi.myshopify.com',
          storefrontAccessToken: '3e04d2eb8bb55ebd1cfcdcd82cdb055c',
        });
var attributeKey = "kumppaniyritys";
var attributeValue = window.location.hostname;
var shopifyDomain = "budolandfi.myshopify.com";

try {
  for (var checkoutId, key, i = 0; i < localStorage.length; ++i) {    key = localStorage.key(i);    if (key.match(shopifyDomain + '.checkoutId')) {    checkoutId = localStorage.getItem(key);  } }  client.checkout.fetch(checkoutId).then((checkout) => {
    var obj = {};
    obj.key = attributeKey;
    obj.value = attributeValue;
    var input = {
      customAttributes: [obj]
    };
    client.checkout.updateAttributes(checkoutId, input).then((checkout) => {});
  });
}
catch (err) {
console.log('checkout not updated');
}
```

**Comment by rebeccajfriedman** [comment]
@Thornlock I could not repro the issue using your steps above. I'm going to close this issue, but please reopen it if you are still experiencing the issue and have consistently reproducible steps.
