### ISSUE TITLE
Question: How to Query Pages in Graphql using this library

### ISSUE THREAD

**Issue by robmellett** [Shopify/js-buy-sdk#703]
Hey there,

Thanks for your awesome work on the project!  I was just wondering how to query different objects in the Store Front API.

As per the docs I'm implementing the unoptimized version of SDK.  I'd like to be able to use the pagesByHandle connection.
```js
// fetch the large, unoptimized version of the SDK
import Client from 'shopify-buy/index.unoptimized.umd';
 
const client = Client.buildClient({
  domain: 'your-shop-name.myshopify.com',
  storefrontAccessToken: 'your-storefront-access-token'
});
```

```js
const pagesQuery = client.graphQLClient.query((root) => {
  root.addConnection('pages', {args: {first: 10}}, (page) => {
    page.add('id');
  });
});
 
// Call the send method with the custom products query
client.graphQLClient.send(pagesQuery).then(({model, data}) => {
  // Do something with the pages
  console.log(model);
});
```
However, the error I'm receving in the above is '**No field of name "page" found on type "QueryRoot" in schema**' - and I'm unsure how to proceed.

This is GraphQL resource I'm trying to access
https://help.shopify.com/en/api/storefront-api/reference/object/page

or via GraphQl
```graphql
query ($handle: String!) {
  pageByHandle(handle: $handle) {
    id,
    body,
    bodySummary,
    createdAt,
  }
}
```

Any help would be greatly appreciated :)

**Comment by robmellett** [comment]
Bump?  Any ideas on how to proceed with this one?

**Comment by rebeccajfriedman** [comment]
Hi @robmellett - I just tested your code exactly with my test shop, and I was able to get pages returned. Is it possible you are using an SDK release that predates the addition of `pages` in Storefront API? What SDK version are you using?

**Comment by robmellett** [comment]
Hey @rebeccajfriedman,

Thank you for the reply! I think I figured out the issue in the end.  It was because I was using the regular Shopify Buy SDK, whereas I needed the unoptimised version. 

For some reason the page resource wasn't included in the regular version.
