### ISSUE TITLE
How do i fetch all my 350 products? react native

### ISSUE THREAD

**Issue by 2basiry** [Shopify/js-buy-sdk#705]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

Please include code samples.

If the error you're dealing with is a network / API issue, please include the value of the `X-Request-ID` response header, the data sent to the API, and the payload of the response.

**Expected behavior**

**Environment (please complete the following information):**
 - SDK Version [e.g. `v1.2.0`]

**Additional context**

**Bug Report Checklist**
- [x] I have read and agree to the [CODE_OF_CONDUCT.md](https://github.com/Shopify/js-buy-sdk/blob/master/CODE_OF_CONDUCT.md)
- [x] I have read the [CONTRIBUTING.md](https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md) guidelines.
- [x] I have provided a detailed description of the bug, including code samples, and/or network data.
- [x] I have provided information about my development environment, including SDK version.

**Comment by rebeccajfriedman** [comment]
The [README](https://github.com/Shopify/js-buy-sdk#fetching-products) explains how to fetch products. If you would like to fetch a subsequent page of products, use the [fetchNextPage](https://github.com/Shopify/js-buy-sdk/blob/master/src/client.js#L82-L95) method.
