### ISSUE TITLE
Question: set currency for checkout

### ISSUE THREAD

**Issue by jarred** [Shopify/js-buy-sdk#706]
Now that Shopify Payments has [Multi Currency](https://help.shopify.com/en/manual/payments/shopify-payments/multi-currency) is it possible to set the currency via the SDK that will display in the checkout?

Passing through a `&currency=EUR` parameter to the url like the [docs suggest](https://help.shopify.com/en/manual/payments/shopify-payments/multi-currency/testing-multiple-currencies) does not do the trick.

Thanks.

**Comment by jarred** [comment]
I've had confirmation from the Payments team that adding a currency parameter to the checkout webUrl (eg `&currency=EUR`) is not supported.

Hoping it's possible to update the currency via this SDK. Otherwise I'll have to redirect to the Shopify frontend and create the cart there, which would be cumbersome.

**Comment by spencercanner** [comment]
Hey @jarred, `checkout.create(...)` accepts a `presentmentCurrencyCode`, which will create the checkout in the specified currency. More info can be found in the [docs](https://shopify.github.io/js-buy-sdk/CheckoutResource.html#create) 

Let me know if this resolves your issue

**Comment by jarred** [comment]
@spencercanner that's great. It certainly gets me partway there.

Do you know if it's possible to update the `presentmentCurrencyCode` of an existing checkout? My customers sometimes change the currency in the checkout, once products have been added.

**Comment by spencercanner** [comment]
To change the checkout currency, you'll need to create a new checkout using the updated `presentmentCurrencyCode`

**Comment by jarred** [comment]
Thanks @spencercanner
