### ISSUE TITLE
Return status code with failing requests

### ISSUE THREAD

**Issue by tasha-urbancic** [Shopify/js-buy-sdk#709]
I'm working on an app where we need access to the error status codes `402` and `403` to conditionally change the UI & copy to indicate to the user what type of issue (payment, forbidden access, etc) they are experiencing, and what the potential solution is. 

However, currently only `response.errors` is returned, not allowing us to access `response.status` which would include the status codes we need access to.

I am proposing a change to the following file:
[https://github.com/Shopify/js-buy-sdk/blob/master/src/default-resolver.js](https://github.com/Shopify/js-buy-sdk/blob/master/src/default-resolver.js) 

This would involve either returning the entire `response` (instead of just `response.errors`) like this:

```js
return function(response) {
  const { model, errors } = response;
      
  return new Promise((resolve, reject) => {
    try {
      const result = keys.reduce((ref, key) => {
        return ref[key];
      }, model);
    
      resolve(result);
    } catch (_) {
      if (errors) {
        reject(response); // Return the full response here
      } else {
        reject(defaultErrors);
      }
    }
  });
};
```

I am happy to open a PR, but seemingly would be a breaking change for anyone who depends on the current structure. I am not sure if there is an alternate, non-breaking change way of going about this. I am open to discussing ideas about the best way to go about this!

**Comment by tasha-urbancic** [comment]
I understand the point you are making, and I agree that we would not want to show this to a customer.

However, our app is a two sided integration:
1. Storefront:  Customers can shop products based on images (they would receive generic messaging)
2. Management: where Merchants can attach Shopify product variants to images making them shop-able on the Storefront

It is the Management part where we want to alert the merchant on any issues and give them specific instructions on how to solve them. For example being late on payments, or having an invalid token.

**Comment by rebeccajfriedman** [comment]
For the management piece, you should use the Admin API. It is not possible to modify products using the Storefront API. The JS Buy SDK is built as a wrapper to the Storefront API, which is unauthenticated.
