### ISSUE TITLE
Add a product with no variant

### ISSUE THREAD

**Issue by fandy** [Shopify/js-buy-sdk#719]
## Problem

The current way to add a product to cart without variants to cart is hacky.

In [`mutation checkoutLineItemsAdd`](https://github.com/Shopify/js-buy-sdk/blob/master/src/graphql/checkoutLineItemsAddMutation.graphql), `CheckoutLineItemInput` requires a variant ID. This is confusing when you have a product which has no variants, as you cannot pass in the default `shopifyId`.

The solution is to use the "Default Title" variant that every Shopify product has. This is confusing because it's undocumented and not in your Admin dashboard. I was misleading and I had to do some guessing to figure it out.

## Proposed solution

1. When the `shopifyId` of the root product is passed, add the `Default Title` variant (big change)
2. Document what to do when you have a product with no variants.

**Comment by rebeccajfriedman** [comment]
Hi @fandy - thanks for reaching out! We are unlikely to change the underlying API to support the functionality you proposed in #1.

I'm going to close this ticket, but I encourage you to make a PR to this repo (it's open source) to add in the documentation you feel is missing.
