### ISSUE TITLE
"product is null" thrown when fetchMultiple is called with non existent products

### ISSUE THREAD

**Issue by BottlecapDave** [Shopify/js-buy-sdk#726]
### Bug details 

**Describe the bug**
`product is null` is thrown (located in fetchResourcesForProducts) when calling `client.product.fetchMultiple` with an id that doesn't exist withing shopify

**To Reproduce**
If you call `client.product.fetchMultiple` passing in a shopify products id that doesn't exist, or that the client doesn't have access to, then an error is thrown

**Expected behavior**
I'd expect the error not be thrown and instead the unfound products to be ignored in the returned data.

**Environment (please complete the following information):**
 - OS: OSX
 - Browser: Firefox/Chrome
 - SDK Version: 2.7.1

**Additional context**

**Bug Report Checklist**
- [x] I have read and agree to the [CODE_OF_CONDUCT.md](https://github.com/Shopify/js-buy-sdk/blob/master/CODE_OF_CONDUCT.md)
- [x] I have read the [CONTRIBUTING.md](https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md) guidelines.
- [x] I have provided a detailed description of the bug, including code samples, and/or network data.
- [x] I have provided information about my development environment, including SDK version.

**Comment by rebeccajfriedman** [comment]
This issue is fixed in version `2.7.2` of the SDK.
