### ISSUE TITLE
'Variable id of type ID! was provided invalid value' error out of the blue

### ISSUE THREAD

**Issue by richgcook** [Shopify/js-buy-sdk#728]
Without changing anything on a site that's been live for a year I now seem to get an error `Variable id of type ID! was provided invalid value`. I am using `https://sdks.shopifycdn.com/js-buy-sdk/v1/latest/index.umd.min.js` and have had no problems until a few days ago (as I am aware).

My setup involves caching the products JSON every 30 mins and I return these via PHP. The initial variantID I am using (for when the user lands and before selecting a product) is:

`base64_encode($product['variants'][0]['admin_graphql_api_id'])`

Is this no longer the correct variant ID?

**Comment by DrTeePot** [comment]
@richgcook I'm looking into this now. Where is `admin_graphql_api_id` coming from? I'm looking at the `products.json` on my test site and don't see it.

**Comment by richgcook** [comment]
@DrTeePot Thanks. `admin_graphql_api_id ` is in `products.json` under `variants` > `admin_graphql_api_id` so on load I'm fetching the first variant by default using `$product['variants'][0]['admin_graphql_api_id']`

**Comment by richgcook** [comment]
I've ran a `base64_decode` and vice versa and the ID it's adding to cart is all correct. I have to say that sometimes it is working and sometimes it is not? Has something changes recently?
