### ISSUE TITLE
ERR_FILE_NOT_FOUND for carousel arrows

### ISSUE THREAD

**Issue by lolapriego** [Shopify/js-buy-sdk#729]
When fetching full view of a product with  "imgWithCarousel": true arrows for the carousel are not found.

**Context**
- Using latest SDK:  var scriptURL = 'https://sdks.shopifycdn.com/buy-button/latest/buy-button-storefront.min.js'; 
- Grabbed code snippet from Shopify console, not made any modifications.

<img width="652" alt="Screen Shot 2019-11-25 at 8 41 31 PM" src="https://user-images.githubusercontent.com/1484573/69592631-88b82e80-0fc4-11ea-985b-4f999799a420.png">
<img width="601" alt="Screen Shot 2019-11-25 at 8 41 36 PM" src="https://user-images.githubusercontent.com/1484573/69592634-8b1a8880-0fc4-11ea-8630-c437fa4d0d26.png">
<img width="646" alt="Screen Shot 2019-11-25 at 8 48 11 PM" src="https://user-images.githubusercontent.com/1484573/69592767-ffedc280-0fc4-11ea-8389-0bffbe793175.png">

**Comment by lolapriego** [comment]
Actually, it does work in prod but not in local. You may close the issue - it's not a blocker for us

**Comment by StefanSlehta** [comment]
Hi @lolapriego the link you're using is buy button storefront. If you're trying to use the latest `js-buy-sdk` which is this repo, that would be hosted on http://sdks.shopifycdn.com/js-buy-sdk/v2/latest/index.umd.min.js
Sorry for the confusion. 
Also, for your console error, looks like you might not be including the protocol `https://` correctly so it's trying to locate a file on your own computer?
