### ISSUE TITLE
createCheckout checkoutId collision  

### ISSUE THREAD

**Issue by markwbrown** [Shopify/js-buy-sdk#730]
**Please complete the checklist before filing an issue:**

- [ no ] Is this a "how to" question? For questions on how to use the SDK, implement features or other related questions, [please use our forums](https://community.shopify.com/c/Shopify-APIs-SDKs/bd-p/shopify-apis-and-technology).
- [ not at the moment, not enough information ] Is this something you can **debug and fix**? Create a pull request and contribute! Bug fixes and documentation fixes are welcome. You can read our [contribution](https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md) guidelines for more details.

None of the above? Create an issue. Be sure to include all the necessary information for us to understand and reproduce the problem:

### Bug details 

**Describe the bug**
There appears to be a collision issue with the createCheckout method from the js-buy-sdk.

**To Reproduce**
Steps to reproduce the behaviour:

I have not been able to reproduce -- this affected a customer on a client's store. Two customers were assigned the same checkoutId -- One had made an order and a number of days later another went to checkout but was shown the info from the previous customer's purchase. 

I'm sure this could be reproduced by putting createCheckout in a loop and see how long until a collision happens, but that might take a very long time. 

Please include code samples.

`if (!checkoutId) {

    return _jsBuySdk2.default.createCheckout({}).then(checkout => {

      res.redirect(`/?checkoutId=${checkout.id}`);

    });

  }`

This createCheckout method returns `checkoutMutation('checkoutCreate', { input: input }, query, this.graphQLClient); ` which appears to be a call to the Shopify API through graphQL. Bit of a black box at that point. I would presume Shopify is using Redis as a session store and that is where the checkoutID is generated. If this is the case, it is possible the secret used in session generation has a higher propensity to create collisions than one would expect.
 
If the error you're dealing with is a network / API issue, please include the value of the `X-Request-ID` response header, the data sent to the API, and the payload of the response.

API issue: yes, well.... sort of. More specifically, it appears to be an issue with however Shopify generates the checkoutId from the method createCheckout which itself references checkoutMutation which includes this.graphQLClient. I do not have visibility into Shopify's back-end to determine how the checkoutID is created, so everything I'm saying is speculation.

**Expected behavior**
I expected there would be no collisions with checkoutId, or that at the very least it would take a very long time to happen. 

**Environment (please complete the following information):**
 - OS: [centOS server, but this is a web app where all communication happens between client and Shopify. ]
 - Browser [chrome]
 - SDK Version [`1.0.0-alpha.9`]

**Additional context**

**Bug Report Checklist**
- [ x ] I have read and agree to the [CODE_OF_CONDUCT.md](https://github.com/Shopify/js-buy-sdk/blob/master/CODE_OF_CONDUCT.md)
- [ x ] I have read the [CONTRIBUTING.md](https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md) guidelines.
- [ x ] I have provided a detailed description of the bug, including code samples, and/or network data.
- [ x] I have provided information about my development environment, including SDK version.

**Comment by rebeccajfriedman** [comment]
We have not had any other reports of this. Feel free to reopen this ticket if it occurs again and you can provide more detailed information.

**Comment by markwbrown** [comment]
Rebecca, I’m actually asking for more detailed information here. I don’t see what good closing the issue does to address the problem. Is the issue rare? Probably. Is there something about the internals of the createCheckout method that could be explained so it isn’t just a black box? The odds of a collision happening seem very low, but the fact one happened in a relatively short time frame leads me to believe something about the internals of checkoutId generation does not lead to as unique of a checkoutId as one would expect. Since the API allows for a customAttribute to be passed, I’m wondering if passing in something as simple as a Date object would add a sufficient level of variability to whatever acts as a seed in the checkoudId creation so as to avoid future collisions.

**Comment by rebeccajfriedman** [comment]
Unfortunately, I cannot share the inner workings of our checkout system. There is also no change you can make on your side to affect the checkoutId being generated. I suggest checking any caching implementation in your web app. Also, the SDK version you are using is `1.0.0-alpha.9` - which was released in September 2017. I can't speak to the implementation of that version, but I would encourage you to consider upgrading to a more modern version.

If you have specific information about the checkout affected and the other customer who saw the checkout feel free to email custom-storefronts@shopify.com and someone might be able to investigate that specific case further.

**Comment by markwbrown** [comment]
I was already on with chat and they suggested I come here and the forum, which I did. Keeping checkoutId generation a black box is your prerogative, but something is wrong in your implementation.  A checkoutId that has been used for a previous order should never be reassigned, right? That just doesn't make sense to do. But it was in fact done.  I don't believe it is a caching issue, at least not with the storefront in question. It is pretty much boilerplate from the storefront-api-examples/node-js-buy repo and the specific call I have been referencing is one which asks for a checkoutId from the shopify API.

**Comment by markwbrown** [comment]
@rebeccajfriedman 
It seems the checkoutId is a base64 encoded string following the format: gid://shopify/Checkout/<31 character hexidecimal> + ?key= <32 character hexidecimal>. I suspect the first 7 characters of the first 31 character string are independent from the remaining 24 characters in the string, making the first 31 character hexidecimal string a concat of an ID (node ID? + some function...time/rand -- I'm not entirely sure) and a hash, either CRC-96(ZIP) or Crypt16. If this is true, it is not good and one component in the collision issue. The 2nd string of 31 characters could be one of many hashes, but looks like MD5. Since we know both CRC-96, Crypt16 and MD5 all have collision issues why is there not a step in Shopify's middleware to prevent the re-issue of a checkoutId that has been used on a previous purchase?
