### ISSUE TITLE
Argument 'currencyCode' on InputObject 'MoneyInput' has an invalid value.  

### ISSUE THREAD

**Issue by jericbas** [Shopify/js-buy-sdk#731]
### Bug details 

**Describe the bug**
I'm sending right `currencyCode`(USD) in 
 `checkoutCompleteWithCreditCardV2`, but it returns an error that the currencyCode is invalid

**To Reproduce**
Steps to reproduce the behaviour:

Please include code samples.

```

const checkoutId = 'zxczxcxzc'

const payment = {
  "paymentAmount":{
    "currencyCode":"USD", 
    "amount":"6.90"
  },
  "test":true,
  "idempotencyKey":"zedyhzam1-1575457126884",
  "billingAddress":{
    "firstName":"First",
    "lastName":"Last",
    "address1":"1st floor",
    "address2":null,
    "city":"Beverly Hills",
    "company":null,
    "country":"United States",
    "province":"California",
    "zip":"90210",
    "phone":"4324324324"
  },
  "type":"card",
  "paymentData":"tok_1FlvZFEfi4xyMZzWAFQaTaNh"
}

const method = 'checkoutCompleteWithTokenizedPaymentV2'
  const mutation = await client.graphQLClient.mutation(root => {
    root.add(method, { args: { checkoutId, payment } }, res => {
      res.add('payment', (pm) => {
       pm.add('id')
      })
    })
  })

  const response = await client.graphQLClient.send(mutation)

```

![image](https://user-images.githubusercontent.com/34228201/70137207-6a3eeb00-16c8-11ea-8f72-a9bbb5da0b08.png)

**Bug Report Checklist**
- [x] I have read and agree to the [CODE_OF_CONDUCT.md](https://github.com/Shopify/js-buy-sdk/blob/master/CODE_OF_CONDUCT.md)
- [x] I have read the [CONTRIBUTING.md](https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md) guidelines.
- [x] I have provided a detailed description of the bug, including code samples, and/or network data.
- [x] I have provided information about my development environment, including SDK version.

**Comment by rebeccajfriedman** [comment]
Hi @jericbas - you are passing the String value of the currency, but you actually need to be passing the currency code. You can fetch this with: `client.graphQLClient.enum("USD").key`

**Comment by jericbas** [comment]
Hi @rebeccajfriedma, I'm still getting the same response.

**Comment by rebeccajfriedman** [comment]
Did you also create the checkout using the currency code as I mentioned above?

**Comment by jericbas** [comment]
I replaced with String currency code with code you've mentioned.

```javascript
const payment = {
  "paymentAmount":{
    "currencyCode":  client.graphQLClient.enum("USD").key, 
    "amount":"6.90"
  },
...
}
```

**Comment by rebeccajfriedman** [comment]
Can you follow this guide? https://help.shopify.com/en/api/storefront-api/guides/multi-currency-guide#creating-a-checkout-by-specifying-the-currency

You need to pass the currency you'd like to use when you create the checkout AND when you complete the checkout.

**Comment by jericbas** [comment]
Still the same. USD is our only currency.

**Comment by rebeccajfriedman** [comment]
> Hi @jericbas - you are passing the String value of the currency, but you actually need to be passing the currency code. You can fetch this with: client.graphQLClient.enum("USD").key

My suggestion 6 days ago was incorrect. You need to pass `client.graphQLClient.enum("USD")`. I have just tested it locally and can confirm that it will indeed work with that value passed in.

**Comment by ilivestrong** [comment]
How to do pass enum in a postman request?
