### ISSUE TITLE
Can't seem to get fetchProduct working with the latest version bump

### ISSUE THREAD

**Issue by abishekrsrikaanth** [Shopify/js-buy-sdk#732]
### Bug details 

I just upgrade the SDK to the latest version (#725) that has been bumped to use the latest Shopify API version `2019-10`, but the method calls seem to fail. I am not sure if this has something to do with the cursor based pagination or if there is internally anything else causing this issue. A simple `client.product.fetch()` doesn't seem to work when the same code works if I revert back to #707. Anybody else seem to face issue with the latest version? The only method call that seems to work fine is `client.checkout.create()` and `client.checkout.fetch`.

**Comment by rebeccajfriedman** [comment]
Can you please post the query you are making that works on `2.7.2` but not on `2.8.1`, as well as your myshopifydomain so that we can look into this?

**Comment by abishekrsrikaanth** [comment]
@rebeccajfriedman, i am gonna close this. I removed the `node_modules` and ran `yarn install` and seems to be working fine now. I will reopen the ticket if I come across this again. Closing it for now.
