### ISSUE TITLE
Missing field

### ISSUE THREAD

**Issue by zemd** [Shopify/js-buy-sdk#734]
### Bug details 

`productsCount` is not available when I try to get it with `collection` query. 

**To Reproduce**
```
graphQLClient.query((root) => {
    root.add('collectionByHandle', { args: { handle } }, (collectionByHandle) => {
      collectionByHandle.add('id');
      collectionByHandle.add('handle');
      collectionByHandle.add('title');
      collectionByHandle.add('image', (image) => {
        image.add('originalSrc');
      });
      collectionByHandle.add('descriptionHtml');
      collectionByHandle.add('productsCount');
  });
});
```

this displays `No field of name "productsCount" found on type "Collection" in schema`

**Expected behavior**
it should return valid data.

**Environment (please complete the following information):**
 - OS: **OS X**
 - Browser [e.g. chrome, safari]: **node v9.11.2**
 - SDK Version [e.g. `v1.2.0`]: **2.8.1**

**Bug Report Checklist**
- [x] I have read and agree to the [CODE_OF_CONDUCT.md](https://github.com/Shopify/js-buy-sdk/blob/master/CODE_OF_CONDUCT.md)
- [x] I have read the [CONTRIBUTING.md](https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md) guidelines.
- [x] I have provided a detailed description of the bug, including code samples, and/or network data.
- [x] I have provided information about my development environment, including SDK version.

**Comment by rebeccajfriedman** [comment]
Hi @zemd - productsCount is not a supported field. See the [API documentation](https://help.shopify.com/en/api/storefront-api/reference/object/collection) for an exhaustive list of all fields available on the collection.

**Comment by zemd** [comment]
@rebeccajfriedman Hi Rebecca, thanks for you answer, is there a way to get it using this library? I still need to get somehow `productsCount`.

**Comment by rebeccajfriedman** [comment]
Unfortunately, it is not supported at this time, although we are tracking it on our backlog. I suggest posting on the [forums](https://community.shopify.com/c/Shopify-APIs-SDKs/bd-p/shopify-apis-and-technology) for suggestions for workarounds from other community members.
