### ISSUE TITLE
doc is not up to date with the mutation

### ISSUE THREAD

**Issue by f3ltron** [Shopify/js-buy-sdk#737]
I was figue out to use the add line items with the doc. But it is missing so maybe i looking bad or the doc in the shopify website is not up to date ? There differences with mutations present here and in the doc website. 

Can you explain me please ?

**Comment by rebeccajfriedman** [comment]
Hi @f3ltron - the checkoutLineItemsAdd mutation is deprecated in favour of [checkoutLineItemsReplace](https://help.shopify.com/en/api/storefront-api/reference/mutation/checkoutlineitemsreplace). That being said, if you'd still like to use checkoutLineItemsAdd, the documentation is available via [the full schema](https://github.com/Shopify/js-buy-sdk/blob/master/schema.json#L13493-L13541).

**Comment by f3ltron** [comment]
Why is it deprecated as they they looks not doing the same? The add add when replace you have to pass every cart items all the time ? Can we have more consistent examples in the doc so ?

**Comment by f3ltron** [comment]
Maybe you can passe a function helper that do the same job as the addItem to format the cart ?  @rebeccajfriedman
