### ISSUE TITLE
Include hidden articles in a query

### ISSUE THREAD

**Issue by peeppirnpuu** [Shopify/js-buy-sdk#746]
Hello

I am looking a way to include articles with `"Visibility: Hidden"` inside my query.

<img width="305" alt="Screen Shot 2020-02-27 at 15 30 32" src="https://user-images.githubusercontent.com/4577484/75449743-3812f180-5976-11ea-9a4e-993b9db42108.png">

I found that that `published_status` has been used for GraphQL queries before, but am uncertain how to put this into practice: https://community.shopify.com/c/Shopify-APIs-SDKs/GraphQL-admin-api-returns-unpublished-products-in-query-quot/td-p/528069

What I am trying to do is to hide some articles in category view but to show them via link. I am currently using tags to achieve this same functionality.

**Comment by DrTeePot** [comment]
The `JS Buy SDK` is powered by the [Storefront API](https://shopify.dev/docs/storefront-api). This API only exposes data that would be exposed to a regular customer on the storefront, like published articles (and products). 

If you need to build custom back-end functionality on top of Shopify check out the "Build an app" section of [our developer tutorials](https://shopify.dev/tutorials).
