### ISSUE TITLE
How to add multiple variants to cart with cart.addVariants ?

### ISSUE THREAD

**Issue by dmitrybelyakov** [Shopify/js-buy-sdk#75]
What would be the best way of adding multiple items to cart at once? 
Say we have a list (length may vary):

```
var addUs = [{quantity: 1, variant: superWrapper...}, {quantity: 1, variant: superWrapper...}]
```

Looking at the `cart.addVariants` [method documentation](http://shopify.github.io/js-buy-sdk/guide/), it states that it accepts variable number of arguments. It would be nice if we could unpack that list into function arguments, but since this is javascript, I'm not sure that is possible.

**Comment by richgilbank** [comment]
@dmitrybelyakov That should be possible with `cart.addVariants.apply(null, addUs)`, which would apply the array to the method, and each object as a separate argument in the `arguments` list. Does that cover your case?

**Comment by ccamarat** [comment]
That's the technique I'm using and it seems to work fine.

**Comment by dmitrybelyakov** [comment]
Sorry, I have actually written a reply to @richgilbank but probably forgot to post. I will do it again on Monday and provide a use case.

**Comment by dmitrybelyakov** [comment]
So here is what I do:

```javascript
//these are actual product ids
var ids = [5861929351, 5863604999, 5863612103];

shopify.fetchQueryProducts({product_ids: ids}).then(function(products){
    shopify.createCart().then(function(cart){

        var addUs = [];
        for(var index in products) {
            if(!products[index].selectedVariant) continue;
            addUs.push({
                quantity: 1,
                variant: products[index].selectedVariant
            });
        }


        // everything is fine until this step
        cart.addVariants.apply(null, addUs).then(function(cart){
            console.log(cart);
        });
    });
});
```

Here is the error i'm getting:

```
Uncaught (in promise) TypeError: Cannot read property 'lineItems' of null(…)
```

**Comment by dmitrybelyakov** [comment]
Ok, while i was writing this i actually found the issue. It is that you need to pass cart (instead of null) when doing `addVariants.apply()` so it looks like this:

```javascript
cart.addVariants.apply(null, addUs).then(function(cart){
    console.log(cart);
});
```

We can consider this a resolved issue. 

Huge thank you to @richgilbank and @ccamarat
