### ISSUE TITLE
Custom styling without iframes

### ISSUE THREAD

**Issue by bubbabaird** [Shopify/js-buy-sdk#757]
I'm trying to follow the instructions on this page: https://shopify.github.io/buy-button-js/advanced/ about "Custom styling without iframes" - I can't determine where I'm supposed to put this code.  I've tried many things but cannot get the iframes to be false and unstyle the css.  

For instance I can't determine where this code actually goes...

var options = {
  product: {
    iframe: false
  },
  cart: {
    iframe: false
  }
}

...because the instructions don't match up with where i'm supposed to put this code.  In my code I DO see...

options = {

... but the word "var" isn't there.

My goal here is to take over styling the CSS instead of using the provided CSS so I'm hoping you can help me determine how I can do that with shopify's buy now iframe.  This is the page that I have this iframe currently on: https://www.centralcarolinas.org/emmaus/shop 

Please help and thanks.

**Comment by StefanSlehta** [comment]
Hi! This is the repository for our low level SDK building custom storefronts. 

For your issue, look into using [buy button js](https://github.com/Shopify/buy-button-js)
