### ISSUE TITLE
Unable to get totalInventory field

### ISSUE THREAD

**Issue by DennisOosterling** [Shopify/js-buy-sdk#760]
### Bug details 
**Describe the bug**
Using `"shopify-buy": "^2.10.0"`
And the following initialization code: 
```js
shopify.buildClient({
    domain: `fake.myshopify.com`,
    storefrontAccessToken: fakeStoreFrontToken,
});
```

Im unable to receive the `totalInventory` field
![image](https://user-images.githubusercontent.com/31688709/80608919-cae41100-8a37-11ea-8729-4a402d412e21.png)

Permissions are to my knowledge correct:
![image](https://user-images.githubusercontent.com/31688709/80608980-e0593b00-8a37-11ea-8d31-03e7573ca024.png)

**To Reproduce**

- Have shopify store
- Create a private app and check all permissions for storefront api
- Set Webhook api version to `2020-04` (this might not even be needed since it's for the admin api)
- set up client
- get a product:
```js
client.product.fetchByHandle(handle).then((product) => {
      return product;
});
```
- Check the response, no totalInventory field present on product or variant

**Expected behavior**
totalInventory field present on product or variant

**Environment (please complete the following information):**
 - OS: OSX
 - Browser: chrome
 - SDK Version `2.10.0` / `2020-04`

**Additional context**
-

**Bug Report Checklist**
- [x] I have read and agree to the [CODE_OF_CONDUCT.md](https://github.com/Shopify/js-buy-sdk/blob/master/CODE_OF_CONDUCT.md)
- [x] I have read the [CONTRIBUTING.md](https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md) guidelines.
- [x] I have provided a detailed description of the bug, including code samples, and/or network data.
- [x] I have provided information about my development environment, including SDK version.

**Comment by StefanSlehta** [comment]
Hi @DennisOosterling , `js-buy-sdk` is not pulling all the available fields for all queryable objects. You can see all the fields we're pulling for [product here](https://github.com/Shopify/js-buy-sdk/blob/master/src/graphql/ProductFragment.graphql). 

You can look into this section of README and expand the sdk to pull any data you like.
https://github.com/Shopify/js-buy-sdk#expanding-the-sdk

Hope this helps!
