### ISSUE TITLE
Api not working `net::ERR_NAME_NOT_RESOLVED`

### ISSUE THREAD

**Issue by brilliant-ember** [Shopify/js-buy-sdk#762]
**Please complete the checklist before filing an issue:**

- [ ] Is this a "how to" question? For questions on how to use the SDK, implement features or other related questions, [please use our forums](https://community.shopify.com/c/Shopify-APIs-SDKs/bd-p/shopify-apis-and-technology).
- [ ] Is this something you can **debug and fix**? Create a pull request and contribute! Bug fixes and documentation fixes are welcome. You can read our [contribution](https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md) guidelines for more details.

None of the above? Create an issue. Be sure to include all the necessary information for us to understand and reproduce the problem:

### Bug details 

**Describe the bug**
Using the api always yields this error, making the api not usable.
![image](https://user-images.githubusercontent.com/23269759/82092136-aee29f80-96c6-11ea-9e22-ed2844778a69.png)
**Background info**
This is for a private app that can perform checkouts, unfortunately this api doesn't work and googling + asking around the slack channel didn't help ( I am an intern at the time and have access to the internal slack channel) 
**To Reproduce**
Steps to reproduce the behaviour:
Make sure you have a private app for your store, and it should have the storefront api working, then grab the api token that the stores's Admin UI will give you and use it for the request. below is a sample code used to produce the error.

``` html
<html>
    <script src="http://sdks.shopifycdn.com/js-buy-sdk/v2/latest/index.umd.min.js"></script>
    <!-- <script src='./js-buy-sdk-edited.js'></script> -->
    <script>
        const client = window.ShopifyBuy.buildClient({
          domain: 'https://the store .myshopify.com',
          storefrontAccessToken: 'ur token' ,          apiVersion:'2020-04'

        });;
    
        // Fetch all products in your shop
        client.product.fetchAll().then((products) => {
          // Do something with the products
          console.log(products);
        });

        
        </script>
<body>HI</body>


</html>
```

Please include code samples.

If the error you're dealing with is a network / API issue, please include the value of the `X-Request-ID` response header, the data sent to the API, and the payload of the response.

**Expected behavior**

**Environment (please complete the following information):**
 - OS: macOS Catalina 10.15.4
 - Browser Chrome
 - SDK Version v2

**Additional context**

**Bug Report Checklist**
- [ x] I have read and agree to the [CODE_OF_CONDUCT.md](https://github.com/Shopify/js-buy-sdk/blob/master/CODE_OF_CONDUCT.md)
- [ x] I have read the [CONTRIBUTING.md](https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md) guidelines.
- [ x] I have provided a detailed description of the bug, including code samples, and/or network data.
- [x ] I have provided information about my development environment, including SDK version.

**Comment by minasmart** [comment]
Hey there! If you look at the error that’s being posted, this is a network error. The client can’t resolve `https://https//`. This makes sense since the docs specify you provide the domain and not the scheme. 

See the example here:

https://github.com/Shopify/js-buy-sdk/blob/master/README.md#initializing-the-client

Please remove the scheme from your configured domain and this should work fine.
