### ISSUE TITLE
Country is not supported

### ISSUE THREAD

**Issue by jitendradev0891** [Shopify/js-buy-sdk#779]
Hello,

I am facing issue on updating shipping address. The error is "Country is not supported"

Also please check the screenshot for the issue.

![image](https://user-images.githubusercontent.com/48373914/90506514-071bb880-e172-11ea-95bf-fb7809ab6b40.png)

 let shippingAddress = {
      address1: 'WAMURAN',
      address2: 'WAMURAN',
      city: 'WAMURAN',
      company: '',
      country: 'Australia',
      firstName: 'jitendra',
      lastName: 'pal',
      phone: '8057884767',
      province: 'Queensland',
      zip: '4512'
    };

 client.checkout.updateShippingAddress(checkoutId, shippingAddress);

**Comment by vixdug** [comment]
@jitendradev0891 often this is due to using an invalid address. Can you try with a proper address with full formatting and see if this resolves your issue?
