### ISSUE TITLE
"Copy to clipboard" also copies "Copy to clipboard" to the clipboard

### ISSUE THREAD

**Issue by richgilbank** [Shopify/js-buy-sdk#78]
Something seems to be up with the "Copy to Cipboard" button on the Downloads page of the docs site - the first time I clicked it, the text I expected to be copied to my clipboard was, but "Copy to clipboard" (the button text) was also appended to it. I haven't been able to replicate since though, as the button doesn't seem to be having any affect whatsoever now (not copying), and there are no console errors logged. 
`¯\(ツ)/¯`
Any ideas @harismahmood89?

**Comment by harismahmood89** [comment]
@richgilbank you mentioned that you fixed this?

**Comment by harismahmood89** [comment]
Resolved in #80
