### ISSUE TITLE
Strange API response: Zip is not valid for Canada

### ISSUE THREAD

**Issue by davedbase** [Shopify/js-buy-sdk#781]
Hi there,

I'm having trouble getting a shipping update complete with the client. Have a look:

```
client.checkout.updateShippingAddress(cart.checkoutId, details).then(checkout => {
  setCart({
    ...cart,
    total: checkout.totalPrice,
    lines: checkout.lineItems
  });
  console.log(checkout);
})
.catch((err) => {
  console.error(err);
});
```
Details looks like so:
```
type ShippingDetails = {
  address1: string,
  address2: string,
  city: string,
  company: string,
  country: string,
  firstName: string,
  lastName: string,
  phone: string,
  province: string,
  zip: string
}
```
Zip is currently being passed with a proper Postal Code value. I've tried it with spaces, no spaces, lower case, upper case etc. The error is vague and comes from the API as a UserError type.

I'm wondering if we should be using postal or postalCode in the client instead? When I attempt using a different value (shot in the dark) I get `Zip can't be blank` as a UserError.

**Comment by StefanSlehta** [comment]
Hi @davedbase can you provide any request ids from the requests that are failing?

**Comment by davedbase** [comment]
@StefanSlehta that's really strange. I hopped online to retrieve the information and it seems to be working now. If the issue rears it's head again I'll come back to re-open and post. Could have been a one-off but pretty sure it was nothing with the code.
