### ISSUE TITLE
shippingLine not populating with relevant information

### ISSUE THREAD

**Issue by davedbase** [Shopify/js-buy-sdk#782]
### Bug details 

**Describe the bug**

I've implemented a good portion of the buy SDK and it's working wonderfully. I'm however trying to implement a custom shipping component that updates the address and retrieves the amount to display to the user. I have the address updating and am expecting _shippingLine_ to be populated however it returns as null.

The following is an x-request-id: cf59d15c-3e34-47de-ac7a-b5b612762592 for review.

The products that this is relevant to have a shipping component based on Printful. Printful likely computes the value and returns it to Shopify. The products are enabled to use shipping properly so I'd expect this to work unless there's another unrelated/uncontrollable issue.

**To Reproduce**

1. Add 3 products to your Buy Button
2. Via SDK add the products
3. Update shippingAddress fields
4. Retrieve the cart or review the checkout value returns on updating address and shippingLine is null

**Expected behavior**

shippingLine should return with my shipping cost.

**Environment (please complete the following information):**

MacOS
Chrome

**Comment by christerwpersson** [comment]
I haven't worked with Printful, so i'm not sure if that changes things (so i could be wrong here), but I believe that you'll first need to query for the availableShippingRates. When you've fetched these (you'll need to build a polling mechanism, that looks at the "ready" field, to determine when Shopify has computed the available shipping methods) you'll need to mutate the shippingLine with the selected shippingRate. When you've done this, then the shippingLine should then be set on your checkout.

To fetch the available shippingrates, you can expand the sdk (see readme on how to do that), e.g.

```
const query = graphQLClient.query(root => {
      root.add("node", { args: { id } }, node => {
        node.add("id")
        node.addInlineFragmentOn("Checkout", checkout => {
          checkout.add("shippingLine", shippingLine => {
            shippingLine.add("handle")
            shippingLine.add("priceV2", price => {
              price.add("amount")
              price.add("currencyCode")
            })
            shippingLine.add("title")
          })
          checkout.add("availableShippingRates", rates => {
            rates.add("ready")
            rates.add("shippingRates", rate => {
              rate.add("title")
              rate.add("priceV2", price => {
                price.add("amount")
                price.add("currencyCode")
              })
              rate.add("handle")
            })
          })
        })
      })
    })
```

It's described here (after the section on populating shipping address): https://shopify.dev/tutorials/create-a-checkout-with-storefront-api
