### ISSUE TITLE
Use the shared ESLint config

### ISSUE THREAD

**Issue by lemonmade** [Shopify/js-buy-sdk#79]
Hey folks, this is a pretty low-priority thing, but if you've got a little time, I'd love if you could try out the [shared JavaScript styleguide/ linting config](https://github.com/Shopify/javascript) and let me know what you think of it in practice.

**Comment by richgilbank** [comment]
:+1:, would love to switch over now that it's a little more fleshed out. Will take a look at migrating over in the next little while. Thanks @lemonmade!

**Comment by minasmart** [comment]
👍 

The only reason we didn't use it was because this project was started before it really existed. I'd love to switch over.
