### ISSUE TITLE
Retrieving New Products Returns `null` but Old Products Work 

### ISSUE THREAD

**Issue by sshaw** [Shopify/js-buy-sdk#793]
### Bug details 

**Describe the bug**

Old products created months or years ago return data. Products created today return `null`.

**To Reproduce**
Steps to reproduce the behaviour:

```js
client.product.fetch(newId).then(console.log).catch(console.error)
```

The underlying response body is: 

```json
{"data":{"node":null}}
```

ID:

```
x-request-id: 66f20bab-2254-4af3-b4e1-954d679ccffd
```

Query (generated by above API call):

```gql
fragment VariantFragment on ProductVariant {
  id
  title
  price
  priceV2 {
    amount
    currencyCode
  }
  presentmentPrices(first: 20) {
    pageInfo {
      hasNextPage
      hasPreviousPage
    }
    edges {
      node {
        price {
          amount
          currencyCode
        }
        compareAtPrice {
          amount
          currencyCode
        }
      }
    }
  }
  weight
  available: availableForSale
  sku
  compareAtPrice
  compareAtPriceV2 {
    amount
    currencyCode
  }
  image {
    id
    src: originalSrc
    altText
  }
  selectedOptions {
    name
    value
  }
  unitPrice {
    amount
    currencyCode
  }
  unitPriceMeasurement {
    measuredType
    quantityUnit
    quantityValue
    referenceUnit
    referenceValue
  }
}

fragment ProductFragment on Product {
  id
  availableForSale
  createdAt
  updatedAt
  descriptionHtml
  description
  handle
  productType
  title
  vendor
  publishedAt
  onlineStoreUrl
  options {
    id
    name
    values
  }
  images(first: 250) {
    pageInfo {
      hasNextPage
      hasPreviousPage
    }
    edges {
      cursor
      node {
        id
        src
        altText
      }
    }
  }
  variants(first: 250) {
    pageInfo {
      hasNextPage
      hasPreviousPage
    }
    edges {
      cursor
      node {
        ...VariantFragment
      }
    }
  }
}

query ($id: ID!) {
  node(id: $id) {
    __typename
    ...ProductFragment
  }
}

```

**Expected behavior**

I expect a product to be returned like it is normally

**Environment (please complete the following information):**
 - SDK Version: 2.11.0 and https://sdks.shopifycdn.com/js-buy-sdk/v2/latest/index.umd.min.js**Bug Report Checklist**
- [X] I have read and agree to the [CODE_OF_CONDUCT.md](https://github.com/Shopify/js-buy-sdk/blob/master/CODE_OF_CONDUCT.md)
- [X] I have read the [CONTRIBUTING.md](https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md) guidelines.
- [X] I have provided a detailed description of the bug, including code samples, and/or network data.
- [X] I have provided information about my development environment, including SDK version.

**Comment by vixdug** [comment]
@sshaw two thoughts: 
1. can you check the ID you are passing in? Can you post an example (want to ensure its the Storefront API ID vs. GID) 
2. Are the products published to your app or only on the Online Store channel?

**Comment by sshaw** [comment]
> Are the products published to your app or only on the Online Store channel?

This was the problem, it was only available via the online store 🎉 

I've never seen this option. I guess the old products were grandfathered into all channels but the new one must be explicitly added? 

I think that 1) something besides `null` should be returned. Even if this is "defined behavior" it's not good behavior. In the wonderful world of REST 403 may work but in the 200-everything world of GQL I'd hope for something besides `null` or 2) if not documented document it.

**Comment by sshaw** [comment]
P.S. *Thanks!*
