### ISSUE TITLE
How to add selling_plan in CheckoutLineItemInput

### ISSUE THREAD

**Issue by tufail** [Shopify/js-buy-sdk#796]
I like to use the option selling plan in this sdk and trying to send object 
`const lineItemsToAdd = [{
			variantId: 323223344, 
                        quantity: 3,
			selling_plan: 48824473 
		}];
`
in `client.checkout.addLineItems(checkoutId, lineItemsToAdd)`

but getting error
```diff
-Uncaught (in promise) Error: [{"message":"Variable $lineItems of type [CheckoutLineItemInput!]! was provided invalid value for 0.selling_plan (Field is not defined on CheckoutLineItemInput)","locations":[{"line":1,"column":3245}],"extensions":{"value":[{"variantId":"Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zNjgzMjkxOTE5MTcwNQ==","quantity":1,"selling_plan":48824473}],"problems":[{"path":[0,"selling_plan"],"explanation":"Field is not defined on CheckoutLineItemInput"}]}}]
```
as this is working in shopify store ...and the detail we can get from here https://shopify.dev/docs/themes/ajax-api/reference/cart
Please help us how can we use the selling plan from our store

**Comment by vixdug** [comment]
Hi @tufail 

Subscriptions are not yet available for the Storefront API / SDK. When they are it will be announced in the changelog.

**Comment by adrach** [comment]
any update on this yet?
thx

**Comment by sirrodgepodge** [comment]
yes please!

**Comment by zmonteca** [comment]
Bump.

**Comment by vixdug** [comment]
Hey - Subscriptions / Selling plans are available on the Storefront API however they require the use of the **cart** vs. **checkout**. Here is the documentation: https://shopify.dev/api/examples/subscriptions. You would need to connect with the Storefront API directly and redirect to a web checkout from **cart**.

**Comment by tarunsoftprodigy** [comment]
@vixdug How do I use it for my already set up storefront on buy-sdk?
