### ISSUE TITLE
Search Product By Name

### ISSUE THREAD

**Issue by Arcalise08** [Shopify/js-buy-sdk#797]
This might seem basic but how can I search a product by name?

I'm assuming i'd have to use the unoptimized version. My client has over 700 items in his shop and loading all the items and filtering through them on the frontend isnt feasible for his customers.

**Comment by vixdug** [comment]
I would suggest something like: 

```
const handle = 'product-handle';

client.product.fetchByHandle(handle).then((product) => {
  // Do something with the product
  console.log(product);
});
```

Otherwise, as you noted, you can build a custom query with the unoptimized version, passing in your query (just as if doing this from the Storefront API directly)
