### ISSUE TITLE
Discount Code Create(like Admin API)

### ISSUE THREAD

**Issue by jinming88** [Shopify/js-buy-sdk#798]
Hi. I wanna create a new discount code like Shopify admin API using this SDK.

Please visit these links.
https://shopify.dev/docs/admin-api/rest/reference/discounts/pricerule
https://shopify.dev/docs/admin-api/rest/reference/discounts/discountcode

Using these 2 endpoints, I can fully create a new discount code.
I added code to my Node JS embedded APP and it's working perfectly.
Now, I tried to call this embedded APP backend from react-native APP to create a new discount code.

But there are some issues so, I still didn't solve it.
So, I am going to use Shopify buy SDK for this function.
If possible then how can I do it?
Please give me your answer.
Thanks.
Jin

**Comment by vixdug** [comment]
Hi @jinming88 you will need to utilize the admin API for these actions. The Admin API is a secure API behind a key/password that will prevent customers from creating their own discount codes on the fly. It is not functionality that would be added into the Storefront API.
