### ISSUE TITLE
Add to cart doesn't update the add to cart analytics data in shopify

### ISSUE THREAD

**Issue by DennisOosterling** [Shopify/js-buy-sdk#804]
Hi all,

A bit of context, we have a custom store front written in react and we use shopify as an eCommerce backend using the js-buy-sdk and gatsby shopify plugin. 

We would like to use the metrics inside the shopify analytics to make some reports, it seems like the `Reached checkouts` and `Completed sessions` register correctly but the add to cart is always 0. 
See: 
![image](https://user-images.githubusercontent.com/31688709/103343257-f5391300-4a8b-11eb-98e6-c06964f4a614.png)

I suspect it's because the `add to cart` action happens on our custom storefront, and for the checkout we route to shopify with the checkoutUrl from the js-buy-sdk.

At this point I'm unsure if this should be a bug report, feature request or should be reported somewhere else (I also created a topic in shopify's [forums](https://community.shopify.com/c/Shopify-APIs-SDKs/js-buy-sdk-how-to-get-the-add-to-carts-to-show-in-shopify/m-p/1002848#M60612))

But it seems like when you add to cart with the js-buy-sdk shopify should also make an entry in the analytics area?

Expected: When adding to cart with the js-buy-sdk it should also update the analytics part of shopify.
Actual: When adding to cart the add to cart metric in shopify analytics stays 0.

**Comment by vixdug** [comment]
@DennisOosterling Currently this is expected behavior. The "Add to cart" metric relies on signals from a liquid storefront. Google Analytics will be best to have a full picture of what is happening on the headless storefront. We are aware of this feature request and considering options for the future.

**Comment by DennisOosterling** [comment]
@vixdug Thank you for the information
