### ISSUE TITLE
Payment Error on Shopify Checkout page if contact info is missing required fields

### ISSUE THREAD

**Issue by shawngrona** [Shopify/js-buy-sdk#805]
**Please complete the checklist before filing an issue:**

- [ N] Is this a "how to" question? For questions on how to use the SDK, implement features or other related questions, [please use our forums](https://community.shopify.com/c/Shopify-APIs-SDKs/bd-p/shopify-apis-and-technology).
- [N ] 
- [N ] Is this something you can **debug and fix**? Create a pull request and contribute! Bug fixes and documentation fixes are welcome. You can read our [contribution](https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md) guidelines for more details.

None of the above? Create an issue. Be sure to include all the necessary information for us to understand and reproduce the problem:

### Bug details 

**Describe the bug**
I was asked by support via ticket 21751611 to open an issue here to interact with dev team.  It does not seem this issue belongs here on the js-buy-sdk github, but support certain I should post here ;-)

On the following checkout link - We're unable to complete the payment step: https://psychedelicsupport.myshopify.com/42839539875/checkouts/3efe7c92e6f79bef4bd31c46ec5cf7dc

This is on the payment page of the shopify checkout, there are no errors in Console nor in the network tab.
<img width="1693" alt="Screen Shot 2021-01-12 at 9 16 43 AM" src="https://user-images.githubusercontent.com/7434518/104353567-e192a100-54bc-11eb-9ba3-cb146f51800f.png">
![image (12)](https://user-images.githubusercontent.com/7434518/104353606-eeaf9000-54bc-11eb-9de3-dd4e1cf383ff.png)

**To Reproduce**
Steps to reproduce the behaviour:
Please include code samples.

Steps to repro:
Add items to cart via shopify-buy sdk
Get the checkout url from shopify-buy cart.webUrl
Redirect the user via window.location.href to the above url
Complete the user details, name and address, but do not enter first name
Abandon the checkout
Go to admin settings and make first and last name required in checkout
Get the checkout url from shopify-buy cart.webUrl
Redirect the user via window.location.href to the above url
Complete the payment details (using stripe checkout w/ card 4242 4242 4242 4242)

Expected result:
error is surfaced - 'you need to update your contact details with first and last name'

Actual result:
screenshots as above, no error - 'Error - Payment' in title bar.

It appears that the Checkout page is not giving appropriate error about missing required fields (first name) when submitting the payment.

If the error you're dealing with is a network / API issue, please include the value of the `X-Request-ID` response header, the data sent to the API, and the payload of the response.

**Expected behavior**

**Environment (please complete the following information):**
 - OS: Windows
 - Browser - Chrome
 - SDK Version - shopify-buy 2.10

**Additional context**

The user had previously saved their contact details, without a first name.  I changed the Shopify 

**Bug Report Checklist**
- [X ] I have read and agree to the [CODE_OF_CONDUCT.md](https://github.com/Shopify/js-buy-sdk/blob/master/CODE_OF_CONDUCT.md)
- [X] I have read the [CONTRIBUTING.md](https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md) guidelines.
- [X] I have provided a detailed description of the bug, including code samples, and/or network data.
- [X] I have provided information about my development environment, including SDK version.

**Comment by vixdug** [comment]
Hey @shawngrona 

You're right that this is not specific to the SDK. You can replicate this through the liquid storefront as it really only pertains to checkout. I've triaged this to the correct team who is aware. Thanks!
