### ISSUE TITLE
Cant Remove Line Item From Cart

### ISSUE THREAD

**Issue by wickedmom** [Shopify/js-buy-sdk#838]
For whatever reason, I cant seem to remove a line item from my cart. Adding an item works perfectly fine though!

Here is my code.

```
const testRemove = () => {
    const checkoutId = checkoutID;
    const lineItemIdsToRemove = [item.id]

    // Remove an item from the checkout
    myShopifyClient.checkout.removeLineItems(checkoutId, lineItemIdsToRemove).then((checkout) => {
      // Do something with the updated checkout
      console.log(checkout.lineItems);
    });
  };
```

I'm getting the following error: 

`Unhandled Rejection (Error): [{"message":"invalid id","locations":[{"line":1,"column":3269}],"path":["checkoutLineItemsRemove"]}]`

So I assume it's something with the product's id? Even when I manually enter the product's id as a string or add the id as a string inside an array the same error occurs.

**Comment by jmmendivil** [comment]
![image](https://user-images.githubusercontent.com/1274534/125872092-247018e3-b6dc-481b-b018-3329c98a8cdf.png)

**Comment by ijazbacha** [comment]
> For whatever reason, I cant seem to remove a line item from my cart. Adding an item works perfectly fine though!
> 
> Here is my code.
> 
> ```
> const testRemove = () => {
>     const checkoutId = checkoutID;
>     const lineItemIdsToRemove = [item.id]
> 
>     // Remove an item from the checkout
>     myShopifyClient.checkout.removeLineItems(checkoutId, lineItemIdsToRemove).then((checkout) => {
>       // Do something with the updated checkout
>       console.log(checkout.lineItems);
>     });
>   };
> ```
> 
> I'm getting the following error:
> 
> `Unhandled Rejection (Error): [{"message":"invalid id","locations":[{"line":1,"column":3269}],"path":["checkoutLineItemsRemove"]}]`
> 
> So I assume it's something with the product's id? Even when I manually enter the product's id as a string or add the id as a string inside an array the same error occurs.

How do you fixed it
