### ISSUE TITLE
Please add support for productRecommendations method

### ISSUE THREAD

**Issue by DIma-Kush** [Shopify/js-buy-sdk#872]
It seems there is no support of productRecommendations method https://shopify.dev/api/storefront/reference/common-objects/queryroot?api%5Bversion%5D=2022-04#productrecommendations-2022-04

for returning related products

**Comment by DIma-Kush** [comment]
https://github.com/Shopify/js-buy-sdk/pull/873

**Comment by swalkinshaw** [comment]
Closed by https://github.com/Shopify/js-buy-sdk/pull/873

This will be included in the next release
