### ISSUE TITLE
Please release new changes with 2.15.0 tag version

### ISSUE THREAD

**Issue by dmytro-kushnir** [Shopify/js-buy-sdk#875]
Please release this work: https://github.com/Shopify/js-buy-sdk/issues/872

thanks.

**Comment by DIma-Kush** [comment]
hey @swalkinshaw ! do we have a release plan, as we really need this feature in our project?
Thanks in advance.

**Comment by melissaluu** [comment]
Hi @DIma-Kush - thanks for contributing! This change will be part of the next release that is planned for April 2022 when we upgrade the SDK to use the new Storefront API `2022-04` version.

**Comment by rafaelderolez** [comment]
@melissaluu Looks like we'll be going with Multipass in the end (regarding carts / checkouts / users).  Won't be needing to extend the sdk after all. Thanks though!
