### ISSUE TITLE
Converting GraphModel to POJO

### ISSUE THREAD

**Issue by fmoessle** [Shopify/js-buy-sdk#882]
Is there a way to convert the GraphModel from e.g. product.fetchAll() to a POJO?

I have issues with server-side rendering (nuxt), because the properties on e.g. a product are getter and not primitive values.

**Comment by MurmeltierS** [comment]
Hey @fmoessle I'm struggling with the same issue (nuxt), did you find a solution?

**Comment by MurmeltierS** [comment]
Exactly. JSON.parse/JSON.stringify is my workaround for the moment too.

This works, but it leaves me with the problem that the @types/js-buy-sdk are completely outdated.

**Comment by fmoessle** [comment]
I also realized this in a quite painful way 🙈 .
