### ISSUE TITLE
Missing MetafieldConnection in Product schema

### ISSUE THREAD

**Issue by czarekowyxjs** [Shopify/js-buy-sdk#910]
**Please complete the checklist before filing an issue:**

- [ ] Is this a "how to" question? For questions on how to use the SDK, implement features or other related questions, [please use our forums](https://community.shopify.com/c/Shopify-APIs-SDKs/bd-p/shopify-apis-and-technology).
- [ ] Is this something you can **debug and fix**? Create a pull request and contribute! Bug fixes and documentation fixes are welcome. You can read our [contribution](https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md) guidelines for more details.

None of the above? Create an issue. Be sure to include all the necessary information for us to understand and reproduce the problem:

### Bug details 

**Describe the bug**
**Product** schema has fields metafield and metafields. In version 2.15.1, metafield was type Metafield and metafields was type MetafieldConnection. Now both fields have same type: metafield. It makes impossible to fetch list of metafields for product.

**To Reproduce**
Try to add metafields connection to your request.

**Example of request which works for version 2.15.1, but doesn't for 2.16.1:**
```js
export const collectionsWithProductsQuery = client.graphQLClient.query((root: any) => {
  root.addConnection('collections', { args: { first: 100 } }, (collection: any) => {
    collection.add('title')

    collection.addConnection('products', { args: { first: 100 } }, (product: any) => {
      product.add('title')

      product.addConnection('metafields', { args: { first: 100 } }, (metafield: any) => {
        metafield.add('namespace')
        metafield.add('key')
        metafield.add('value')

        metafield.add('reference', (reference: any) => {
          reference.addInlineFragmentOn('MediaImage', (mediaImage: any) => {
            mediaImage.add('id')
            mediaImage.add('image', (image: any) => {
              image.add('id')
              image.add('altText')
              image.add('height')
              image.add('width')
              image.add('url')
              image.add('transformedSrc')
            })
          })
        })
      })
    })
  })
})
```

**Expected behavior**
It should return list of metafields. Exactly as it was in version 2.15.1

**Environment (please complete the following information):**
 - OS: Ubuntu 20
 - Browser Chrome
 - SDK Version: 2.16.1

**Additional context**

**Bug Report Checklist**
- [x] I have read and agree to the [CODE_OF_CONDUCT.md](https://github.com/Shopify/js-buy-sdk/blob/master/CODE_OF_CONDUCT.md)
- [x] I have read the [CONTRIBUTING.md](https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md) guidelines.
- [x] I have provided a detailed description of the bug, including code samples, and/or network data.
- [x] I have provided information about my development environment, including SDK version.

**Comment by riccardolardi** [comment]
@czarekowyxjs any update on how to query metafields using js-buy-sdk? Why was this issue closed?
