### ISSUE TITLE
Private methods listed in navigation

### ISSUE THREAD

**Issue by richgilbank** [Shopify/js-buy-sdk#92]
On pages like http://shopify.github.io/js-buy-sdk/api/classes/ShopClient.html, several methods are marked as private, but still appear in the navigation. These should probably be toggled by the controls at the top of the page. 
<img width="1438" alt="javascript_buy_sdk" src="https://cloud.githubusercontent.com/assets/1245284/14573149/31acdc8e-0321-11e6-8ac2-4bc6c7b98cab.png">

**Comment by swalkinshaw** [comment]
Fixed at some point, behaviour is correct now
