### ISSUE TITLE
FetchNextPage is not working since v2.17.0

### ISSUE THREAD

**Issue by jacksonwangdev** [Shopify/js-buy-sdk#920]
### Bug details 

**Describe the bug**
I have been using js-buy-sdk library in my React Native application
Before update to v2.17.0, i could fetch all the collection's products by using fetchWithProducts and then FetchNextPage for pagination. But after the update, i get the following:

`[TypeError: Cannot convert undefined value to object]`

**To Reproduce**
Steps to reproduce the behaviour:

The client is intialised as per normal:
```
var Shopify = Client.buildClient({
    domain: Constants.Shopify.url,
    storefrontAccessToken: Constants.Shopify.storefrontAccessToken,
});
```

Call the fetchWithProducts function:
```
fetchProductsByCollectionId: async (id, per_page) => {
        try {
            const responses = await Shopify.collection.fetchWithProducts(id, {productsFirst: per_page});
            return responses.products.map((item) => new Product(item));
        } catch (err) {
            console.log(err);
            return undefined;
        }
   }
```
And then call the FetchNextPage for pagination
```
fetchNextPage: async (list) => { // list is the output of fetchProductsByCollectionId function above
        if (!list) {return undefined;}
        try {
            const responses = await Shopify.fetchNextPage(list);
            if (responses) {
                const responseJson = responses.model;
                return responseJson.map((item) => new Product(item));
            }
            return undefined;
        } catch (err) {
            console.log(err);
            return undefined;
        }
    }
```

**Expected behavior**
fetchNextPage working fine and i can load more data when i'm scrolling down the product list

**Environment (please complete the following information):**
 - OS: MacOS Monteray
 - SDK Version v2.17.0

https://github.com/Shopify/js-buy-sdk/issues/920#tasklist-block-07048f48-c3be-4cd6-a577-03d477369e08

**Comment by melissaluu** [comment]
This is now fixed in the latest SDK `v2.17.1` - thanks for letting us know!
