### ISSUE TITLE
Buy Button Customization

### ISSUE THREAD

**Issue by AryaCreative** [Shopify/js-buy-sdk#93]
We would like to understand if we can fully customize the new Buy Buttons to function like the following link?  https://www.wickedgoodcupcakes.com/

We want the customer to be able to choose the quantity of each product from the "collection" page, and we would like for them to have to buy a minimum number and maximum number of products.  The flow would follow this exactly...we believe the new buy button would be the best way to achieve this.  Would love some feedback if this is possible...

1)      Home page.  Click on shop our cupcakes from the selection of categories on the left

2)      Select a collection to buy, clicking on the picture or buy now button

3)      Select the individual flavors that make up the X pack (X = 2 or 4 or 6).  The page automatically indicates when a sufficient quantity has been selected and provides the “Add to cart” button

4)      Immediately asked for zip code

5)      Immediately sent to form for shipping info and calendar for delivery date

6)      Shipping details confirmation page

7)      Shopping cart confirmation page with “Checkout” button

8)      Billing information page

9)      Abandoned process here, but you see the flow

**Comment by richgilbank** [comment]
Hi @AryaCreative, from what I understand, this shouldn't be a problem, and there's a few ways to do it. One would be using Shopify's Online Store channel and line item properties to pass information about the options through to checkout. Alternatively, with the JS Buy SDK (to sell from another site), you could model your JS in a way to require specific numbers of products to be added to the cart as well. This would have to be implemented on your end, as the SDK really only deals with retrieving product information from Shopify, adding it to a cart, and checking out - your specific use case would have to be developed. 

If you're looking to add this to an online store yourself, our [support team](https://support.shopify.com/?page=6) would be able to help you with more specifics on how to do so. With the JS Buy SDK, you could certainly implement the product and cart related pieces with JavaScript. 

In either case, the flow for checkout is going to have to be the way it currently works, so shipping estimates, billing information, etc are all located in the checkout section. [Here](https://checkout.shopify.com/10190495/checkouts/e7614826eede2d6dc83834d103642bd4?_fd=0&channel=buy_button&referer=https%3A%2F%2Fwidgets.shopifyapps.com%2Fchannel_admin%2Fembeds%2Fnew%3Fid%3D3017237251%26product_handle%3Dyllo-w%26product_name%3DYELLOW%252520W%26first_variant_id%3D8796696579) is an example of such a flow. 

If you have any additional questions, please let us know!
