### ISSUE TITLE
Unable to instantiate new checkouts

### ISSUE THREAD

**Issue by avcohen** [Shopify/js-buy-sdk#990]
### Bug details

**Describe the bug**
Unable to instantiate a new checkout using the `checkout.create` method

**To Reproduce**
Running in a Next.JS app

        import Client from 'shopify-buy';

        const Shopify = Client.buildClient({
            domain: process.env.SHOPIFY_STORE_DOMAIN,
            storefrontAccessToken: process.env.SHOPIFY_STOREFRONT_API_KEY,
            language: 'en-GB',
            apiVersion: '2024-07',
        });

        const newCheckout = await Shopify.checkout.create({
            presentmentCurrencyCode: 'GBP'
        });

![Image](https://github.com/user-attachments/assets/3d089457-844a-4da7-8516-f1e9a2123ef3)

**Expected behavior**
I'd expect the checkout to be created

**Environment (please complete the following information):**
 - OS: OS X
 - Browser [e.g. chrome, safari] - Chrome
 - SDK Version [e.g. `v1.2.0`] ^2.22.0
- Node Version: 18
- Package Manager: Bun

**Bug Report Checklist**
- [ X] I have read and agree to the [CODE_OF_CONDUCT.md](https://github.com/Shopify/js-buy-sdk/blob/main/CODE_OF_CONDUCT.md)
- [ X] I have read the [CONTRIBUTING.md](https://github.com/Shopify/js-buy-sdk/blob/main/CONTRIBUTING.md) guidelines.
- [ X] I have provided a detailed description of the bug, including code samples, and/or network data.
- [ X] I have provided information about my development environment, including SDK version.

**Comment by thipokch** [comment]
@avcohen  Is the SDK being deprecated here, because I'm having this issue too.
